### DISCUSSION TITLE
Discussion for the biweekly meeting (2023/01/14)

### DISCUSSION THREAD

**Discussion by johnlanni** [alibaba/higress#120] [General]
## 周会纪要
1. Higress Console 项目介绍：https://github.com/higress-group/higress-console    通过 Higress Admin API转换ingress/mcpbridge等资源等社区任务完成认领
2. Higress 解除对 istio 依赖的方案review和讨论，其中对 istio CRD 依赖去除后，需要设计 higress 自己的 wasmplugin CRD，也正好解决之前路由级匹配的配置可读性差的问题， 这块方案列在下面，大家可以一起讨论下
3. 社区认领任务的同学请联系我加进语雀空间，相关API设计文档都统一在这里维护和讨论

## 社区进展同步

1.  感谢 @Charlie17Li 将 pkg/bootstrap 的单测覆盖率提高到 71%
2. 感谢 @CH3CHO 完成了 key-rate-limit 插件 [README 文档](https://github.com/alibaba/higress/blob/main/plugins/wasm-cpp/extensions/key_rate_limit/README_EN.md)的英文翻译
3. `higress.io/destination` 注解支持了多个目标服务，可以按按权重路由，[配置示例](https://github.com/alibaba/higress/blob/main/samples/nacos-discovery/multi-destination.yaml)

**Comment by johnlanni** [comment]
移除 istio CRD 后，higress 需要对 wasmplugin 定义自己的 API，并实现对应 API 转换逻辑将生成的 wasmplugin 通过 xds 下发给 istio。
这个工作顺带可以优化下目前的路由域名级生效的配置不够直观的问题
当前 API 示例：
```yaml
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: request-block
  namespace: higress-system
spec:
  selector:
    matchLabels:
      higress: higress-system-higress-gateway 
  url: oci://<your_registry_hub>/request-block:1.0.0
  pluginConfig:
   # 这个配置会全局生效，但如果被下面规则匹配到，则会改为执行命中规则的配置
   block_urls:
   - "swagger.html"
   _rules_:
   # 路由级生效配置
   - _match_route_:
     - default/foo
     # default 命名空间下名为 foo 的 ingress 会执行下面这个配置
     block_bodys:
     - "foo"
   - _match_route_:
     - default/bar
     # default 命名空间下名为 bar 的 ingress 会执行下面这个配置
     block_bodys:
     - "bar"
   # 域名级生效配置
   - _match_domain_:
     - "*.example.com"
     # 若请求匹配了上面的域名, 会执行下面这个配置
     block_bodys:
     - "foo"
     - "bar"
```

higress API 示例：

```yaml
apiVersion: extensions.higress.io/v1alpha1
kind: WasmPlugin
metadata:
  name: request-block
  namespace: higress-system
spec:
  url: oci://<your_registry_hub>/request-block:1.0.0
  # 配置生效规则
  rules: 
  # 默认配置，只允许有一个，全局生效
  - default: true
    config:
      block_urls:
      - "swagger.html"
  # 匹配生效
  - match:
       # 匹配 ingress 名称，如果在 higress-system 命名空间下，可以省略 namespace/ 前缀
      ingress: default/foo
    config:
      block_bodys:
      - "foo"    
  - match:
      ingress: default/bar
    config:
      block_bodys:
      - "bar"
  - match:
      domain: "*.example.com"
    config:
      block_bodys:
      - "foo"
      - "bar"
```
