### DISCUSSION TITLE
istio的配置有办法平滑迁移嘛

### DISCUSSION THREAD

**Discussion by cuisongliu** [alibaba/higress#1408] [Q&A]
我之前使用的istio如何平滑迁移，比如我自己创建一个istio ns下的的service 然后gw vs dr 逻辑创建，目的是为了和默认的gateway的端口区分开。如何解决？

**Comment by cuisongliu** [comment]
需求是这样的，我有一些是nginx ingress 还有一部分是istio的配置，我看higress可以兼容两者，所以我想能否做到同时维护nginx 和istio .我们内部环境是内网的，但是没有dns所以只能通过nodePort区分，之前是nginx 31382端口，istio 32000端口，我想能否在higress 同时兼容两套，我做过尝试 部署两套higress 然后写不同的ingressclass 但是好像监控有点问题。不知道这个方案是否可行？或者ingress+gateway

**Comment by johnlanni** [comment]
能给一些配置示例吗，比如现在的配置是怎么样的，然后想确认哪些配置 higress 是否支持

**Comment by cuisongliu** [comment]
```
{{- if .Values.enable }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: unknown
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.16.2
    release: istio
  name: {{ include "istio-proxy.fullname" . }}
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: s3
      nodePort: {{.Values.proxy.istioNodePort}}
      port: {{.Values.proxy.istioPort}}
      protocol: TCP
      targetPort: {{.Values.proxy.istioPort}}
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  sessionAffinity: None
  type: NodePort
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "istio-proxy.fullname" . }}
  labels:
    {{- include "istio-proxy.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number:  {{.Values.proxy.istioPort}}
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "istio-proxy.fullname" . }}
  labels:
    {{- include "istio-proxy.labels" . | nindent 4 }}
spec:
  hosts:
    - "*"
  gateways:
    - {{ include "istio-proxy.fullname" . }}
  http:
    - route:
        - destination:
            host: {{.Values.proxy.host}}
            port:
              number: {{.Values.proxy.port}}
      headers:
        request:
          set:
            Origin: "{{.Values.origin}}"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "istio-proxy.fullname" . }}
  labels:
    {{- include "istio-proxy.labels" . | nindent 4 }}
spec:
  host: {{.Values.proxy.host}}
  trafficPolicy:
    loadBalancer:
      simple: {{.Values.proxy.loadBalancer}} #LEAST_CONN
    connectionPool: {{ toYaml .Values.proxy.connectionPool | nindent 6 }}
    outlierDetection: {{ toYaml .Values.proxy.outlierDetection | nindent 6 }}
{{- end }}

```

这是我们之前的helm chart 其实是想能开多个nodePort 进行负载

**Reply by johnlanni** [reply]
这个看上去是能兼容的，只是要调整下 selector

```yaml
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
```

```yaml
  selector:
    istio: ingressgateway
```

higress 的相关 label 是(假设默认安装在higress-system下):

```yaml
higress: higress-system-higress-gateway
```
