### DISCUSSION TITLE
合并slash

### DISCUSSION THREAD

**Discussion by chenvista** [alibaba/higress#1479] [Q&A]
之前使用nginx ingress 如https://open.xxx.com//mall/v1  多了个/  是可以的，现在迁移到higress后发现不行。因为这个给第三方调用的，第三方配置错了，协调比较麻烦，higress可以支持这种吗

**Comment by johnlanni** [comment]
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: merge-slash
  namespace: higress-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        name: envoy.filters.network.http_connection_manager
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          merge_slashes: true
```

apply 这个 envoyfilter 即可
