### DISCUSSION TITLE
easy-logger 自定义插件在 higress-gateway 加载了，但是功能没生效

### DISCUSSION THREAD

**Discussion by pteric** [alibaba/higress#1565] [Q&A] [answered]
按照文档 https://github.com/higress-group/higress-group.github.io/blob/main/src/content/docs/ebook/en/wasm14.md 自定义插件
easy-logger.yaml
```
apiVersion: extensions.higress.io/v1alpha1
kind: WasmPlugin
metadata:
  name: easy-logger
  namespace: higress-system
spec:
  matchRules:
  - ingress:
    - kubeflow/foo
    config:
      request: true
      response: true
      responseStatusCodes: "200,500,502,503"
  imagePullPolicy: IfNotPresent
  imagePullSecret: image-pull-secret-max-registry
  url: oci://max-image-repo-registry.cn-hangzhou.cr.aliyuncs.com/max/easy-logger:1.0.0
```

目前 controller 和 gateway 检查配置都加载了 easy-logger 插件，如下图：
controller：
![image](https://github.com/user-attachments/assets/7f66572b-1bc6-43da-ba71-f175df616601)
gateway：
![image](https://github.com/user-attachments/assets/b3d26178-b5d6-40e7-9196-ac5d94f6ebb2)
![image](https://github.com/user-attachments/assets/d9dc45fe-ea4b-4586-b273-f90d7144babe)

执行 curl 命令时流量通了但是 gateway 日志里没有打印 easy-logger 里的日志：
![image](https://github.com/user-attachments/assets/bdf78855-0be9-46dc-93cf-779d2b603fad)
