### DISCUSSION TITLE
请教关于客户端真实IP的问题

### DISCUSSION THREAD

**Discussion by brookqin** [alibaba/higress#1979] [Q&A]
现在的部署是内部局域网 k3s 部署 higress, 没有LB，手工给 higress-gateway 指定 IP，请求路径应该是 client(192.168.1.55) -> higress-ingress -> higress-gateway service(192.168.1.201) -> echo-service -> echo-pod

echo 服务获取不到真实 IP:
```
Request served by echo-server-5fbbdb95c8-kxj54

GET /echo HTTP/1.1

Host: 192.168.1.201
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7
Req-Start-Time: 1743315164046
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36
X-Envoy-Attempt-Count: 1
X-Envoy-Decorator-Operation: echo-server.default.svc.cluster.local:8080/echo
X-Envoy-Internal: true
X-Envoy-Original-Host: 192.168.1.201
X-Envoy-Route-Identifier: true
X-Forwarded-For: 10.42.0.1
X-Forwarded-Proto: http
X-Request-Id: 49ce91c7-d6eb-4f40-8b4c-8f23083ea92a
```

按照其它 issue 的讨论配置了 addXRealIpHeader: true / enableProxyProtocol: true 都无效，必须要在 gateway 上启用 externalTrafficPolicy: Local 才可以吗？

感谢🙏

**Comment by cr7258** [comment]
你是用 `kubectl port-foward` 的方式访问 higress-gateway 吗？

**Reply by brookqin** [reply]
不是的，higress-gateway 是 LoadBalancer 类型，手动指定了IP地址

```yaml
apiVersion: v1
kind: Service
metadata:
  name: higress-gateway
  namespace: higress-system
  labels:
    app: higress-gateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: higress-gateway
    app.kubernetes.io/version: 2.0.7
    helm.sh/chart: higress-core-2.0.7
    higress: higress-system-higress-gateway
  annotations:
    svc.load-balancer-ip: 192.168.1.201
spec:
  ports:
    - name: http2
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32358
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30592
  selector:
    app: higress-gateway
    higress: higress-system-higress-gateway
  clusterIP: 10.43.253.32
  clusterIPs:
    - 10.43.253.32
  type: LoadBalancer
  sessionAffinity: None
  loadBalancerIP: 192.168.1.201
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster
```

ingress 配置
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-server
  namespace: higress-system
  labels:
    higress.io/domain_higress-default-domain: 'true'
    higress.io/resource-definer: higress
  annotations:
    higress.io/destination: echo-server.default.svc.cluster.local:8080
    higress.io/ignore-path-case: 'false'
status:
  loadBalancer:
    ingress:
      - ip: 192.168.1.201
spec:
  ingressClassName: higress
  tls:
    - secretName: default
  rules:
    - http:
        paths:
          - path: /echo
            pathType: Prefix
            backend:
              resource:
                apiGroup: networking.higress.io
                kind: McpBridge
                name: default
```
