### ISSUE TITLE
使用higress.io/auth-tls-secret配置客户端证书未生效

### ISSUE THREAD

**Issue by ishells** [alibaba/higress#1008]
### Discussed in https://github.com/alibaba/higress/discussions/1004

<div type='discussions-op-text'>

<sup>Originally posted by **ishells** May 27, 2024</sup>
1、版本
     console 1.3.3 
     gateway 1.3.6
    controller 1.3.6
2、问题描述
    使用nginx ingress时，通过以下注解使用了自签的ca客户端证书（非域名ssl证书）+ https 验证客户端身份，客户端访问该域名时会验证客户端所安装的ca客户端证书
```
      ## 原 nginx 注解内容
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: 'true'
    nginx.ingress.kubernetes.io/auth-tls-secret: kube-system/ca-secret
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: '3'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'

    ## 完整nginx ingress yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: 'true'
    nginx.ingress.kubernetes.io/auth-tls-secret: kube-system/ca-secret
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: '3'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  name: xxx-gms-ing
  namespace: xxx-prod
spec:
  ingressClassName: xxx-nginx
  rules:
    - host: xxx.987ht.net
      http:
        paths:
          - backend:
              service:
                name: xxx-manage
                port:
                  number: 8808
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - xxx.987ht.net
      secretName: 987htnet-cert
```

    改用higress之后，按照文档指示，指定注解设置客户端ca证书，
    并额外设置域名ssl证书secret ( 客户端ca证书通过注解指定，域名ssl证书通过tls.secretName相关字段指定 ) 
    测试发现客户端证书并没有生效（不影响访问，未校验客户端已安装的同一CA证书），完整higress yaml如下：
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    higress.io/auth-tls-secret: 987ca-cacert
    higress.io/destination: xxx-gameserver.xxx-test.svc.cluster.local:10000
    higress.io/ignore-path-case: 'false'
    higress.io/ssl-redirect: 'true'
  labels:
    higress.io/domain_xxx-game-higress.987ht.net: 'true'
    higress.io/resource-definer: higress
  name: xxx-game-higress
  namespace: higress-test
spec:
  ingressClassName: higress
  rules:
    - host: xxx-game-higress.987ht.net
      http:
        paths:
          - backend:
              resource:
                apiGroup: networking.higress.io
                kind: McpBridge
                name: default
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - xxx-game-higress.987ht.net
      secretName: 987ht-net-cert
```

问题描述如上，请求协助排查解决~谢谢</div>

**Comment by johnlanni** [comment]
https://higress.io/zh-cn/docs/user/annotation-use-case#%E7%BD%91%E5%85%B3%E4%B8%8E%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%8F%8C%E5%90%91%E8%AE%A4%E8%AF%81mtls

这里有说明：

![image](https://github.com/alibaba/higress/assets/6763318/7dd9ec84-c29e-4b88-a250-6c3952c678fe)

**Comment by ishells** [comment]
我是按照文档的格式来设置的secret名称，但是我的域名secret和客户端ca证书不是一个，客户端ca证书是自签的

**Comment by ishells** [comment]
> https://higress.io/zh-cn/docs/user/annotation-use-case#%E7%BD%91%E5%85%B3%E4%B8%8E%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%8F%8C%E5%90%91%E8%AE%A4%E8%AF%81mtls
> 
> 这里有说明：
> 
> ![image](https://private-user-images.githubusercontent.com/6763318/334261118-7dd9ec84-c29e-4b88-a250-6c3952c678fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NjgyNjYsIm5iZiI6MTcxNjg2Nzk2NiwicGF0aCI6Ii82NzYzMzE4LzMzNDI2MTExOC03ZGQ5ZWM4NC1jMjllLTRiODgtYTI1MC02YzM5NTJjNjc4ZmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjhUMDM0NjA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mzg1MjdjNjg3ZDVhNmUyMTQyNDEwOWQ5NzcxOTI3NGYxYjg0NmYzOWZiZTgyMWRhZjdlNTY2OGY2ZDliNmJjMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AtXcii7OttBRQBb52xfYc3OA2hERfWrDD-CEYFLxJ9M)

我是按照文档的格式来设置的secret名称，但是我的域名secret和客户端ca证书不是一个，客户端ca证书是自签的

**Comment by ishells** [comment]
> > https://higress.io/zh-cn/docs/user/annotation-use-case#%E7%BD%91%E5%85%B3%E4%B8%8E%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%8F%8C%E5%90%91%E8%AE%A4%E8%AF%81mtls
> > 这里有说明：
> > ![image](https://private-user-images.githubusercontent.com/6763318/334261118-7dd9ec84-c29e-4b88-a250-6c3952c678fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NjgyNjYsIm5iZiI6MTcxNjg2Nzk2NiwicGF0aCI6Ii82NzYzMzE4LzMzNDI2MTExOC03ZGQ5ZWM4NC1jMjllLTRiODgtYTI1MC02YzM5NTJjNjc4ZmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjhUMDM0NjA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mzg1MjdjNjg3ZDVhNmUyMTQyNDEwOWQ5NzcxOTI3NGYxYjg0NmYzOWZiZTgyMWRhZjdlNTY2OGY2ZDliNmJjMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AtXcii7OttBRQBb52xfYc3OA2hERfWrDD-CEYFLxJ9M)
> 
> 我是按照文档的格式来设置的secret名称，但是我的域名secret和客户端ca证书不是一个，客户端ca证书是自签的

higress.io/auth-tls-secret: 987ca-cacert 注解中，987ca是自签客户端ca证书所在的secret

  tls:
    - hosts:
        - xxx-game-higress.987ht.net
      secretName: 987ht-net-cert
这个tls的secret是域名的证书，我试过按照 `987ht-net-cert-cacert` 的格式设置也没有生效，因为这个secret中没有ca.crt内容

就是想请教下，tls证书和ca客户端证书不是一个secret的情况下应该怎么使用该功能？

**Comment by 2456868764** [comment]
```
 tls:
    - hosts:
        - xxx-game-higress.987ht.net
      secretName: 987ht-net-cert
```
这里 secetName 是这个域名下服务端证书

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    higress.io/auth-tls-secret: 987ca-cacert
```
这里 tls secet 名称是 CA证书，名称要改为 987ht-net-cert-cacert
另外这个CA Secet 内容格式 

```
apiVersion: v1
data:
  cacert: XXXXX
kind: Secret
metadata:
  name: 987ht-net-cert-cacert
```
这些 secret 和 对应 ingress 要在同一个 namespace 下。同时客户端证书和服务端证书需要同个 CA证书 或者CA证书链下签发，mTLS 才能通过认证。

**Comment by ishells** [comment]
`客户端证书和服务端证书需要同个 CA证书 或者CA证书链下签发` 这个是硬需求吗？

我的客户端证书是纯自签的一个ca证书（之前在nginx ingress下会通过nginx.ingress.kubernetes.io/auth-tls-secret注解进行绑定，客户端比如本地电脑也会安装该ca证书，使用中能够验证生效），和域名不是一套证书链，麻烦请教下再这种情况下在higress中是不是无法生效？

**Comment by ishells** [comment]
经过测试可以了，感谢大佬回复协助解决问题！

做了如下修改供后续来者参考：
1. 同时存在两个secret
- 一个是域名服务端证书secret（name: 987ht-net-cert）
```yaml
# 域名服务端证书secret内容如下：
apiVersion: v1
data:
  tls.crt: >-
    xxx
  tls.key: >-
    xxx
kind: Secret
metadata:
  labels:
    # higress自动添加的
    higress.io/domain_987ht.net: 'true'
    higress.io/domain_wildcard.987ht.net: 'true'
    higress.io/resource-definer: higress
  name: 987ht-net-cert
  namespace: higress-test
```
- 一个是自签的客户端证书secret（name: 987ht-net-cert-cacert）
```yaml
# 自签客户端证书secret内容如下
apiVersion: v1
data:
  cacert: >-
    xxx
kind: Secret
metadata:
  name: 987ht-net-cert-cacert
  namespace: higress-test
```

2. higress ingress规则如下
```yaml
# ingress规则是在higress控制台创建的
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    higress.io/auth-tls-secret: 987ht-net-cert-cacert
    higress.io/destination: xxxx-gameserver.xxxx-test.svc.cluster.local:10000
    higress.io/ignore-path-case: 'false'
    higress.io/ssl-redirect: 'true'
  labels:
    higress.io/domain_kbx-game-higress.987ht.net: 'true'
    higress.io/resource-definer: higress
  name: xxx-game-higress
  namespace: higress-test
spec:
  ingressClassName: higress
  rules:
    - host: xxx-game-higress.987ht.net
      http:
        paths:
          - backend:
              resource:
                apiGroup: networking.higress.io
                kind: McpBridge
                name: default
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - xxx-game-higress.987ht.net
      secretName: 987ht-net-cert
```

3. 原有nginx ingress规则如下所示
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: 'true'
    nginx.ingress.kubernetes.io/auth-tls-secret: kube-system/ca-secret
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: '3'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  name: xxx-gms-ing
  namespace: xxx-prod
spec:
  ingressClassName: xxx-nginx
  rules:
    - host: xxx.987ht.net
      http:
        paths:
          - backend:
              service:
                name: xxx-manage
                port:
                  number: 8808
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - xxx.987ht.net
      secretName: 987htnet-cert
```
