### ISSUE TITLE
support  aws eks 

### ISSUE THREAD

**Issue by DevOpserzhao** [alibaba/higress#1051]
目前与AWS Load Balancer Controller 冲突

**Comment by CH3CHO** [comment]
请问冲突的具体表现是什么呢？

**Comment by DevOpserzhao** [comment]
```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foo
spec:
  ingressClassName: higress
  rules:
  - host: foo.bar.com
    http:
      paths:
      - pathType: Prefix
        path: "/foo"
        backend:
          service:
            name: foo-service
            port:
              number: 5678
```

Error from server (Forbidden): error when creating "foo.yml": admission webhook "vingress.elbv2.k8s.aws" denied the request: invalid ingress class: IngressClass.networking.k8s.io "higress" not found
