### ISSUE TITLE
Can `AutomaticHttps`+`CredentialConfig` set secret at other namespace?

### ISSUE THREAD

**Issue by zzjin** [alibaba/higress#1066]
## Why do you need it?
`CredentialConfig` can not use other namespace's TLS secret.

## How could it be?
users can set other namespaces secrets for domains.

## Other related information
kubernetes's `ingress-nginx` controller can use `--default-ssl-certificate` like "default/secret".
@see: https://kubernetes.github.io/ingress-nginx/user-guide/tls/#default-ssl-certificate

**Comment by johnlanni** [comment]
cc @2456868764

**Comment by zzjin** [comment]
The simple way: add parse logic with `CredentialConfig.TLSSecret`, eg support "sealos-system/wildcard-cert" instead of "wildcard-cert" for `higress-system` namespace.

```yaml
automaticHttps: false
fallbackForInvalidSecret: true
acmeIssuer:
- email: cloud@sealos.io
  name: letsencrypt
renewBeforeDays: 1
credentialConfig:
- domains:
    - '*.sealos.io'
    - 'sealos.io'
  tlsSecret: sealos-system/wildcard-cert
  # tlsSecret: wildcard-cert
```

But here comes the conflict:
when user also set `AutomaticHttps=true` alongside with namespace-ed `tlsSecret`, the `SecretMgr` cannot support it since it can only update and manage secret under `higress-system` own namespace.

https://github.com/alibaba/higress/blob/main/pkg/cert/secret.go#L48-L70
