### ISSUE TITLE
When matching the original path with regex, the rewriting path is not correct.

### ISSUE THREAD

**Issue by jaggerwang** [alibaba/higress#1077]
### Ⅰ. Issue Description

Add a rewirte policy in web console，to transform path like `/api/v1/user/test/test1` to path `/v1/open/test/test1` of service `user`。
![image](https://github.com/alibaba/higress/assets/1255011/049a46b8-30bf-4919-a733-b816141b8c62)

But the result path is `/v$1/open/$2`, not using the capture value of regex, and I can't find any related docs.
![image](https://github.com/alibaba/higress/assets/1255011/920953c3-cdad-4c05-8e68-3cc3be191c31)

### Ⅵ. Environment:

- Higress version:  1.4.1
- OS : macOS Chrome
- Others:

**Comment by jaggerwang** [comment]
另外目标服务这里有办法根据路径里匹配到的服务名来动态找到对应的 Kubernetes 服务吗？这样多个服务可以共享一条路由配置，而不是每个服务去重复一遍。
![image](https://github.com/alibaba/higress/assets/1255011/2c6abfa9-4bea-45c4-b60f-0c99b8f813f0)

**Comment by jaggerwang** [comment]
I also tried the ingress way:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /open/v$1/$2
    nginx.ingress.kubernetes.io/use-regex: "true"
  labels:
    app.kubernetes.io/component: user-open
    app.kubernetes.io/instance: basicai
    app.kubernetes.io/name: basicai
  name: user-open
spec:
  ingressClassName: higress
  rules:
  - host: open-cloud-dev.alidev.beisai.com
    http:
      paths:
      - backend:
          service:
            name: user
            port:
              number: 80
        path: /api/v(\d+)/user/(.+)
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - open-cloud-dev.alidev.beisai.com
    secretName: alidev.beisai.com
```

But it seems there have error about ssl certificate:
```bash
$ curl -v https://open-dev-cloud.alidev.beisai.com/api/v1/user/test/test1
*   Trying 47.103.200.40:443...
* Connected to open-dev-cloud.alidev.beisai.com (47.103.200.40) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* Recv failure: Connection reset by peer
* LibreSSL/3.3.6: error:02FFF036:system library:func(4095):Connection reset by peer
* Closing connection
curl: (35) Recv failure: Connection reset by peer
```

**Comment by johnlanni** [comment]
![image](https://github.com/alibaba/higress/assets/6763318/0d1032fa-b18c-4a58-b9b3-abff65050a92)
这个控制台的方式，目前对正则匹配只支持精确重写，你可以用另一个注解来实现这个正则重写能力，请参考文档：
https://higress.io/zh-cn/docs/user/annotation-use-case#rewrite%E9%87%8D%E5%86%99path

**Comment by jaggerwang** [comment]
前面也试过了 Ingress 方式，但是报 TLS 证书错误，这个证书一直被 Nginx Ingress Controller 接管的 Ingress 在使用，应该没有问题，比如下面的 Spring Cloud Gateway 的 Ingress。

![image](https://github.com/alibaba/higress/assets/1255011/9d5bbb0c-dca4-4f05-82fc-9fbef3b0f95c)

我们用的是阿里云 ACK，Ingress Controller 也是用的其自带的，最近想替换为 Higress，正在做技术调研。Higress 使用的 Helm 安装，其 values 文件如下。

```yaml
global:
  ingressClass: higress
  enableIstioAPI: false
  enableGatewayAPI: false

higress-core:
  gateway:
    replicas: 2
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: "1"
        memory: 2Gi
    nodeSelector:
      dedicated: app
  controller:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: "1"
        memory: 2Gi
    nodeSelector:
      dedicated: app

higress-console:
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      cpu: "1"
      memory: 2Gi
  nodeSelector:
    dedicated: app
  o11y:
    enabled: false
  pvc:
    rwxSupported: false

```
