### ISSUE TITLE
Higress console ingress not work when managed by higress, but it did work when managed by nginx ingress controller.

### ISSUE THREAD

**Issue by jaggerwang** [alibaba/higress#1110]
### Ⅰ. Issue Description

When using the following ingress, I can access higress console at `https://higress-console.alidev.beisai.com/`.

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: higress-console
spec:
  ingressClassName: nginx
  rules:
    - host: higress-console.alidev.beisai.com
      http:
        paths:
          - backend:
              service:
                name: higress-console
                port:
                  number: 8080
            path: /
            pathType: Prefix
  tls:
  - hosts:
    - higress-console.alidev.beisai.com
    secretName: alidev.beisai.com

```

![image](https://github.com/alibaba/higress/assets/1255011/39e5f42c-6e69-4165-a767-100bf41b6bf6)

But when I change the `ingressClassName` to `higress`, the browser shows another site which managed by nginx ingress controller.

### Ⅵ. Environment:

- Higress version:  1.4.1
- OS :
- Others: Aliyun ACK 1.28

**Comment by CH3CHO** [comment]
I believe the domain `higress-console.alidev.beisai.com` still points to the nginx gateway, right?

**Comment by jaggerwang** [comment]
Then how to switch a ingress managed by nginx ingress controller to higress? There is another ingress managed by higress and it works, but it not managed by nginx ever.

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:    nginx.ingress.kubernetes.io/rewrite-target: /open/v$1/$2
  labels:
    app.kubernetes.io/component: user-open
    app.kubernetes.io/instance: basicai
    app.kubernetes.io/name: basicai
  name: user-open
spec:
  ingressClassName: higress
  rules:
    - host: open-dev-cloud.alidev.beisai.com
      http:
        paths:
          - backend:
              service:
                name: user
                port:
                  number: 80
            path: /api/v(\d+)/user/(.+)
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - open-dev-cloud.alidev.beisai.com
      secretName: alidev.beisai.com
```
