### ISSUE TITLE
基于higress wasm sdk编写的插件无法被envoy加载

### ISSUE THREAD

**Issue by butterunderflow** [alibaba/higress#112]
请问higress的wasm sdk和[envoy的sdk](https://github.com/tetratelabs/proxy-wasm-go-sdk)是兼容的吗? 

我尝试在本地用envoy加载[这个教程](https://higress.io/zh-cn/docs/user/wasm-go.html)中的wasm插件, 但是envoy似乎无法正确加载编译后的wasm. 用这个SDK https://github.com/tetratelabs/proxy-wasm-go-sdk 就没有问题, 请问你们有遇到过类似的问题吗? 有没有什么解决思路呢

**Comment by butterunderflow** [comment]
感谢回复!
这是部分envoy log:
```
[2022-12-14 10:36:14.438][8273][info][config] [source/server/configuration_impl.cc:87] loading 0 static secret(s)
[2022-12-14 10:36:14.438][8273][info][config] [source/server/configuration_impl.cc:93] loading 2 cluster(s)
[2022-12-14 10:36:14.441][8273][info][config] [source/server/configuration_impl.cc:97] loading 2 listener(s)
discovered admin address: 0.0.0.0:8001
[2022-12-14 10:36:14.535][8273][warning][wasm] [source/extensions/common/wasm/context.cc:1175] wasm log: [my-plugin] need config
[2022-12-14 10:36:14.535][8273][error][wasm] [source/extensions/common/wasm/wasm.cc:109] Wasm VM failed Failed to configure base Wasm plugin
[2022-12-14 10:36:14.537][8273][critical][wasm] [source/extensions/common/wasm/wasm.cc:471] Plugin configured to fail closed failed to load
[2022-12-14 10:36:14.539][8273][critical][main] [source/server/server.cc:117] error initializing configuration 'envoy_configs/higress-go-plugin0.yaml': Unable to create Wasm HTTP filter my-plugin
[2022-12-14 10:36:14.539][8273][info][main] [source/server/server.cc:925] exiting
Unable to create Wasm HTTP filter my-plugin
error: envoy exited with status: 1
```
这是我的envoy配置
```yaml
static_resources:
  listeners:
    - name: main
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 18000
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: auto
                route_config:
                  name: echo
                  virtual_hosts:
                    - name: echo
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: echo
                http_filters:
                  - name: envoy.filters.http.wasm
                    typed_config:
                      "@type": type.googleapis.com/udpa.type.v1.TypedStruct
                      type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
                      value:
                        config:
                          name: "my-plugin"
                          configuration:
                            "@type": type.googleapis.com/google.protobuf.StringValue
                            value: ""
                          vm_config:
                            runtime: "envoy.wasm.runtime.v8"
                            code:
                              local:
                                filename: higress-go-plugin0/plugin.wasm
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router


    - name: echo
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 38140
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: auto
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: admin
                http_filters:
                  - name: envoy.filters.http.wasm
                    typed_config:
                      "@type": type.googleapis.com/udpa.type.v1.TypedStruct
                      type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
                      value:
                        config:
                          configuration:
                            "@type": type.googleapis.com/google.protobuf.StringValue
                            value: "echo"
                          vm_config:
                            runtime: "envoy.wasm.runtime.v8"
                            code:
                              local:
                                filename: "echo.wasm"
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router


  clusters:
    - name: echo
      connect_timeout: 5000s
      type: strict_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: echo
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 0.0.0.0
                      port_value: 38140
    - name: admin
      connect_timeout: 5000s
      type: strict_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: admin
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 0.0.0.0
                      port_value: 8001


admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```
其中higress-go-plugin0/plugin.wasm是编译后插件的路径.

**Comment by johnlanni** [comment]
[2022-12-14 10:36:14.535][8273][warning][wasm] [source/extensions/common/wasm/context.cc:1175] wasm log: [my-plugin] need config

因为你的代码里为ctx设置了 `ParseConfigBy`，但实际上没有传配置，所以报了这个错。
而且目前是兼容 istio 的 WasmPlugin 模式使用的，传入的配置需要是 json 格式。

**Comment by butterunderflow** [comment]
感谢解答. 
我这里应该是有插件配置的吧, 不是指的这里的 `configuration` 字段吗?
```yaml
                        config:
                          name: "my-plugin"
                          configuration:
                            "@type": type.googleapis.com/google.protobuf.StringValue
                            value: ""
```

后来我尝试了一下把这个 `ParseConfigBy` 去掉, 依然无法启动, 是因为这是higress sdk必要的设置吗?

https://github.com/alibaba/higress/blob/main/plugins/wasm-go/pkg/wrapper/plugin_wrapper.go#L105
