### ISSUE TITLE
Implement  AI quota plugin

### ISSUE THREAD

**Issue by johnlanni** [alibaba/higress#1154]
## Why do you need it?

我们已经有了 AI token 限流插件，可以实现针对特定调用方的每秒/分钟/小时/天的 token 调用量限制。

比如配置方式是：

key-auth 插件定义不同 consumer 的 Authoration Bearer Header

```yaml
consumers:
- credential: "Bearer 123"
  name: "consumer1"
- credential: "Bearer abc"
  name: "consumer2"
keys:
- "Authorization"
```

然后 ai token 限流插件配置:

```yaml
redis:
  password: 123456
  service_name: "redis.dns"
rule_items:
- limit_by_consumer: ""
  limit_keys:
  - key: "consumer1"
    # 限制 1M token 每天
    token_per_day: 1000000
- limit_by_consumer: ""
  limit_keys:
  - key: "consumer2"
    # 限制 10k token 每天
    token_per_hour: 10000
rule_name: "test"
```

这可以满足 token 限流场景需求，但无法满足给特定 consumer 分配固定的 Quota 的场景，例如用户充值后分配对应 Quota，用完为止，再充值再刷新 Quota。

所以我们需要一个 AI Quota 管理插件。

### 基本能力

```yaml
redis:
  password: 123456
  service_name: "redis.dns"
redis_key_prefix: chat_quota
```

`redis_key_prefix` 用于指定 redis 中用于存储 quota  key 的前缀，和 consumer name 拼接为最终的 key，用于存放 consumer 的 Quota。例如最终 key 为: `chat_quota#consumer1`

每次 LLM 请求结束后，计算 Quota 消耗，再去更新 redis 中这个 key 对应的 value，例如原本 value 为 1000， 本次消耗 100，则更新后的值为 900。

每次 LLM 请求开始前，在 redis 中查找 key 对应 value 的值，如果小于等于 0，则拒绝当次访问。

### 支持Quota管理的能力

```yaml
redis:
  password: 123456
  service_name: "redis.dns"
redis_key_prefix: chat_quota
admin_consumer: consumer3
admin_path: /quota
```

这里设定 consumer3 为管理员用户，这个用户可以更新其他用户的 quota，假定其 bearer token 为 "xxxxxx"

#### quota 刷新

如果当前请求 url 的后缀符合 admin_path，例如插件在 example.com/v1/chat/completions 这个路由上生效，那么更新这个路由的 quota 的方式为：

curl  https://example.com/v1/chat/completions/quota/refresh -d "consumer=consumer1&quota=10000" -H 'Authorization: Bearer xxxxxx'

这样 redis 中 chat_quota#consumer1 的值就会被刷新为 10000

#### quota 查询

也可以查询特定用户的quota：

curl  https://example.com/v1/chat/completions/quota?consumer=consumer1  -H 'Authorization: Bearer xxxxxx'
将返回： {"quota": 10000, "consumer": "consumer1"}

#### quota 增删

还可以直接增删 quota：

curl  https://example.com/v1/chat/completions/quota/delta -d "consumer=consumer1&value=100" -H 'Authorization: Bearer xxxxxx'

这样 redis 中 chat_quota#consumer1 的值就会增加100，可以支持负数，则减去对应值
