### ISSUE TITLE
Based on the geo-ip plugin, extend the capabilities of the ai-promopt-decorator plugin.

### ISSUE THREAD

**Issue by johnlanni** [alibaba/higress#1223]
## Why do you need it?

基于[geo-ip 插件](https://github.com/alibaba/higress/pull/1172)的能力，让  [AI 提示词装饰器插件
](https://github.com/alibaba/higress/tree/main/plugins/wasm-go/extensions/ai-prompt-decorator) 可以实现以下功能：

当配置：

```yaml
prepend:
- role: system
  content: "提问用户当前的地理位置信息是，国家：${geo-country}，省份：${geo-province}, 城市：${geo-city}"
```

使用以上配置发起请求：

```bash
curl http://localhost/test \
-H "content-type: application/json" \
-d '{
  "model": "gpt-3.5-turbo",
  "messages": [
    {
      "role": "user",
      "content": "明天天气怎么样"
    }
  ]
}
```

经过插件处理后，实际请求为：

```bash
curl http://localhost/test \
-H "content-type: application/json" \
-d '{
  "model": "gpt-3.5-turbo",
  "messages": [
    {
      "role": "system",
      "content": "提问用户当前的地理位置信息是，国家：中国，省份：浙江, 城市：杭州"
    },
    {
      "role": "user",
      "content": "明天天气怎么样"
    }
  ]
}
```
