### ISSUE TITLE
404 when using wildcard gateway with ingress

### ISSUE THREAD

**Issue by nbragin4** [alibaba/higress#1264]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via [ASRC](https://security.alibaba.com/)(Alibaba Security Response Center) where the issue will be triaged appropriately.**

- [x] I have searched the [issues](https://github.com/alibaba/higress/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
Encountering a 404 error when using a wildcard gateway in conjunction with ingress rules. It appears that the wildcard Gateway may be overriding specific non-wildcard ingress rules.

### Ⅱ. Describe what happened
When creating a gateway with the following configuration, I intermittently receive a 404 error when accessing specific routes defined by ingress resources.

If there is an exception, please attach the exception trace:

```
No trace for this behavior.
```

### Ⅲ. Describe what you expected to happen
I expected the wildcard gateway to coexist with the non-wildcard ingress rules without causing conflicts, allowing access to both wildcard and specific routes without resulting in 404 errors.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. Create a Gateway using the following YAML configuration:
   ```yaml
   apiVersion: networking.istio.io/v1beta1
   kind: Gateway
   metadata:
     name: test-gateway
     namespace: test-gateway
   spec:
     selector:
       higress: test-gateway
     servers:
       - hosts:
           - '*.example.com'
         port:
           name: https
           number: 444
           protocol: HTTPS
         tls:
           cipherSuites:
             - ECDHE-ECDSA-AES128-GCM-SHA256
             - ECDHE-RSA-AES128-GCM-SHA256
             - ECDHE-ECDSA-AES256-GCM-SHA384
             - ECDHE-RSA-AES256-GCM-SHA384
           credentialName: test-gateway-certificate
           minProtocolVersion: TLSV1_2
           mode: SIMPLE
   ```
2. Define a non-wildcard ingress rule for a specific host (e.g., `test.example.com`).
3. Attempt to access both the wildcard and non-wildcard routes and observe the 404 errors.
4. restart higress gateway pod every time when you change related to this gateway virtualservices or ingresses .

### Ⅴ. Anything else we need to know?
It would be beneficial to understand if there are any existing mechanisms to resolve priority issues between wildcard gateways and specific ingress rules automatically.

### Ⅵ. Environment:

- Higress version:  1.4.1
- OS: Cloud Provider deployed Linux k8s distro (Ubuntu)
- Others: works inside istio 1.19.3 mesh
