### ISSUE TITLE
关于认证插件的用户配置细化到路由上的建议

### ISSUE THREAD

**Issue by ilovedumplings** [alibaba/higress#1358]
## Why do you need it?
 Is your feature request related to a problem? Please describe in details
现在的只能在全局配置认证用户,然后在路由级别的插件上应用某些认证用户,这样其实不好实现多租户的概念,另外拿key-auth举例，我只能在全局配置配置用哪些key,我无法指定在路由指定使用哪个参数传入某个key,这样很不灵活
![image](https://github.com/user-attachments/assets/b56b7a1a-6c06-44cd-89ce-ccf6efe720f9)

## How could it be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by hanxiantao** [comment]
按照插件中提供的示例，每个路由添加一个 WasmPlugin 应该也可以实现，控制台的逻辑我没有了解过，但我理解插件层面目前是按照这种方式实现的，你可以按照这种方式先试下
```yaml
apiVersion: extensions.higress.io/v1alpha1
kind: WasmPlugin
metadata:
  name: wasm-keyauth-httpbin
  namespace: higress-system
spec:
  defaultConfig:
    consumers:
      - credential: 2bda943c-ba2b-11ec-ba07-00163e1250b5
        name: consumer1
      - credential: c8c8e9ca-558e-4a2d-bb62-e700dcc40e35
        name: consumer2
    global_auth: false
    keys:
      - x-api-key
      - apikey
    in_header: true
  defaultConfigDisable: false
  matchRules:
    - config:
        allow:
          - consumer1
      configDisable: false
      ingress:
        - ingress-keyauth-httpbin
  url: oci://docker.io/dongjiang1989/keyauth:1.0.0
  imagePullPolicy: Always
```
