### ISSUE TITLE
 使用 hgctl 部署历史版本，参数不生效

### ISSUE THREAD

**Issue by whitebear009** [alibaba/higress#1436]
### Ⅰ. Issue Description
我想使用 hgctl 在新集群上部署 higress 的历史版本，使用官网的以下参数不生效。
yaml配置如下:
```
profile: k8s
global:
  install: k8s
  ingressClass: nginx
  namespace: higress-system

higress-core:
  gateway:
    replicas: 3
    service:
      type: NodePort
  controller:
    replicas: 3

higress-console:
  replicasCount: 2
  service:
    type: NodePort

charts:
  higress:
    url: https://higress.io/helm-charts
    name: higress
    version: 1.4.2
```
安装命令为： 
`hgctl install -f higress-values.yaml`

### Ⅱ. Describe what happened
仍然部署了最新版本
```
[root@k8s-node-xiasha35 .hgctl]# hgctl install -f higress-values-txyun.yaml

Please select higress install configration profile:

1.Install higress to local kubernetes cluster like kind etc.

2.Install higress to kubernetes cluster

3.Install higress to local docker environment

Please input 1, 2 or 3 to select, input your selection:2

This will install Higress "k8s" profile into the cluster.
Proceed? (y/N)y


🧐 Validating Profile: "k8s"

⌛️ Detecting kubernetes version ... v1.20.6

⌛️ Detecting higress installed by helm or not...


📦 Running command: helm  list  -n  higress-system  -f  higress


NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART	APP VERSION

⚡️ Fetching Higress Helm Chart latest version "2.0.1"
🏄 Downloading Higress Helm Chart version: 2.0.1, url: https://higress.io/helm-charts
📦 Rendering Higress Helm Chart

⌛️ Processing installation...

✔️ Installed ClusterRole::higress-console-higress-system.
✔️ Installed ClusterRoleBinding::higress-console-higress-system.
✔️ Installed ConfigMap:higress-console:higress-system.
✔️ Installed Deployment:higress-console:higress-system.
```

- Higress version:  1.4.2
- K8s version : 1.20
- Others:
