### ISSUE TITLE
AI 缓存插件对接 TextIn https://www.textin.com/document/acge_text_embedding

### ISSUE THREAD

**Issue by CH3CHO** [alibaba/higress#1447]

**Comment by Chi-Kai** [comment]
认领这个任务

**Comment by Chi-Kai** [comment]
在测试中遇到了问题。我的docker-compose.yaml 如下:
```yaml
services:
  envoy:
    image: higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/gateway:v2.0.2
    entrypoint: /usr/local/bin/envoy
    # 注意这里对wasm开启了debug级别日志，正式部署时则默认info级别
    command: -c /etc/envoy/envoy.yaml --component-log-level wasm:debug
    networks:
    - wasmtest
    ports:
    - "10000:10000"
    volumes:
    - ./envoy.yaml:/etc/envoy/envoy.yaml
    - ./main.wasm:/etc/envoy/main.wasm # ai-cache
    - ../ai-proxy/ai.wasm:/etc/envoy/ai.wasm # ai-proxy
networks:
  wasmtest: {}
```
envoy.yaml如下:
```yaml
admin:
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                scheme_header_transformation:
                  scheme_to_overwrite: https
                stat_prefix: ingress_http
                # Output envoy logs to stdout
                access_log:
                  - name: envoy.access_loggers.stdout
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                # Modify as required
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: [ "*" ]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: deepseek
                            timeout: 300s
                http_filters:
                  - name: wasmtest
                    typed_config:
                      "@type": type.googleapis.com/udpa.type.v1.TypedStruct
                      type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
                      value:
                        config:
                          name: wasmtest
                          vm_config:
                            runtime: envoy.wasm.runtime.v8
                            code:
                              local:
                                filename: /etc/envoy/ai.wasm
                          configuration:
                            "@type": "type.googleapis.com/google.protobuf.StringValue"
                            value: |
                              {
                                "provider": {
                                  "type": "deepseek",
                                  "apiTokens": [
                                    "sk-d3a05cebda74496a82568828430d95b8"
                                  ]
                                }
                              }

                  - name: cache
                    typed_config:
                      "@type": type.googleapis.com/udpa.type.v1.TypedStruct
                      type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
                      value:
                        config:
                          name: cache
                          vm_config:
                            runtime: envoy.wasm.runtime.v8
                            code:
                              local:
                                filename: /etc/envoy/main.wasm
                          configuration:
                            "@type": "type.googleapis.com/google.protobuf.StringValue"
                            value: |
                              {
                                "embedding": {
                                  "type": "textin",
                                  "textinAppId": "1",
                                  "textinSecretCode": "1",
                                  "textinMatryoshkaDim": 1792
                                },
                                "vector": {
                                  "type": "dashvector",
                                  "serviceName": "test",
                                  "collectionID": "test1",
                                  "serviceHost": "1.dashvector.cn-zhangjiakou.aliyuncs.com",
                                  "apiKey": "1"
                                },
                                "cache": { # 不使用cache
                                  "serviceName": "",
                                  "type": ""
                                }
                              }
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
   - name: deepseek
     connect_timeout: 30s
     type: LOGICAL_DNS
     dns_lookup_family: V4_ONLY
     lb_policy: ROUND_ROBIN
     load_assignment:
       cluster_name: deepseek
       endpoints:
         - lb_endpoints:
             - endpoint:
                 address:
                   socket_address:
                     address: api.deepseek.com
                     port_value: 443
     transport_socket:
       name: envoy.transport_sockets.tls
       typed_config:
         "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
         "sni": "api.deepseek.com"
```
启动后Log:
![image](https://github.com/user-attachments/assets/659e3965-3707-4378-aeb6-2ed23f09f53b)
执行下面命令:
```
curl "http://localhost:10000/v1/chat/completions"  -H "Content-Type: application/json" -d '{
  "model": "deepseek-chat",            
  "messages": [                                                     
    {                        
      "role": "user",                
      "content": "你好，你是谁？"
    }                                                                                 
  ]                                                 
}'
```
长时间无响应。此时后台日志:
![image](https://github.com/user-attachments/assets/38b2fc3a-314e-49bc-9aa3-3fc9bcdeae6e)
是我配置有问题吗？

**Comment by CH3CHO** [comment]
这应该是个bug，就是在请求embedding或者vector失败的时候，请求卡住。请 @Suchun-sv 看一下。

不过这个问题是可以通过修改配置绕过去的。所有需要 envoy 请求的服务都需要配置和 service name 和端口相对应的 cluster。你可以改一下配置试试看。

**Comment by Chi-Kai** [comment]
应该不是cache的问题，我没有启用cache只用ai-proxy时也出现了这个问题。卡在这个地方:
![image](https://github.com/user-attachments/assets/a3ce87d6-071c-45b7-8eda-650169a41333)
具体问题还没搞明白。

**Comment by CH3CHO** [comment]
> 应该不是cache的问题，我没有启用cache只用ai-proxy时也出现了这个问题。卡在这个地方: ![image](https://private-user-images.githubusercontent.com/56287847/382700081-a3ce87d6-071c-45b7-8eda-650169a41333.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MTIzODAsIm5iZiI6MTczMDcxMjA4MCwicGF0aCI6Ii81NjI4Nzg0Ny8zODI3MDAwODEtYTNjZTg3ZDYtMDcxYy00NWI3LThlZGEtNjUwMTY5YTQxMzMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDA5MjEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkYjczYjEyOWM2N2VmODk0Yzk5ODZjNmE5MmI0MDk2NGY5OTZmZTYzZDExN2ExNTBhNzgzMjQ4OWE4YTRkZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vNflpENt3o22PphfDR9Y3mCuRa8gIl22JAspb9LNotU) 具体问题还没搞明白。

这个地方没有问题的。能贴一下你的测试请求吗，包括header和body，完整的

**Comment by Chi-Kai** [comment]
就是这个呢
```
curl "http://localhost:10000/v1/chat/completions" -H "Content-Type: application/json" -d '{ "model": "deepseek-chat", "messages": [ { "role": "user", "content": "你好，你是谁？" } ] }'
```

**Comment by CH3CHO** [comment]
那感觉不太合理。要不你把后端的deepseek服务换成一个httpecho，看看请求有没有发出去吧

**Comment by Chi-Kai** [comment]
老师你好。我经过查看echo是可以正常接收的。但是ai服务还是不能接收。不知道问题出在哪里，或者可以从哪方面排查？
docker-compose.yaml
```yaml
  envoy:
    image: higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/gateway:v2.0.2
    entrypoint: /usr/local/bin/envoy
    command: -c /etc/envoy/envoy.yaml --component-log-level wasm:debug
    networks:
    - wasmtest
    ports:
    - "10000:10000"
    volumes:
    - ./envoy.yaml:/etc/envoy/envoy.yaml
    - ./main.wasm:/etc/envoy/main.wasm # ai-cache
    - ../ai-proxy/ai.wasm:/etc/envoy/ai.wasm # ai-proxy

  echo:
    image: higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/http-echo:0.2.4-alpine
    networks:
    - wasmtest
    command:
    - "-text=hello from echo server"

networks:
  wasmtest: {}
```
envoy.yaml:
```yaml
admin:
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                scheme_header_transformation:
                  scheme_to_overwrite: https
                stat_prefix: ingress_http
                # Output envoy logs to stdout
                access_log:
                  - name: envoy.access_loggers.stdout
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                # Modify as required
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: [ "*" ]
                      routes:
                        - match:
                            prefix: "/ai"
                          route:
                            cluster: yi
                            timeout: 300s
                        - match:
                            prefix: "/echo"
                          route:
                            cluster: echo
                            timeout: 300s
                http_filters:
                  - name: wasmtest
                    typed_config:
                      "@type": type.googleapis.com/udpa.type.v1.TypedStruct
                      type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
                      value:
                        config:
                          name: wasmtest
                          vm_config:
                            runtime: envoy.wasm.runtime.v8
                            code:
                              local:
                                filename: /etc/envoy/ai.wasm
                          configuration:
                            "@type": "type.googleapis.com/google.protobuf.StringValue"
                            value: |
                              {
                                "provider": {
                                  "type": "yi",
                                  "apiTokens": [
                                    "5*********"
                                  ]
                                }
                              }
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:

    - name: yi
      connect_timeout: 30s
      type: LOGICAL_DNS
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: yi
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: api.lingyiwanwu.com
                      port_value: 443
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          "sni": "api.lingyiwanwu.com"
    
    - name: echo    # 新增echo集群配置
      connect_timeout: 30s
      type: LOGICAL_DNS
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: echo
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: echo    # 使用服务名称
                      port_value: 5678 # http-echo默认
```
请求命令:
```
curl "http://localhost:10000/ai/v1/chat/completions"  -H "Content-Type: application/json" -d '{
  "model": "yi-large",            
  "messages": [                                                     
    {                        
      "role": "user",                
      "content": "你好，你是谁？"
    }                                                                                 
  ]                                                 
}'
```
截图:
![image](https://github.com/user-attachments/assets/cb7a99fa-d7d7-4f71-a3a2-27e1ea3bef3a)
而直接用curl请求api是可以的。
