### ISSUE TITLE
如何配置合并请求路径中的斜杠`/`

### ISSUE THREAD

**Issue by johnlanni** [alibaba/higress#1481]
### Discussed in https://github.com/alibaba/higress/discussions/1479

<div type='discussions-op-text'>

<sup>Originally posted by **chenvista** November  6, 2024</sup>
之前使用nginx ingress 如https://open.xxx.com//mall/v1  多了个/  是可以的，现在迁移到higress后发现不行。因为这个给第三方调用的，第三方配置错了，协调比较麻烦，higress可以支持这种吗</div>

**Comment by johnlanni** [comment]
下面配置的作用是对于请求环节，合并请求中多余的‘/’, 开启后www.a.com//b多余的'/'会被合并，将会同www.a.com/b一致 ：

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: merge-slash
  namespace: higress-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        name: envoy.filters.network.http_connection_manager
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          merge_slashes: true
```
