### ISSUE TITLE
higress 配置4层代理，如何设置负载均衡策略为最小连接数

### ISSUE THREAD

**Issue by vvhuang-ll** [alibaba/higress#1573]

**Comment by johnlanni** [comment]
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: tcp-least-conn-lb
  namespace: higress-system # Higress Gateway所在的命名空间
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      context: GATEWAY
      cluster:
        # 这里就是服务列表里展示的服务名（不带端口）
        service: my-ip.static
    patch:
      operation: MERGE
      value:
        lb_policy: LEAST_REQUEST
```

**Comment by vvhuang-ll** [comment]
应用上面的配置后，在gateway容器里面查看envoy-rev.json配置，没看到有添加的配置信息。如何确认配置是否生效
```
grep "tcp-least-conn-lb" envoy-rev.json 
istio-proxy@higress-gateway-5cd9bd4cd5-ppmth:/etc/istio/proxy$ grep "lb_policy" envoy-rev.json 
        "lb_policy": "ROUND_ROBIN",
        "lb_policy": "ROUND_ROBIN",
        "lb_policy": "ROUND_ROBIN",
        "lb_policy": "ROUND_ROBIN",
```

**Comment by johnlanni** [comment]
@vvhuang-ll 配置里的服务名换成你自己的了吗？

**Comment by vvhuang-ll** [comment]
@johnlanni 是的
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: tcp-least-conn-lb
  namespace: higress-system # Higress Gateway所在的命名空间
spec:
  workloadSelector:
    labels:
      app: higress-gateway # 替换为实际的Higress Gateway工作负载标签
  configPatches:
  - applyTo: CLUSTER
    match:
      context: GATEWAY
      cluster:
        service: logstash-producer-logstash.app.svc.cluster.local 
      operation: MERGE
      value:
        lb_policy: LEAST_REQUEST
```
