### ISSUE TITLE
higress创建4层负载均衡如何配置max_connection_duration参数

### ISSUE THREAD

**Issue by vvlisn** [alibaba/higress#1577]
## higress创建4层负载均衡如何配置max_connection_duration参数
使用下面的配置不生效
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: tcp-least-conn-lb
  namespace: higress-system 
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      context: GATEWAY
      cluster:
        service: logstash-producer-logstash.app.svc.cluster.local
    patch:
      operation: MERGE
      value:
        lb_policy: LEAST_REQUEST
        max_connection_duration: 3600s
```
