### ISSUE TITLE
创建的服务来源里有多个IP或者多个域名，会做负载均衡吗

### ISSUE THREAD

**Issue by w7team** [alibaba/higress#1579]
```
  registries:
  - domain: "1.1.1.1:80,2.2.2.2:80"
    name: test
    port: 80
    type: static
  - domain: a.com,b.com,c.com
    name: registries-uiarciju
    port: 80
    type: dns
```

比如这种，会真多domain的多个值做均衡吗？我看官方的UI也可以填写多行，对这一块有疑问
