### ISSUE TITLE
higress支持ssl-passthrough么

### ISSUE THREAD

**Issue by jidalong** [alibaba/higress#1596]
想通过kubeconfig实现在外部访问集群；如何实现类似SSL透传特性（nginx.ingress.kubernetes.io/ssl-passthrough: "true"）解决证书认证问题。

**Comment by johnlanni** [comment]
ingress API 目前还没有支持这个注解，你可以试一下 Gateway API：
https://gateway-api.sigs.k8s.io/guides/tls/

**Comment by johnlanni** [comment]
欢迎认领这个issue，实现 ingress api 上的支持，参考转换的 istio gateway:

```yaml
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: mygateway
  namespace: higress-system
spec:
  selector:
    higress: higress-system-higress-gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH # 启用 TLS 透传
    hosts:
    - "*.example.com"

```
