### ISSUE TITLE
Implement annotation to support case-insensitive path matching

### ISSUE THREAD

**Issue by johnlanni** [alibaba/higress#163]
## How could it be?
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    higress.io/ignore-path-case: "true"
  name: foo
spec:
  ingressClassName: higress  
  rules:
  - http:
      paths:
      - pathType: Exact
        path: "/abc"
...
```

## Other related information
[1. Annotation example](https://github.com/alibaba/higress/blob/main/pkg/ingress/kube/annotations/cors.go)
[2. Istio api conversion](https://github.com/alibaba/higress/blob/main/pkg/ingress/config/ingress_config.go#L331)
[3. Istio VitrualService's MatchRequest api](https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPMatchRequest)
