### ISSUE TITLE
higress envoy默认会重新生成x-request-id，请问higress中怎么关闭generate_request_id配置

### ISSUE THREAD

**Issue by heartbeat2013** [alibaba/higress#1655]
线上服务跟x-request-id有关联，客户端请求中带的x-request-id会被envoy重新生成的x-request-id覆盖掉，请教下怎么关闭该功能

**Comment by johnlanni** [comment]
可以使用下面这个配置：
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name:  disable-request-generate
  namespace: higress-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        name: envoy.filters.network.http_connection_manager
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          generate_request_id: false
```
