### ISSUE TITLE
【外部认证】插件是否能支持响应body 及 例外路径(不需要认证)

### ISSUE THREAD

**Issue by takenToken** [alibaba/higress#1691]
# 外部认证配置：
```yaml
http_service:
  authorization_request:
    allowed_headers:
    - exact: "token"
    headers_to_add:
      x-envoy-header: true
  authorization_response:
    allowed_upstream_headers:
    - exact: "x-auth-status"
    - exact: "x-auth-msg"
  endpoint:
    path_prefix: "/auth"
    service_name: "tenant-lesoon-basic-api.tenant-dev.svc.cluster.local"
    service_port: 8080
  endpoint_mode: "envoy"
  timeout: 1000
status_on_error: 403
```

# 测试结果：
<img width="1885" alt="Image" src="https://github.com/user-attachments/assets/ba4272b2-9695-4104-8d8a-439d318a6f75" />

* 类似于ASM的服务网格网关自定义授权逻辑。

# 疑问
* 响应无body，无法做到更精细化处理。  例如： 资源权限认证、 单点登录认证等。 
* 如何配置例外路径， 例如：前端路径、特殊业务路径不需要认证的，如何针对这边路径配置例外？ 如果这边路径也要走到外部授权认证一遍的话，浪费资源了。

**Comment by hanxiantao** [comment]
问题1：目前版本的代码实现是在认证失败的时候（认证服务返回非200）响应认证服务返回的 response_code 和 response_body，不确定插件是否更新为最新版本，我这边会自己再验证下。如果未更新会打个新的 ext-auth 插件版本更新下即可

问题2：这个目前版本暂不支持，我们这边使用认证的时候一般会把认证和非认证的路径进行区分，当然也可以加一个类似 `skippedPathPrefixes` 配置排除特定路径不走认证 这个可以帮忙一起评估下 @johnlanni。如果需要的话，我这边开发下

**Comment by johnlanni** [comment]
@hanxiantao 例外路径确实是个挺通用的功能，可以实现一下

**Comment by takenToken** [comment]
@hanxiantao  您好，请问一下这两个功能大概什么时候回合并上，并插件编译到中央仓库，我这边好验证一下结果是否符合预期，谢谢。 

<img width="668" alt="Image" src="https://github.com/user-attachments/assets/bbb03c45-13e1-4614-adaa-fc4fe1186bf1" />

**Comment by hanxiantao** [comment]
@takenToken 新的插件已经更新了，今天验证下吧 higress-registry.cn-hangzhou.cr.aliyuncs.com/plugins/ext-auth:latest

**Comment by takenToken** [comment]
@hanxiantao  您好， 请问一下【oci://higress-registry.cn-hangzhou.cr.aliyuncs.com/plugins/ext-auth:latest】具体版本是多少，多久会自动拉取最新版本。  我现在验证了白名单没有生效， 请问一下是什么情况。 

配置
```yml
http_service:
  authorization_request:
    allowed_headers:
    - exact: "token"
    headers_to_add:
      x-envoy-header: true
  authorization_response:
    allowed_upstream_headers:
    - exact: "x-auth-status"
    - exact: "x-auth-msg"
  endpoint:
    path_prefix: "/auth"
    service_name: "tenant-lesoon-basic-api.tenant-dev.svc.cluster.local"
    service_port: 8080
  endpoint_mode: "envoy"
  match_list:
  - match_rule_path: "/login"
    match_rule_type: "prefix"
  match_type: "blacklist"
  timeout: 3000
status_on_error: 403
```

<img width="1892" alt="Image" src="https://github.com/user-attachments/assets/373de08d-e53d-403d-b2e7-722725eb13f2" />


<img width="1454" alt="Image" src="https://github.com/user-attachments/assets/49741c22-5be4-44bc-8127-605aca494f98" />

**Comment by hanxiantao** [comment]
> [@hanxiantao](https://github.com/hanxiantao) 您好， 请问一下【oci://higress-registry.cn-hangzhou.cr.aliyuncs.com/plugins/ext-auth:latest】具体版本是多少，多久会自动拉取最新版本。 我现在验证了白名单没有生效， 请问一下是什么情况。
> 
> 配置
> 
> http_service:
>   authorization_request:
>     allowed_headers:
>     - exact: "token"
>     headers_to_add:
>       x-envoy-header: true
>   authorization_response:
>     allowed_upstream_headers:
>     - exact: "x-auth-status"
>     - exact: "x-auth-msg"
>   endpoint:
>     path_prefix: "/auth"
>     service_name: "tenant-lesoon-basic-api.tenant-dev.svc.cluster.local"
>     service_port: 8080
>   endpoint_mode: "envoy"
>   match_list:
>   - match_rule_path: "/login"
>     match_rule_type: "prefix"
>   match_type: "blacklist"
>   timeout: 3000
> status_on_error: 403
> <img alt="Image" width="1892" src="https://private-user-images.githubusercontent.com/5975626/405856925-373de08d-e53d-403d-b2e7-722725eb13f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc1OTgzODksIm5iZiI6MTczNzU5ODA4OSwicGF0aCI6Ii81OTc1NjI2LzQwNTg1NjkyNS0zNzNkZTA4ZC1lNTNkLTQwM2QtYjJlNy03MjI3MjVlYjEzZjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMjNUMDIwODA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzM0NjQ2YTNhYTMwZjVkNTRjZTg5NmFjY2VkNWRlMGNiYzczODk3YjUyMWQzNGY0MTg4MzBlMjBjMzJkYzI4ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.wsf2ktJd_FZlLQ3D_Uzh3wJdDxpjBjmWd_-5TXxD7x8"> <img alt="Image" width="1454" src="https://private-user-images.githubusercontent.com/5975626/405858854-49741c22-5be4-44bc-8127-605aca494f98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc1OTgzODksIm5iZiI6MTczNzU5ODA4OSwicGF0aCI6Ii81OTc1NjI2LzQwNTg1ODg1NC00OTc0MWMyMi01YmU0LTQ0YmMtODEyNy02MDVhY2E0OTRmOTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMjNUMDIwODA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yzc0MmM0OGE0YWI5MmJjN2I3ZDkzODU4NDI1ZGZlNjQyODBkNTA3YzhlMjY5MWY5ZjRkN2Q3YWY1ZDI5MzE0MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ttxcbgwifPRi6KA4POZ4a8vG-xN1QmEU1lZdmEPgOPk">

白名单是跳过认证，改成白名单试下

![Image](https://github.com/user-attachments/assets/986f1f7a-0450-4105-bc56-f3c56d17d3ad)

**Comment by takenToken** [comment]
@hanxiantao  刚发现这个问题， 改成白名单效果一样。 

```yml
http_service:
  authorization_request:
    allowed_headers:
    - exact: "token"
    headers_to_add:
      x-envoy-header: true
  authorization_response:
    allowed_upstream_headers:
    - exact: "x-auth-status"
    - exact: "x-auth-msg"
  endpoint:
    path_prefix: "/auth"
    service_name: "tenant-lesoon-basic-api.tenant-dev.svc.cluster.local"
    service_port: 8080
  endpoint_mode: "envoy"
  match_list:
  - match_rule_path: "/login"
    match_rule_type: "prefix"
  match_type: "whitelist"
  timeout: 3000
status_on_error: 403
```

**Comment by hanxiantao** [comment]
> [@hanxiantao](https://github.com/hanxiantao) 刚发现这个问题， 改成白名单效果一样。
> 
> http_service:
>   authorization_request:
>     allowed_headers:
>     - exact: "token"
>     headers_to_add:
>       x-envoy-header: true
>   authorization_response:
>     allowed_upstream_headers:
>     - exact: "x-auth-status"
>     - exact: "x-auth-msg"
>   endpoint:
>     path_prefix: "/auth"
>     service_name: "tenant-lesoon-basic-api.tenant-dev.svc.cluster.local"
>     service_port: 8080
>   endpoint_mode: "envoy"
>   match_list:
>   - match_rule_path: "/login"
>     match_rule_type: "prefix"
>   match_type: "whitelist"
>   timeout: 3000
> status_on_error: 403

这里拉取测试改下，改成 imagePullPolicy: Always 试下，我改成最新的试过是可以的，估计是没有更新，默认是 imagePullPolicy: IfNotPresent

**Comment by hanxiantao** [comment]
@takenToken 因为发现了个问题，等 #1705 合并后我们再发下正式版本

**Comment by takenToken** [comment]
@hanxiantao   是不是如下调整。  请问对higress版本有要求吗？  我现在使用是2.0.4 ，控制台1.4.6 。     latest版本在哪里可以查看具体版本。 


以下调整效果一样， 403 
```yml
http_service:
  authorization_request:
    allowed_headers:
    - exact: "token"
    headers_to_add:
      x-envoy-header: true
  authorization_response:
    allowed_upstream_headers:
    - exact: "x-auth-status"
    - exact: "x-auth-msg"
  endpoint:
    path_prefix: "/auth"
    service_name: "tenant-lesoon-basic-api.tenant-dev.svc.cluster.local"
    service_port: 8080
  endpoint_mode: "envoy"
  match_list:
  - match_rule_path: "/login"
    match_rule_type: "prefix"
  match_type: "whitelist"
  timeout: 3000
imagePullPolicy: "Always"
status_on_error: 403
```
