### ISSUE TITLE
transformer 插件能否支持将请求头写入到响应头上？

### ISSUE THREAD

**Issue by monchcc** [alibaba/higress#1701]
## 问题描述

 transformer 插件能否支持将请求头写入到响应头上？
 
 目前在transformer的文档上并没有说明，另外看了代码好像暂时不支持这种功能。

## 应用场景

 想要将otel的traceID，写入到响应头上，方便开发人员能够通过traceID去快速的查询关联日志；

从`onHttpRequestHeaders` 中获取traceID的请求头，存入ctx，再在`onHttpResponseHeaders`写入到相应头中。

**Comment by johnlanni** [comment]
通过header控制策略就可以，添加一个响应头，value填：%REQ(OT-TRACEID)%

**Comment by monchcc** [comment]
> 通过header控制策略就可以，添加一个响应头，value填：%REQ(OT-TRACEID)%


我这么配置，相应头中就增加了字符串 `x-trace-id: %REQ(OT-TRACEID)%`;
能补充下文档示例吗？
```
respRules:
  - operate: add
    headers:
      - key: x-trace-id
        value: "%REQ(OT-TRACEID)%"
```
