### ISSUE TITLE
多模型降级配置中遇到的问题：根据模型路由不生效

### ISSUE THREAD

**Issue by chenbo90** [alibaba/higress#1744]
## Why do you need it?
 Is your feature request related to a problem? Please describe in details

## How could it be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

## Other related information

我使用aio镜像（2.0.6）部署了higress,想测试验证下降级配置。配置了两个ai路由，一个路由到deepseek,一个路由到moonshoot。路由是根据model进行区分的，但是我使用curl命令发现调用的一直都是deepseek。想请大佬帮排查下，下面是我的配置截图：
1:创建AI服务提供者 deepseek和moonshoot

<img width="1389" alt="Image" src="https://github.com/user-attachments/assets/875fc97e-1e0e-4f53-b756-63ca17f7a1c1" />
2:创建AI路由

<img width="1410" alt="Image" src="https://github.com/user-attachments/assets/74508b72-fe7d-4087-b92a-bc64459c0b08" />
下面是ds的详细配置截图

<img width="1451" alt="Image" src="https://github.com/user-attachments/assets/d8fe2ae0-4436-45fd-953f-7c3737993998" />
下面是moonshoot的配置截图

<img width="1454" alt="Image" src="https://github.com/user-attachments/assets/d6810c3e-5a2e-48f4-8e12-0f892eef3742" />
3:参考使用方法中的curl命令

<img width="792" alt="Image" src="https://github.com/user-attachments/assets/37c7e64d-1360-4179-bc6b-d0c3a95b7340" />
分别指定不同的模型去访问后端的服务。

<img width="1511" alt="Image" src="https://github.com/user-attachments/assets/bede7763-7348-48e4-b260-5f13b6f842b1" />
按理来说：model为：deepseek-chat访问的是deepseek服务，model为gpt-3访问的是moonshoot（这个也待定，不确定，但是之前使用ai代理插件的时候配置的是gpt-3是可以的），结果显示，最终访问的都是deepseek。这个model值是怎么和ai服务提供者对应起来的？是我的model写的不对么？怎么改？麻烦回答下，谢谢。

**Comment by chenbo90** [comment]
抱歉，我找到原因了，配置的时候选择【按比例】或者【按模型名称】，我应该配置按模型名称。抱歉，这个问题解决了。但是还有一个问题就是，如果配置了降级，这个怎么测试验证？比如deepseek的路由配置降级成moonshoot，听开发说目前支持4XX和5XX触发降级，我将ds的apitoken配置错误，想触发降级，但是直接报鉴权失败。这个怎么触发降级呢？有什么好办法么？还望指教

**Comment by CH3CHO** [comment]
> 抱歉，我找到原因了，配置的时候选择【按比例】或者【按模型名称】，我应该配置按模型名称。抱歉，这个问题解决了。但是还有一个问题就是，如果配置了降级，这个怎么测试验证？比如deepseek的路由配置降级成moonshoot，听开发说目前支持4XX和5XX触发降级，我将ds的apitoken配置错误，想触发降级，但是直接报鉴权失败。这个怎么触发降级呢？有什么好办法么？还望指教

要看一下DS返回的状态码是4xx吗？

**Comment by chenbo90** [comment]
> > 抱歉，我找到原因了，配置的时候选择【按比例】或者【按模型名称】，我应该配置按模型名称。抱歉，这个问题解决了。但是还有一个问题就是，如果配置了降级，这个怎么测试验证？比如deepseek的路由配置降级成moonshoot，听开发说目前支持4XX和5XX触发降级，我将ds的apitoken配置错误，想触发降级，但是直接报鉴权失败。这个怎么触发降级呢？有什么好办法么？还望指教
> 
> 要看一下DS返回的状态码是4xx吗？

<img width="1226" alt="Image" src="https://github.com/user-attachments/assets/2486d612-d91c-4101-89fe-172826b6141a" />嗯，是401，授权错误。我是把deepseek的凭证故意写错，想制造出4XX的故障，让他降级。结果看没降级成功。您看是这么配置么？还有，想问下，这个降级的代码在哪能看到？是在插件里还是在控制台

**Comment by CH3CHO** [comment]
> 嗯，是401，授权错误。我是把deepseek的凭证故意写错，想制造出4XX的故障，让他降级。结果看没降级成功。您看是这么配置么？还有，想问下，这个降级的代码在哪能看到？是在插件里还是在控制台

我先本地试一下看看。

**Comment by chenbo90** [comment]
> > 嗯，是401，授权错误。我是把deepseek的凭证故意写错，想制造出4XX的故障，让他降级。结果看没降级成功。您看是这么配置么？还有，想问下，这个降级的代码在哪能看到？是在插件里还是在控制台
> 
> 我先本地试一下看看。

好的，现在是否有结论？我看最终是生成一个Envoyfilter，里面是4xx和5xx。

**Comment by CH3CHO** [comment]
> 好的，现在是否有结论？我看最终是生成一个Envoyfilter，里面是4xx和5xx。

我本地测了是可以降级的，你看一下 higress-system 下面都有哪些 ingress，把配置贴一下。

**Comment by chenbo90** [comment]
> > 好的，现在是否有结论？我看最终是生成一个Envoyfilter，里面是4xx和5xx。
> 
> 我本地测了是可以降级的，你看一下 higress-system 下面都有哪些 ingress，把配置贴一下。

我控制台配置了两个AI路由，因为我用的是AIO方式进行部署的，配置都是文件，我从后台看AI路由相关的ingress有三个：

<img width="623" alt="Image" src="https://github.com/user-attachments/assets/5537ffc1-bf63-4c96-8784-c1386fe1eb3b" />
ai-route-deepseek-ai-router.internal.yaml配置内容如下：
annotations:
  higress.io/destination: llm-deepseek-pro.internal.dns:443
  higress.io/exact-match-header-x-higress-llm-model: deepseek-chat
  higress.io/ignore-path-case: "false"
labels:
  higress.io/domain_higress-default-domain: "true"
  higress.io/internal: "true"
  higress.io/resource-definer: higress
rules:
- http:
    paths:
    - backend:
        resource:
          apiGroup: networking.higress.io
          kind: McpBridge
          name: default
      path: /
      pathType: Prefix

ai-route-deepseek-ai-router.fallback.internal.yaml内容如下：
annotations:
  higress.io/destination: llm-moonshot-pro.internal.dns:443
  higress.io/exact-match-header-x-higress-fallback-from: ai-route-deepseek-ai-router.internal
  higress.io/exact-match-header-x-higress-llm-model: deepseek-chat
  higress.io/ignore-path-case: "false"
labels:
  higress.io/domain_higress-default-domain: "true"
  higress.io/internal: "true"
  higress.io/resource-definer: higress
rules:
- http:
    paths:
    - backend:
        resource:
          apiGroup: networking.higress.io
          kind: McpBridge
          name: default
      path: /
      pathType: Prefix

ai-route-moonshot-ai-router.internal.yaml内容如下：
annotations:
  higress.io/destination: llm-moonshot-pro.internal.dns:443
  higress.io/exact-match-header-x-higress-llm-model: moonshot-v1-8k
  higress.io/ignore-path-case: "false"
labels:
  higress.io/domain_higress-default-domain: "true"
  higress.io/internal: "true"
  higress.io/resource-definer: higress
rules:
- http:
    paths:
    - backend:
        resource:
          apiGroup: networking.higress.io
          kind: McpBridge
          name: default
      path: /
      pathType: Prefix。
从控制台看就是：

<img width="1162" alt="Image" src="https://github.com/user-attachments/assets/3161c3a0-6a8c-4f74-a1bf-30c4a731eb26" />

<img width="1224" alt="Image" src="https://github.com/user-attachments/assets/6e6b7bc3-6446-48a8-b6ee-582504c196be" />

理想状态下是我curl model为deepseek-chat的模型的时候，由于我把apitoken配置错了，发生401错误，会自动调用moonshot-v1-8k的模型上。是不是可以这么理解，但是现实是没有这个结果出现。

**Comment by CH3CHO** [comment]
上面的格式用 Markdown 的代码块包装一下吧。

你的描述是对的。

fallback 那个 ingress 的内容也贴一下。还有 higress-config 这个 ConfigMap 的内容。

**Comment by chenbo90** [comment]
> > 上面的格式用 Markdown 的代码块包装一下吧。

> 
> 你的描述是对的。
> 
> fallback 那个 ingress 的内容也贴一下。还有 higress-config 这个 ConfigMap 的内容。

ai-route-deepseek-ai-router.fallback.internal.yaml配置如下：

```
annotations:
  higress.io/destination: llm-moonshot-pro.internal.dns:443
  higress.io/exact-match-header-x-higress-fallback-from: ai-route-deepseek-ai-router.internal
  higress.io/exact-match-header-x-higress-llm-model: deepseek-chat
  higress.io/ignore-path-case: "false"
labels:
  higress.io/domain_higress-default-domain: "true"
  higress.io/internal: "true"
  higress.io/resource-definer: higress
rules:
- http:
    paths:
    - backend:
        resource:
          apiGroup: networking.higress.io
          kind: McpBridge
          name: default
      path: /
      pathType: Prefix
```

ai-route-deepseek-ai-router.internal.yaml配置如下：
```
annotations:
  higress.io/destination: llm-deepseek-pro.internal.dns:443
  higress.io/exact-match-header-x-higress-llm-model: deepseek-chat
  higress.io/ignore-path-case: "false"
labels:
  higress.io/domain_higress-default-domain: "true"
  higress.io/internal: "true"
  higress.io/resource-definer: higress
rules:
- http:
    paths:
    - backend:
        resource:
          apiGroup: networking.higress.io
          kind: McpBridge
          name: default
      path: /
      pathType: Prefix
```
ai-route-moonshot-ai-router.internal.yaml配置如下：
```
annotations:
  higress.io/destination: llm-moonshot-pro.internal.dns:443
  higress.io/exact-match-header-x-higress-llm-model: moonshot-v1-8k
  higress.io/ignore-path-case: "false"
labels:
  higress.io/domain_higress-default-domain: "true"
  higress.io/internal: "true"
  higress.io/resource-definer: higress
rules:
- http:
    paths:
    - backend:
        resource:
          apiGroup: networking.higress.io
          kind: McpBridge
          name: default
      path: /
      pathType: Prefix
```
higress-config.yaml配置如下：
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: higress-config
  namespace: higress-system
  creationTimestamp: "2000-01-01T00:00:00Z"
  resourceVersion: "1"
data:
  higress: |-
    downstream:
      connectionBufferLimits: 32768
      http2:
        initialConnectionWindowSize: 1048576
        initialStreamWindowSize: 65535
        maxConcurrentStreams: 100
      idleTimeout: 180
      maxRequestHeadersKb: 60
      routeTimeout: 0
    upstream:
      connectionBufferLimits: 10485760
      idleTimeout: 10% 
```
嗯，好的。你看还有看哪些配置，需要的话，我再贴一下。
