### ISSUE TITLE
Fail to apply the basic auth in plugin and route rules

### ISSUE THREAD

**Issue by heartshare** [alibaba/higress#1753]
![Image](https://github.com/user-attachments/assets/a688f90b-5ef2-4164-a8db-75afdd18693b)

https://www.bilibili.com/video/BV1qMvMeAEJy/?spm_id_from=333.337.search-card.all.click  the video can show up the login box

Tested in docker and docker-compose standalone packages
Diff browsers no pop up the login box too

**Comment by CH3CHO** [comment]
Please try the following config:

```yaml
global_auth: true
consumers:
- name: admin
  credential: admin:admin
```
