### ISSUE TITLE
开启AI提示词插件后，日志没有打印出追加的prompt内容

### ISSUE THREAD

**Issue by yumc2573** [alibaba/higress#1764]
## Why do you need it?
 Is your feature request related to a problem? Please describe in details

## How could it be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by johnlanni** [comment]
AI观测插件，默认只打印最后一个消息的，可以自己修改AI观测插件的配置，来打印完整消息，可以参考文档：
https://higress.cn/docs/latest/plugins/ai/api-o11y/ai-statistics/?spm=36971b57.2ef5001f.0.0.2a932c1fxxwpP3#%E8%AE%B0%E5%BD%95%E9%97%AE%E9%A2%98%E4%B8%8E%E5%9B%9E%E7%AD%94

```yaml
  - key: question # 记录问题
    value_source: request_body
    value: messages.@reverse.0.content
    apply_to_log: true
```

具体是这个配置，这里的 `messages.@reverse.0.content` 是基于 GJSON 的表达式，可以参考 GJSON 文档：https://github.com/tidwall/gjson/blob/master/SYNTAX.md?spm=36971b57.2ef5001f.0.0.2a932c1fxxwpP3&file=SYNTAX.md

例如，如果希望将所有 role 为 user 的 content 拼成一个数组作为 key，可以写成：messages.@reverse.#(role=="user")#.content

可以用这个工具测试：https://gjson.dev/?spm=36971b57.2ef5001f.0.0.2a932c1fxxwpP3
