### ISSUE TITLE
mcpbridge 必须注册名字为 default 否则 gateway cluster 信息里会找不到

### ISSUE THREAD

**Issue by Colstuwjx** [alibaba/higress#1839]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via [ASRC](https://security.alibaba.com/)(Alibaba Security Response Center) where the issue will be triaged appropriately.**

- [x] I have searched the [issues](https://github.com/alibaba/higress/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

如题，如果配置一个 mcpbridge 为：

```
apiVersion: networking.higress.io/v1
kind: McpBridge
metadata:
  name: google
  namespace: higress-system
spec:
  registries:
  - domain: www.google.com
    name: google
    type: dns
    port: 443
```

会发现 gateway 无法识别该信息，curl cluster 也会发现拿不到：

```
istio-proxy@higress-gateway-775dff6898-df764:/$ curl http://localhost:15000/clusters|grep google
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12871    0 12871    0     0  17.2M      0 --:--:-- --:--:-- --:--:-- 12.2M
```

后续如果配置了 ingress 请求的话也会报错 cluster not found

### Ⅲ. Describe what you expected to happen

希望不会限定只允许 default 名字的 mcpbridge

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. 建一个非 default 名字的 mcpbridge
2. 在 gateway pod 里发送测试 curl 

### Ⅵ. Environment:

- Higress version:  2.0.7
- OS : macOS Kind
- Others:
