### ISSUE TITLE
关于 ai-proxy 插件的使用

### ISSUE THREAD

**Issue by huhaiqwer** [alibaba/higress#1860]
问题现象：

第一次使用 `ai-proxy`  摸得还不是很熟，希望大佬帮忙解答下。
开启 `ai-proxy` 插件后，请求 模型服务会报错

## curl 请求报错如下（这个状态码与服务无关）

![Image](https://github.com/user-attachments/assets/a1507f3b-bcc5-4101-8086-4a20dd3b1ed3)
## higress 报错如下 

![Image](https://github.com/user-attachments/assets/9c85c60b-1b75-4337-925a-30130a0a4773)

`ai-proxy` 插件配置如下：

![Image](https://github.com/user-attachments/assets/618add5d-211a-44ca-bf83-e2646fc00394)

未开启 `ai-proxy` 插件时，可以正常请求

![Image](https://github.com/user-attachments/assets/1163e6d8-b7d1-4167-b351-66b585d4883c)

**Comment by huhaiqwer** [comment]
> 如果你的原始 model 和实际请求的 model 一样，可以不用配 modelMapping，只配 apiToken 和 type 即可。 从错误日志上看好像和 ai-statistics 插件有关，你是用 all-in-one 模式部署的吗？ 可以先把 ai-statistics 插件禁用试试。

是用all-in-one模式部署的
尝试过关闭 `ai-statistics` 插件, curl 网关的时候，还是会报错，http sttaus 不是 200  且 higress-gateway 没日志输出


开启 `ai-statustic` 之后，日志会有输出， 这里 报错 `Get model failed` ，意识是找不到模型吗？请问老师有什么思路，还有 这个 modelMapping 我不知道如何使用，我们的实际场景都是 模型的私有化部署，然后通过 `higress` 进行鉴权，和token的管理。我们正常时候 curl 请求带的 `model` 名称跟模型实际名称是一直的。可以请老师解答以下吗，官网的解释我不是很理解

![Image](https://github.com/user-attachments/assets/02043274-628d-4885-90e3-790057df9b31)

**Comment by huhaiqwer** [comment]
接上文，参考 官网 `ai-proxy 在 k8s 上的使用` 
`ingress` 配置如下：

**Comment by huhaiqwer** [comment]
接上文，参考 官网 ai-proxy 在 k8s 上的使用
ingress 配置如下：

**Comment by huhaiqwer** [comment]
接上文，参考 官网 ai-proxy 在 k8s 上的使用
ingress 配置如下：

**Comment by huhaiqwer** [comment]
接上文，参考 官网 ai-proxy 在 k8s 上的使用，现在发现配置之后 `higress-gateway` 直接报错。麻烦老师帮忙解惑下~
新建服务来源 `ai-proxy-test`、配置如下：

![Image](https://github.com/user-attachments/assets/bde68693-9d83-44b8-9ac9-5a2a8a7155e0)

新建 ingress `ai-proxy-test-r`,配置如下：
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    higress.io/destination: ai-proxy-test.static
    higress.io/ignore-path-case: "true"
  creationTimestamp: "2025-03-08T08:40:26Z"
  generation: 1
  labels:
    higress.io/domain_ai.proxy.test.com: "true"
    higress.io/resource-definer: higress
  name: ai-proxy-test-r
  namespace: higress-system
  resourceVersion: "39098037"
  selfLink: /apis/networking.k8s.io/v1/namespaces/higress-system/ingresses/ai-proxy-test-r
  uid: 2a5213c8-3e77-43bc-bbee-240a7148bb5e
spec:
  ingressClassName: higress
  rules:
  - host: ai.proxy.test.com
    http:
      paths:
      - backend:
          resource:
            apiGroup: networking.higress.io
            kind: McpBridge
            name: default
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
```

`ai-proxy` 配置如下：
```yaml
apiVersion: extensions.higress.io/v1alpha1
kind: WasmPlugin
metadata:
  annotations:
    higress.io/wasm-plugin-description: Provide unified OpenAI API compatible interface
      to call different AI service providers.
    higress.io/wasm-plugin-icon: https://img.alicdn.com/imgextra/i1/O1CN018iKKih1iVx287RltL_!!6000000004419-2-tps-42-42.png
    higress.io/wasm-plugin-title: AI Proxy
  creationTimestamp: "2025-03-07T07:17:13Z"
  generation: 40
  labels:
    higress.io/resource-definer: higress
    higress.io/wasm-plugin-built-in: "true"
    higress.io/wasm-plugin-category: ai
    higress.io/wasm-plugin-name: ai-proxy
    higress.io/wasm-plugin-version: 1.0.0
  name: ai-proxy-1.0.0
  namespace: higress-system
  resourceVersion: "39099454"
  selfLink: /apis/extensions.higress.io/v1alpha1/namespaces/higress-system/wasmplugins/ai-proxy-1.0.0
  uid: f4780d43-560a-42fa-b4d0-2d08e1aee529
spec:
  defaultConfig:
    provider:
      type: openai
  defaultConfigDisable: true
  matchRules:
  - config:
      provider:
        type: ai-proxy-test
    ingress:
    - ai-proxy-test-r
  phase: UNSPECIFIED_PHASE
  priority: 100
  url: oci://higress-registry.cn-hangzhou.cr.aliyuncs.com/plugins/ai-proxy:latest
```
## 麻烦帮看一下，配置有什么错误吗？ 现在 `curl` 直接 500 
```bash
curl -i -X POST 'http://10.19.93.164:32111/v1/chat/completions' -H 'Content-Type: application/json' -H 'Authorization: Bearer d87352c8-4532-4243-aef2-a122ff25d195' -H 'host: ai.proxy.test.com' -d '{
    "model": "qwen2-72b-instruct-gptq-int4",
    "messages": [
        {"role": "user","content": "hi"}
    ],
    "temperature": 0,
    "stream": false,
    "stream_options":{
        "include_usage": true
    }
}'
HTTP/1.1 500 Internal Server Error
date: Sat, 08 Mar 2025 08:41:49 GMT
server: istio-envoy
content-length: 0
```
## `higress-gateway` 报错日志如下 

![Image](https://github.com/user-attachments/assets/422c2be6-4688-4b73-a2a0-80b26d3e2329)

**Comment by huhaiqwer** [comment]
> 接上文，参考 官网 ai-proxy 在 k8s 上的使用，现在发现配置之后 `higress-gateway` 直接报错。麻烦老师帮忙解惑下~ 新建服务来源 `ai-proxy-test`、配置如下：
> 
> ![Image](https://github.com/user-attachments/assets/bde68693-9d83-44b8-9ac9-5a2a8a7155e0)
> 
> 新建 ingress `ai-proxy-test-r`,配置如下：
> 
> apiVersion: networking.k8s.io/v1
> kind: Ingress
> metadata:
>   annotations:
>     higress.io/destination: ai-proxy-test.static
>     higress.io/ignore-path-case: "true"
>   creationTimestamp: "2025-03-08T08:40:26Z"
>   generation: 1
>   labels:
>     higress.io/domain_ai.proxy.test.com: "true"
>     higress.io/resource-definer: higress
>   name: ai-proxy-test-r
>   namespace: higress-system
>   resourceVersion: "39098037"
>   selfLink: /apis/networking.k8s.io/v1/namespaces/higress-system/ingresses/ai-proxy-test-r
>   uid: 2a5213c8-3e77-43bc-bbee-240a7148bb5e
> spec:
>   ingressClassName: higress
>   rules:
>   - host: ai.proxy.test.com
>     http:
>       paths:
>       - backend:
>           resource:
>             apiGroup: networking.higress.io
>             kind: McpBridge
>             name: default
>         path: /
>         pathType: Prefix
> status:
>   loadBalancer: {}
> `ai-proxy` 配置如下：
> 
> apiVersion: extensions.higress.io/v1alpha1
> kind: WasmPlugin
> metadata:
>   annotations:
>     higress.io/wasm-plugin-description: Provide unified OpenAI API compatible interface
>       to call different AI service providers.
>     higress.io/wasm-plugin-icon: https://img.alicdn.com/imgextra/i1/O1CN018iKKih1iVx287RltL_!!6000000004419-2-tps-42-42.png
>     higress.io/wasm-plugin-title: AI Proxy
>   creationTimestamp: "2025-03-07T07:17:13Z"
>   generation: 40
>   labels:
>     higress.io/resource-definer: higress
>     higress.io/wasm-plugin-built-in: "true"
>     higress.io/wasm-plugin-category: ai
>     higress.io/wasm-plugin-name: ai-proxy
>     higress.io/wasm-plugin-version: 1.0.0
>   name: ai-proxy-1.0.0
>   namespace: higress-system
>   resourceVersion: "39099454"
>   selfLink: /apis/extensions.higress.io/v1alpha1/namespaces/higress-system/wasmplugins/ai-proxy-1.0.0
>   uid: f4780d43-560a-42fa-b4d0-2d08e1aee529
> spec:
>   defaultConfig:
>     provider:
>       type: openai
>   defaultConfigDisable: true
>   matchRules:
>   - config:
>       provider:
>         type: ai-proxy-test
>     ingress:
>     - ai-proxy-test-r
>   phase: UNSPECIFIED_PHASE
>   priority: 100
>   url: oci://higress-registry.cn-hangzhou.cr.aliyuncs.com/plugins/ai-proxy:latest
> ## 麻烦帮看一下，配置有什么错误吗？ 现在 `curl` 直接 500
> curl -i -X POST 'http://10.19.93.164:32111/v1/chat/completions' -H 'Content-Type: application/json' -H 'Authorization: Bearer d87352c8-4532-4243-aef2-a122ff25d195' -H 'host: ai.proxy.test.com' -d '{
>     "model": "qwen2-72b-instruct-gptq-int4",
>     "messages": [
>         {"role": "user","content": "hi"}
>     ],
>     "temperature": 0,
>     "stream": false,
>     "stream_options":{
>         "include_usage": true
>     }
> }'
> HTTP/1.1 500 Internal Server Error
> date: Sat, 08 Mar 2025 08:41:49 GMT
> server: istio-envoy
> content-length: 0
> ## `higress-gateway` 报错日志如下
> ![Image](https://github.com/user-attachments/assets/422c2be6-4688-4b73-a2a0-80b26d3e2329)

将 `provider` 修改成 `openai` 已解决这个问题。

**Comment by huhaiqwer** [comment]
现在 上报后的指标，从 `prometheus ` 查查询，发现 指标不对 

![Image](https://github.com/user-attachments/assets/80fd2fb0-a337-4c1f-a1ac-aa597df9f9d1)
查询语句中应该不带有 `模型名称` 且 `label` 里面没有 `ai-model`  导致，导入官方的 `grafana` 的 `token` 模板 之后，无法查看，请问老师是哪里配置错了吗

**Comment by huhaiqwer** [comment]
这跟官方的采集的指标不一样呀：

![Image](https://github.com/user-attachments/assets/c3029643-ba11-4119-9daa-5515e43c9e27)

**Comment by cr7258** [comment]
正常情况下指标名应该是和官网文档里的一样的，不会带有自己的模型名称，模型名称应该出现在 `ai-model` label 中。
看上去像是 route 和 upstream 部分 label 提取失败了，导致最终保留了原始指标名称。
你这个指标是在 k8s 还是 all-in-one 中拿到的？你把完整的配置贴一下，方便我进行复现。

**Comment by cr7258** [comment]
> 我们正常时候 curl 请求带的 model 名称跟模型实际名称是一直的。可以请老师解答以下吗，官网的解释我不是很理解

如果你请求带的 model 名称和实际上一样的，就不用配 modelMapping。
modelMapping 的作用是比如你原始的请求是 gpt-3，会转换成实际的 model deepseek-chat。
```yaml
modelMapping:
  - "gpt-3": "deepseek-chat"
```

**Comment by cr7258** [comment]
> 开启 ai-statustic 之后，日志会有输出， 这里 报错 Get model failed ，意识是找不到模型吗？

从这个日志上看，你应该不是用的最新版本的 ai-statistics 插件吧？ 你换成最新的版本试试: oci://higress-registry.cn-hangzhou.cr.aliyuncs.com/plugins/ai-statistics:1.0.0

**Comment by huhaiqwer** [comment]
> 正常情况下指标名应该是和官网文档里的一样的，不会带有自己的模型名称，模型名称应该出现在 `ai-model` label 中。 看上去像是 route 和 upstream 部分 label 提取失败了，导致最终保留了原始指标名称。 你这个指标是在 k8s 还是 all-in-one 中拿到的？你把完整的配置贴一下，方便我进行复现。

老师你好：

`higress` 部署在  k8s 上

 `inrgess`   配置如下：

![Image](https://github.com/user-attachments/assets/32bdc245-69d5-4fd6-89bf-b04c15642b0e)

`mcpBridge` 配置如下:

![Image](https://github.com/user-attachments/assets/1b7ed9bf-98db-47a6-9282-d7b44ea2c6c5)

`路由 对应 ai-proxy`  配置如下:

![Image](https://github.com/user-attachments/assets/29a180f9-fd7b-4280-8e81-f6019f2ecd75)

`prometheus` 可查询指标如下：

![Image](https://github.com/user-attachments/assets/a136a48d-2446-42ed-a988-f388f006e00c)

**Comment by huhaiqwer** [comment]
日志中记录的 `ai_log` 与官方的官网所记录的日志也不一致


![Image](https://github.com/user-attachments/assets/3ddc927c-3cd5-4518-9ef9-8adb516c7a9d)

**Comment by cr7258** [comment]
我在本地通过 ollama 部署了 llama3.2:1b 模型，按照你提供的配置进行了设置，我看到的 metric 是正常的，没有出现名字中带有模型名称的情况。我看你是私有的镜像地址部署的，请确保 ai-statistics 插件使用了最新的版本。

```yaml
istio-proxy@higress-gateway-744b4fc98d-qh477:/$ curl -sS http://127.0.0.1:15020/stats/prometheus | grep "model"
# TYPE route_upstream_model_consumer_metric_input_token counter
route_upstream_model_consumer_metric_input_token{ai_route="ai-proxy-test-r",ai_cluster="outbound|80||ai-proxy-test.static",ai_model="llama3.2:1b",ai_consumer="none"} 116

# TYPE route_upstream_model_consumer_metric_llm_duration_count counter
route_upstream_model_consumer_metric_llm_duration_count{ai_route="ai-proxy-test-r",ai_cluster="outbound|80||ai-proxy-test.static",ai_model="llama3.2:1b",ai_consumer="none"} 4

# TYPE route_upstream_model_consumer_metric_llm_service_duration counter
route_upstream_model_consumer_metric_llm_service_duration{ai_route="ai-proxy-test-r",ai_cluster="outbound|80||ai-proxy-test.static",ai_model="llama3.2:1b",ai_consumer="none"} 2063

# TYPE route_upstream_model_consumer_metric_output_token counter
route_upstream_model_consumer_metric_output_token{ai_route="ai-proxy-test-r",ai_cluster="outbound|80||ai-proxy-test.static",ai_model="llama3.2:1b",ai_consumer="none"} 170
```

以下是完整的配置：

```yaml
apiVersion: extensions.higress.io/v1alpha1
kind: WasmPlugin
metadata:
  name: ai-proxy-1.0.0
  namespace: higress-system
spec:
  matchRules:
  - config:
      provider:
        type: openai
        apiTokens:
        - "sk-123456"
    ingress:
    - ai-proxy-test-r
  url: oci://higress-registry.cn-hangzhou.cr.aliyuncs.com/plugins/ai-proxy:1.0.0
  phase: UNSPECIFIED_PHASE
  priority: 100
---
apiVersion: extensions.higress.io/v1alpha1
kind: WasmPlugin
metadata:
  name: ai-statistics
  namespace: higress-system
spec:
  matchRules:
  - ingress:
      - ai-proxy-test-r
  url: oci://higress-registry.cn-hangzhou.cr.aliyuncs.com/plugins/ai-statistics:1.0.0
  phase: UNSPECIFIED_PHASE
  priority: 200
---
apiVersion: networking.higress.io/v1
kind: McpBridge
metadata:
  name: default
  namespace: higress-system
spec:
  registries:
  - domain: 192.168.2.153:15000
    name: ai-proxy-test
    port: 80
    type: static
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    higress.io/destination: ai-proxy-test.static
  name: ai-proxy-test-r
  namespace: higress-system
spec:
  ingressClassName: higress
  rules:
  - host: ai.proxy.test.com
    http:
      paths:
      - backend:
          resource:
            apiGroup: networking.higress.io
            kind: McpBridge
            name: default
        path: /
        pathType: Prefix

```
