### ISSUE TITLE
Support modifying model name based on model mapping when falling back to the target service

### ISSUE THREAD

**Issue by johnlanni** [alibaba/higress#1902]
When using the fallback capability, it is similar to the situation in #1901 , where model mapping cannot be set.

![Image](https://github.com/user-attachments/assets/d65a88cc-8a22-4393-8fc2-524bb9136ba5)

The configuration method also needs to be modified in a similar way.

![Image](https://github.com/user-attachments/assets/0eeb4188-29ea-4500-973d-c9d375c5d43a)

Can be changed to the following configuration:

```yaml
apiVersion: extensions.higress.io/v1alpha1
kind: WasmPlugin
metadata:
  name: model-mapper.internal
  namespace: higress-system
spec:
  defaultConfigDisable: true
  failStrategy: FAIL_OPEN
  matchRules:
  - config:
      modelMapping:
        'gpt-4-*': "qwen-max"
        'gpt-4o': "qwen-vl-plus"
        '*': "qwen-turbo"
    configDisable: false
    # This configuration takes effect when the following ingress and service match simultaneously.
    ingress:
    - ai-route-dashscope.internal
    service:
    - llm-dashscope.internal.dns
  - config:
      modelMapping:
        'gpt-4-*': "qwen-plus"
        '*': "qwen-long"
    configDisable: false
    # This configuration takes effect when the following ingress and service match simultaneously.
    ingress:
    # When fallback is triggered, it will go through this ingress.
    - ai-route-dashscope.fallback.internal
    service:
    - llm-dashscope.internal.dns    
  phase: AUTHN
  priority: 800
  url: oci://higress-registry.cn-hangzhou.cr.aliyuncs.com/plugins/model-mapper:1.0.0
```
