### ISSUE TITLE
关于 ai-cache插件的使用

### ISSUE THREAD

**Issue by dequeueing** [alibaba/higress#1939]
你好，我正在尝试使用ai-proxy插件。配置如下：

![Image](https://github.com/user-attachments/assets/533c7e5b-8623-48e1-8084-decd93905445)

配置完成后没有效果，具体表现为问同样的问题也不会返回相同的回答。

另外向量数据库中也没有数据：

![Image](https://github.com/user-attachments/assets/10d0fab0-648c-4fc2-96e5-3a3ac474bf8f)

请问应该如何解决呢？

**Comment by CH3CHO** [comment]
这里问题稍微有点多：
1. 你配置的是 AI 缓存插件，也就是 ai-cache，而不是 ai-proxy。它的文档在这里：https://higress.cn/docs/latest/plugins/ai/api-provider/ai-cache/
2. `serviceHost` 只需要配置域名，而不是完整的 URL；
3. 两个服务，`my_dashscope.dns` 和 `my_dashvector.dns` 你是怎么配置的呢？所有的服务都需要在服务来源中进行配置，然后到服务列表里查看对应的服务名字。可以看一下这里：https://github.com/alibaba/higress/issues/1812
4. 如果还不行，可以查看 Gateway 容器日志，里面会记录插件的运行信息。有什么错误的话可以再贴上来。

**Comment by dequeueing** [comment]
> 这里问题稍微有点多：
> 
> 1. 你配置的是 AI 缓存插件，也就是 ai-cache，而不是 ai-proxy。它的文档在这里：https://higress.cn/docs/latest/plugins/ai/api-provider/ai-cache/
> 2. `serviceHost` 只需要配置域名，而不是完整的 URL；
> 3. 两个服务，`my_dashscope.dns` 和 `my_dashvector.dns` 你是怎么配置的呢？所有的服务都需要在服务来源中进行配置，然后到服务列表里查看对应的服务名字。可以看一下这里：[自定义的外部请求插件报错 #1812](https://github.com/alibaba/higress/issues/1812)
> 4. 如果还不行，可以查看 Gateway 容器日志，里面会记录插件的运行信息。有什么错误的话可以再贴上来。

感谢回复！因为我刚上手higress不久，所以想请教一下：

1. 若我的服务均来自阿里云（向量模型和向量数据库），应该如何查看服务域名？
2. 创建服务时应该如何选择类型呢？

我的higress通过docker compose部署在本地，所有的操作都是在ui上完成的。
谢谢！

**Comment by CH3CHO** [comment]
> 1. 若我的服务均来自阿里云（向量模型和向量数据库），应该如何查看服务域名

这个阿里云界面上都会告诉你把。

> 2. 创建服务时应该如何选择类型呢？

选 DNS 域名呗。

**Comment by dequeueing** [comment]
你好，ai-cache插件配置如下：

```yaml
embedding:
  apiKey: "*************************"
  model: "text-embedding-v2"
  serviceHost: "dashscope.aliyuncs.com/compatible-mode/v1/embeddings"
  serviceName: "embedding-model.dns"
  type: "dashscope"
enableSemanticCache: true
vector:
  apiKey: "*************************"
  collectionID: "semantic-cache"
  serviceHost: "vrs-cn-ow746o17u00014.dashvector.cn-hangzhou.aliyuncs.com/v1/collections/quickstart"
  serviceName: "embedding-db.dns"
  timeout: 1000000
  type: "dashvector"
```



插件出现internal error：
```plaintext
gateway-1     | 2025-03-24T10:19:08.914697Z	info	Envoy proxy is ready
gateway-1     | 2025-03-24T10:20:30.963661Z	error	envoy wasm external/envoy/source/extensions/common/wasm/context.cc:1401	wasm log higress-system.ai-cache-1.0.0: [ai-cache] [nil] [07a29470-62dc-420a-9db6-0ed1ccbb8d01] [ai-cache] [handleInternalError] [ai-cache] [performEmbeddingQuery] error getting embedding for key: What is the longest river in the world?: failed to get embedding due to status code: 400	thread=80
gateway-1     | 2025-03-24T10:22:48.452982Z	error	envoy wasm external/envoy/source/extensions/common/wasm/context.cc:1401	wasm log higress-system.ai-cache-1.0.0: [ai-cache] [nil] [fe1e2d1c-57ce-44d1-afc3-3d0a59e2855e] [ai-cache] [handleInternalError] [ai-cache] [performEmbeddingQuery] error getting embedding for key: What is the longest river in the world?: failed to get embedding due to status code: 400	thread=71
gateway-1     | 2025-03-24T10:24:24.872350Z	error	envoy wasm external/envoy/source/extensions/common/wasm/context.cc:1401	wasm log higress-system.ai-cache-1.0.0: [ai-cache] [nil] [77e28909-f21c-4d4c-9362-97a1ebb47a6b] [ai-cache] [handleInternalError] [ai-cache] [performEmbeddingQuery] error getting embedding for key: What is the capital of France?: failed to get embedding due to status code: 400	thread=87

```


能否帮忙看一下哪里出现错误？embedding和vector服务来源均已经配置好。

**Comment by dequeueing** [comment]
![Image](https://github.com/user-attachments/assets/3ed569fc-7639-45e2-af13-09b2688a3e42)

**Comment by CH3CHO** [comment]
serviceHost 只需要域名，不用后面的东西。

**Comment by dequeueing** [comment]
> serviceHost 只需要域名，不用后面的东西。

已经修改域名，新的错误为503error：
```plaintext
gateway-1     | 2025-03-24T11:01:05.836545Z	error	envoy wasm external/envoy/source/extensions/common/wasm/context.cc:1401	wasm log higress-system.ai-cache-1.0.0: [ai-cache] [nil] [2481a323-3127-4273-b9fb-2aec31ac7939] [ai-cache] [handleInternalError] [ai-cache] [handleQueryResults] error querying vector database for key: What is the capital of France?: failed to query embedding: 503	thread=99
gateway-1     | 2025-03-24T11:01:13.061013Z	error	envoy wasm external/envoy/source/extensions/common/wasm/context.cc:1401	wasm log higress-system.ai-cache-1.0.0: [ai-cache] [nil] [ade7a1fd-6d2e-40a8-addd-d793112ecc8e] [ai-cache] [handleInternalError] [ai-cache] [handleQueryResults] error querying vector database for key: What is the capital of France?: failed to query embedding: 503	thread=81

```

**Comment by dequeueing** [comment]
服务来源已经配置好：


![Image](https://github.com/user-attachments/assets/700cee02-544d-493d-85f6-03383163cb3f)

ai-cache embedding配置如下：

```plaintext
embedding:
  apiKey: ************************
  model: "text-embedding-v2"
  serviceHost: "dashscope.aliyuncs.com"
  serviceName: "embedding-model.dns"
  type: "dashscope"

```


api key检查无误

**Comment by CH3CHO** [comment]
![Image](https://github.com/user-attachments/assets/912b627e-b9cc-4d48-a957-37e7a138b3bd)

把这个协议改对之后再试试

**Comment by CH3CHO** [comment]
> 3\. 若服务支持https则需选择https

这一点有问题。不是说服务支持 HTTPS，是因为你配的 443 端口它只能用 HTTPS 协议请求。用 HTTP 请求是不行的。

**Comment by sxueck** [comment]
目前我也出现了同样的问题，使用 docker-compose 部署后，报错
```
2025-04-17T16:21:27.782205Z     error   envoy wasm external/envoy/source/extensions/common/wasm/context.cc:1401 wasm log higress-system.ai-cache-1.0.0: [ai-cache] [nil] [c1328615-1422-41e1-9512-780ea4b7a104] [ai-cache] [handleInternalError] [ai-cache] [performEmbeddingQuery] error querying vector database for key: 说三遍你好: error status returned by host: bad argument   thread=81
2025-04-17T16:21:28.451056Z     warning envoy wasm external/envoy/source/extensions/common/wasm/context.cc:1398 wasm log higress-system.ai-cache-1.0.0: [ai-cache] [nil] [c1328615-1422-41e1-9512-780ea4b7a104] [ai-cache] [uploadEmbeddingAndAnswer] failed to upload answer embedding for key: 说三遍你好, error: error status returned by host: bad argument       thread=81
```

我的配置
```
embedding:
  apiKey: "************************"
  model: "embed-multilingual-v3.0"
  normalize: true
  serviceHost: "api.cohere.com"
  serviceName: "llm-CommandR.internal.dns"
  type: "cohere"
enableSemanticCache: true
vector:
  collectionID: "llm-cache"
  serviceHost: "chroma.llm"
  serviceName: "chroma-docker.dns"
  type: "chroma"
```

我的路由

![Image](https://github.com/user-attachments/assets/946fe51c-18f0-451f-8388-52d8dc24d575)

我的路由路径联通

![Image](https://github.com/user-attachments/assets/7733da64-5d26-42be-a0ac-13011f070cfa)

我的 Chroma 库也是正常的

![Image](https://github.com/user-attachments/assets/537da540-d89d-4d54-a58a-6af5b927a287)
