### ISSUE TITLE
helm安装时gzip也给个配置吧

### ISSUE THREAD

**Issue by w7team** [alibaba/higress#1968]
```
    gzip:
      enable: true
      minContentLength: 1024
      contentType:
        - text/plain
        - text/html
        - application/json
        - text/css
        - application/javascript
        - application/xhtml+xml
        - image/svg+xml
      disableOnEtagHeader: true
      memoryLevel: 5
      windowBits: 12
      chunkSize: 4096
      compressionLevel: BEST_COMPRESSION
      compressionStrategy: DEFAULT_STRATEGY
```

像downstream一样，可以helm set配置

**Comment by undertaker86001** [comment]
可能要自己改一下


### 1. 在 values.yaml 中添加 gzip 配置

在 `helm/core/values.yaml` 中添加 gzip 配置段：

```yaml
# -- Gzip compression settings
gzip:
  enable: false
  minContentLength: 1024
  contentType:
    - text/html
    - text/css
    - text/plain
    - text/xml
    - application/json
    - application/javascript
    - application/xhtml+xml
    - image/svg+xml
  disableOnEtagHeader: true
  memoryLevel: 5
  windowBits: 12
  chunkSize: 4096
  compressionLevel: BEST_COMPRESSION
  compressionStrategy: DEFAULT_STRATEGY
```

### 2. 修改 ConfigMap 模板

在 `helm/core/templates/configmap.yaml` 中添加 gzip 配置处理逻辑，类似现有的 downstream 处理方式 ：

```yaml
{{- if hasKey .Values "gzip" }}
{{- $_ := set $newData "gzip" .Values.gzip }}
{{- end }}
```

### 3. 使用方式

实现后，可以通过以下方式配置：

```bash
# 通过 --set 参数
helm install higress higress.io/higress \
  --set gzip.enable=true \
  --set gzip.minContentLength=2048

# 通过 values 文件
helm install higress higress.io/higress -f custom-values.yaml
```
