### ISSUE TITLE
ai-proxy: qwen support custom path with compatible

### ISSUE THREAD

**Issue by HecarimV** [alibaba/higress#2026]
## Why do you need it?
在使用 Higress 的 QwenProvider 时，当开启 qwenEnableCompatible 模式以启用 Qwen 的兼容功能时，当前设计默认使用 内置路径作为 API 路径。然而，实际业务场景中path可能需要修改
```golang
qwenChatCompatiblePath          = "/compatible-mode/v1/chat/completions"
qwenTextEmbeddingCompatiblePath = "/compatible-mode/v1/embeddings"
``` 

## How could it be?
providerConfig 添加一个字段来控制使用兼容模式时可以使用原生url path

**Comment by HecarimV** [comment]
```yaml
provider:
  type: qwen
  apiTokens:
    - "YOUR_QWEN_API_TOKEN"
  qwenEnableCustomCompatible: true  //开启自定义兼容模式。将调用自定义兼容模式接口，同时对请求/响应不做修改
```
AI 对话请求示例
URL: http://your-domain/a/b/c/v1/chat/completions    
```wiki
默认情况下(没开启兼容模式)
/a/b/c/v1/chat/completions会被重写为/api/v1/services/aigc/text-generation/generation 请求/响应会做修改
```
```wiki
和qwenEnableCompatible对比
qwenEnableCompatible: true  path被重写为/compatible-mode/v1/chat/completions 请求/响应不会做修改
qwenEnableCustomCompatible: true  path依旧为/a/b/c/v1/chat/completions 请求/响应不会做修改
```
