### ISSUE TITLE
ai 网关all in one 是不是没有 redis，因为 ai 网关肯定是带有 mcp 的

### ISSUE THREAD

**Issue by jundaychan** [alibaba/higress#2050]
https://higress.cn/ai/mcp-server/?spm=36971b57.21353015.0.0.58687095dev5EW
我看这里官方说必须要 redis 服务，是不是all in one 的镜像并没有 redis，所以是需要重新开启一个服务吗

**Comment by Jing-ze** [comment]
```

**Comment by Jing-ze** [comment]
redis 后面可以考虑加到all-in-one镜像里

**Comment by jundaychan** [comment]
> ```
> docker run -d --rm --name higress-ai --network higress-net -v ${PWD}:/data -p 8001:8001 -p 8080:8080 -p 8443:8443 higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/all-in-one:late
> ```

命令有错，应该是
```
docker run -d --rm --name higress-ai --network higress-net -v ${PWD}:/data -p 8001:8001 -p 8080:8080 -p 8443:8443 higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/all-in-one:latest
```

**Comment by jundaychan** [comment]
> redis 后面可以考虑加到all-in-one镜像里

也许持久化储存也可以打包进去，因为也要考虑轻度生产环境，大部分中小企业k8s 上的少

**Comment by CplusHua** [comment]
> > redis 后面可以考虑加到all-in-one镜像里
> 
> 也许持久化储存也可以打包进去，因为也要考虑轻度生产环境，大部分中小企业k8s 上的少

```
name: higress

services:
  redis:
    image: redis:6-alpine #redis:alpine
    restart: always
    container_name: redis
    environment:
      REDIS_PASSWORD: ""
    volumes:
      - ./redis_db:/data
  higress-ai:
    image: higress/all-in-one:latest
    container_name: higress
    ports:
      - "8001:8001"
      - "8080:8080"
      - "8443:8443"
      - "15020:15020"
      - "15021:15021"
    volumes:
      - ./data:/data
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./logs:/var/log/higress
    restart: unless-stopped
```

可以参考这个docker-compose.yml配置
