### ISSUE TITLE
MCP Client访问 /user/sse 不生效，请求似乎被路由到了randomuser.me

### ISSUE THREAD

**Issue by xmmak** [alibaba/higress#2051]
基于k8s+helm部署了higress，并按文档进行了配置 https://higress.cn/ai/mcp-quick-start

configmap配置如下
```
apiVersion: v1
data:
  higress: |-
    downstream:
      connectionBufferLimits: 32768
      http2:
        initialConnectionWindowSize: 1048576
        initialStreamWindowSize: 65535
        maxConcurrentStreams: 100
      idleTimeout: 180
      maxRequestHeadersKb: 60
      routeTimeout: 0
    upstream:
      connectionBufferLimits: 10485760
      idleTimeout: 10
    mcpServer:
      sse_path_suffix: /sse 
      enable: true          
      redis:
        address: redis-stack-server.higress-system.svc.cluster.local:6379 
        db: 0
      match_list:  
        - match_rule_domain: "*"
          match_rule_path: /user
          match_rule_type: "prefix"
      servers: 
        - name: nacos-mcp-registry
          type: nacos-mcp-registry
          path: /registry
            config:
              serverAddr: "10.10.17.41"
              namespace: "public"
              serviceMatcher:
                amap: ".*"
                ip: ".*"
                your-service-group: "service-match-pattern"
```

已完成路由配置

![Image](https://github.com/user-attachments/assets/a0e06775-3f87-4216-9b22-8162cfb98566)

访问 MCP Server /user/sse地址时，有报错如下：

![Image](https://github.com/user-attachments/assets/039eef2c-1ecc-4885-9027-3269de1fbb85)

查看gateway日志没error报错，有如下日志：
```
{"ai_log":"-","authority":"10.1.36.249","bytes_received":"0","bytes_sent":"151","downstream_local_address":"10.1.183.248:80","downstream_remote_address":"10.1.176.0:49997","duration":"576","istio_policy_status":"-","method":"GET","path":"/user/sse","protocol":"HTTP/1.1","request_id":"94a71027-62ee-4870-b288-0486b68a1570","requested_server_name":"-","response_code":"403","response_flags":"-","route_name":"higress-test/user","start_time":"2025-04-14T02:31:06.932Z","trace_id":"-","upstream_cluster":"outbound|443||user.dns","upstream_host":"104.21.96.1:443","upstream_local_address":"10.1.183.248:33880","upstream_service_time":"573","upstream_transport_failure_reason":"-","user_agent":"node","x_forwarded_for":"10.1.176.0","response_code_details":"via_upstream"}
```

看起来是/user/sse的请求被路由到randomuser.me了吗，是MCP Server配置没生效吗，如果是的话可以从哪里确认呢
