### ISSUE TITLE
【REST-TO-MCP】在 call-mcp-tool 时出现了 json 序列化问题

### ISSUE THREAD

**Issue by X-TAN** [alibaba/higress#2058]
# 原始错误
envoy wasm external/envoy/source/extensions/common/wasm/context.cc:1401
wasm log higress-system.mcp-server-1.0.0: [mcp-server] [ai-mcp-server/queryEmployeeLeaveBalance] 
`json unmarshal server config failed:unexpected end of JSON input`
<img width="1726" alt="Image" src="https://github.com/user-attachments/assets/9fb5e611-a2bc-4149-85e4-a0f92d7b2460" />

服务配置：
<img width="495" alt="Image" src="https://github.com/user-attachments/assets/a82dca2e-7de4-42f9-aad9-40ca840c1a86" />
![Image](https://github.com/user-attachments/assets/9c55abd6-24a3-4946-b9d6-d919f4ea2499)
![Image](https://github.com/user-attachments/assets/7aaa3a16-6442-473b-a0e6-d2e61b9ae984)
插件配置：
```yaml
server:
  name: "ai-mcp-server"
tools:
- args:
  - description: "员工工号"
    name: "workNumber"
    position: "body"
    required: true
    type: "string"
  description: "员工假期余额查询"
  method: "POST"
  name: "queryEmployeeLeaveBalance"
  requestTemplate:
    headers:
    - key: "authorization"
      value: "xxx"
  responseTemplate:
    prependBody: |
      # API响应说明
      - **code**: 返回码，返回0为请求成功，其他一切为请求失败，这时在 msg 中会提示异常消息。
      - **msg**: 返回消息
      - **data**: 返回数据
        - **holidayBalances**: 员工假期余额列表
          - **holidayType**: 假期类型标记，（如 1：年假，2：病假）
          - **holidayName**: 假假期名称（如 "年假"、"病假"）
          - **plusDay**: 假期总余额，按天
          - **leaveDaysDetail**: 假期明细列表，包含具体的假期天数及过期时间
            - **leaveDay**: 可用的假期天数
            - **expiredTime**: 该假期的过期时间（过期时间格式:yyyy-MM-dd）
  url: "http://172.20.13.93:10086/ai-plugin-box/execute/"
```
客户端连接并使用：
![Image](https://github.com/user-attachments/assets/33866538-4748-4787-85bc-b56b218f88ed)

请求返回成功，但是提供REST-API的服务端并未收到请求，而是在 higress-gateway 提示了
envoy wasm external/envoy/source/extensions/common/wasm/context.cc:1401
wasm log higress-system.mcp-server-1.0.0: [mcp-server] [ai-mcp-server/queryEmployeeLeaveBalance] 
`json unmarshal server config failed:unexpected end of JSON input`

请问这个问题该如何解决？
