### ISSUE TITLE
basic auth插件：当配置中同时未和设置matchRules和defaultConfig.global_auth的情况下

### ISSUE THREAD

**Issue by PangQingcheng** [alibaba/higress#2069]
basic auth插件：
当配置中同时未和设置matchRules和defaultConfig.global_auth的情况下，会被默认为开启了全局鉴权。
和配置表述预期不符。
示例:
```
apiVersion: extensions.higress.io/v1alpha1
kind: WasmPlugin
metadata:
  annotations:
    higress.io/wasm-plugin-description: implement authentication feature based on HTTP Basic Auth standard.
    higress.io/wasm-plugin-icon: >-
      https://img.alicdn.com/imgextra/i4/O1CN01BPFGlT1pGZ2VDLgaH_!!6000000005333-2-tps-42-42.png
    higress.io/wasm-plugin-title: Basic Auth
  labels:
    higress.io/resource-definer: higress
    higress.io/wasm-plugin-built-in: 'true'
    higress.io/wasm-plugin-category: auth
    higress.io/wasm-plugin-name: basic-auth
    higress.io/wasm-plugin-version: 1.0.0
    k8slens-edit-resource-version: v1alpha1
  name: basic-auth-1.0.0
  namespace: higress-system
spec:
  defaultConfig:
    consumers:
      - credential: admin:123456
        name: consumer
url: oci://xxxxxx
```
