### ISSUE TITLE
[higress 2.1.0] higress 对接nacos mcp后无法及时更新服务和配置

### ISSUE THREAD

**Issue by biggerball** [alibaba/higress#2101]
**higress mcpServer无法更新服务和配置**
higress无法及时感知服务和配置更新

**复现过程**
1.nacos已有一个mcp配置，通过mcpServers添加在higress并且可以调通。
nacos配置，group为umemix-web
```
{
    "protocol": "http",
    "tools": [
        {
            "name": "test_get",
            "description": "test post request by name",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "name"
                    }
                }
            }
        }
    ],
    "toolsMeta": {
        "test_get": {
            "InvokeContext": {
                "path": "/umemix-web/api/get",
                "method": "GET"
            }
        }
    }
}
```
higress配置
```
mcpServer:
  enable: true
  sse_path_suffix: /sse
  match_list:
    - match_rule_domain: '*'
      match_rule_path: /registry
      match_rule_type: prefix
  redis:
    address: 172.24.86.50:6387
  servers:
    - name: nacos-registry
      type: nacos-mcp-registry
      path: /registry
      config:
        serverAddr: 172.24.146.72
        namespace: public
        serviceMatcher:
          umemix-web: ".*"
```
2.将nacos配置的``tool[0].name``和``toolsMeta.test_get``变更为``test_get1``并保存，此时使用mcp client调用listTool方法，获取到``test_get``和``test_get1``共2个tool，``test_get``未按预期删除。
![Image](https://github.com/user-attachments/assets/72b0d076-f115-4aed-92d9-aaad7aa9eb5f)

3.tool的提供者为微服务，采用k8s部署。应用重新部署后注册到nacos的ip改变，higress依然会调用已删除的pod ip，未按预期调用新ip

**环境:**
nacos-server 3.0.0-BETA， java nacos-client 2.4.3，higress 2.1.0
higress和tool提供者部署在k8s
