### ISSUE TITLE
not_support_sse_on_this_endpoint

### ISSUE THREAD

**Issue by lordk911** [alibaba/higress#2138]
1、想要将一个现有的 fastapi 的服务转成 mcp server
2、higress 基于 helm 部署
3、参考文档 https://higress.cn/ai/mcp-quick-start/

`kubectl edit configmap higress-config -n higress-system`  启用 mcp server

```
apiVersion: v1
data:
  higress: |-
    downstream:
      connectionBufferLimits: 32768
      http2:
        initialConnectionWindowSize: 1048576
        initialStreamWindowSize: 65535
        maxConcurrentStreams: 100
      idleTimeout: 180
      maxRequestHeadersKb: 60
      routeTimeout: 0
    upstream:
      connectionBufferLimits: 10485760
      idleTimeout: 10
    mcpServer:
      sse_path_suffix: /sse  # SSE 连接的路径后缀
      enable: true          # 启用 MCP Server
      redis:
        address: redis-stack-server.higress-system.svc.cluster.local:6379 # Redis服务地址
        username: "" # Redis用户名（可选）
        password: "" # Redis密码（可选）
        db: 0 # Redis数据库（可选）
      match_list:          # MCP Server 会话保持路由规则（当匹配下面路径时，将被识别为一个 MCP 会话，通过 SSE 等机制进行会话保持）
        - match_rule_domain: "*"
          match_rule_path: /postgres
          match_rule_type: "prefix"
        - match_rule_domain: "*"
          match_rule_path: /user
          match_rule_type: "prefix"
      servers: []
```

4、添加服务来源 和 配置路由   （**到这里测试是成功的，能访问到后端的 api**）

5、使用 https://github.com/higress-group/openapi-to-mcpserver 将 openai 文档转换成 mcp-server.yaml
5、拷贝mcp-server.yaml的内容到 MCP 服务器 插件内：

![Image](https://github.com/user-attachments/assets/d8087697-223f-4779-b2eb-4562c6a1d049)

6、尝试在浏览器访问任何端点，都是 405 错误。 

7、gate way 的日志：
`{"ai_log":"-","authority":"example.com:280","bytes_received":"0","bytes_sent":"0","downstream_local_address":"10.0.104.140:280","downstream_remote_address":"10.1.33.204:53989","duration":"1","istio_policy_status":"-","method":"GET","path":"/cdc/sse","protocol":"HTTP/1.1","request_id":"40d1073b-0167-4204-a800-14e4fed71e2f","requested_server_name":"-","response_code":"405","response_flags":"-","route_name":"-","start_time":"2025-04-28T06:34:50.005Z","trace_id":"-","upstream_cluster":"outbound|80||cdc-api-service.static","upstream_host":"-","upstream_local_address":"-","upstream_service_time":"-","upstream_transport_failure_reason":"-","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36","x_forwarded_for":"10.1.33.204","response_code_details":"via_wasm::higress-system.mcp-server-1.0.0::not_support_sse_on_this_endpoint"}`

不知道哪里没有配置对

**Comment by lordk911** [comment]
解决了，higress-config 的 match_list 需要包含之前配置的路由，这个是每次都要手动改吗？

如果改成下面这样可以吗，影响会话保持？ ：

```
match_list:  
        - match_rule_domain: "*"
          match_rule_path: /*
          match_rule_type: "prefix"
```
