### ISSUE TITLE
higress console UI 上配置 AI 路由规则时报错

### ISSUE THREAD

**Issue by Colstuwjx** [alibaba/higress#2155]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via [ASRC](https://security.alibaba.com/)(Alibaba Security Response Center) where the issue will be triaged appropriately.**

- [x] I have searched the [issues](https://github.com/alibaba/higress/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
尝试在界面上配置一个 gpt-4o 模型的路由规则时报错：

<img width="536" alt="Image" src="https://github.com/user-attachments/assets/28ec9c2f-5d84-4719-8da9-10bcf8a8662c" />

### Ⅱ. Describe what happened

报错信息：

```
Method: put
RequestURL: https://higress-console.dev.corp/v1/ai/routes/test-gpt-4o
Headers: {"Accept":"application/json, text/plain, */*","Content-Type":"application/json"}
Data: {"success":false,"message":"io.kubernetes.client.openapi.ApiException: {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Internal error occurred: failed calling webhook \\\"vingress.elbv2.k8s.aws\\\": failed to call webhook: Post \\\"https://aws-load-balancer-webhook-service.kube-system.svc:443/validate-networking-v1-ingress?timeout=10s\\\": EOF\",\"reason\":\"InternalError\",\"details\":{\"causes\":[{\"message\":\"failed calling webhook \\\"vingress.elbv2.k8s.aws\\\": failed to call webhook: Post \\\"https://aws-load-balancer-webhook-service.kube-system.svc:443/validate-networking-v1-ingress?timeout=10s\\\": EOF\"}]},\"code\":500}\n","data":null}
```

higress 所在的集群里是有部署 aws alb 的，我理解这个报错是因为 higress console 尝试建 ingress 规则时误被 aws alb 以为是挂靠到它那里的然后校验失败？

### Ⅲ. Describe what you expected to happen
希望能够在界面上实现自助配置路由规则并最终通过一个 higress 网关域名入口请求 ai model

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. 在 aws eks 上部署 higress 集群组件，版本为 2.1.1 
2. higress core helm values.yaml 里配置 aws alb annotation：

```
global:
  ingressClass: "higress"

higress-core:
  gateway:
    replicas: 1
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-scheme: internal
        service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
        ...
```
 
3. 尝试在 higress-console 上创建 AI provider 和路由规则，路由规则创建时会报 500

### Ⅵ. Environment:

- Higress version:  v2.1.1
- K8s version: 1.27
- Others:
