### ISSUE TITLE
AI统计插件在流式输出的情况下报错，导致AI-token限流在此场景也不生效

### ISSUE THREAD

**Issue by Askhz** [alibaba/higress#2187]
## 现象
**使用流式对话时**，token限流插件不起作用，redis中的key值一直不变，统计界面也没有token数。请求body示例：
```
{
    "model": "qwen2.5-coder-32b",
    "messages": [
        {
            "role": "user",
            "content": "1+1=?"
        }
    ],
    "stream": true,
    "stream_options": {
        "include_usage": true
    }
}
```
response：
```
data: {"id":"52e707bc1b304714bd4e75ea903e6723","object":"chat.completion.chunk","created":1746681039,"model":"qwen2.5-coder-32b","choices":[{"index":0,"delta":{"role":"assistant","content":null},"logprobs":null,"finish_reason":""}],"usage":null}

data: {"id":"52e707bc1b304714bd4e75ea903e6723","object":"chat.completion.chunk","created":1746681039,"model":"qwen2.5-coder-32b","choices":[{"index":0,"delta":{"role":null,"content":"1"},"logprobs":null,"finish_reason":""}],"usage":null}

data: {"id":"52e707bc1b304714bd4e75ea903e6723","object":"chat.completion.chunk","created":1746681039,"model":"qwen2.5-coder-32b","choices":[{"index":0,"delta":{"role":null,"content":" +"},"logprobs":null,"finish_reason":""}],"usage":null}

...

data: {"id":"52e707bc1b304714bd4e75ea903e6723","object":"chat.completion.chunk","created":1746681039,"model":"qwen2.5-coder-32b","choices":[{"index":0,"delta":{"role":null,"content":""},"logprobs":null,"finish_reason":"stop"}],"usage":null}

data: [DONE]
```
**不使用流式输出正常，限流有效**

## gateway日志
warning envoy wasm external/envoy/source/extensions/common/wasm/context.cc:1398 wasm log higress-system.ai-statistics-1.0.0: [ai-statistics] [f8afdab6-c5f5-4013-9f3e-8854eddad59a] get usage information failed, skip metric record   thread=585

## AI 统计配置
```
attributes:
- apply_to_log: true
  key: "question"
  value: "messages.@reverse.0.content"
  value_source: "request_body"
- apply_to_log: true
  key: "answer"
  rule: "append"
  value: "choices.0.delta.content"
  value_source: "response_streaming_body"
- apply_to_log: true
  key: "answer"
  value: "choices.0.message.content"
  value_source: "response_body"
```
