### ISSUE TITLE
集群限流插件是否可以针对整个路由设置限流阈值，不需要设置条件 || Is the cluster current limiting plug-in set a current limiting threshold for the entire route without setting a condition

### ISSUE THREAD

**Issue by aLIEzu** [alibaba/higress#2251]
目前看文档中似乎必须要设置限流规则才能进行限流，能否对整个路由设置一个限流阈值呢

![Image](https://github.com/user-attachments/assets/106c3e65-955f-46dd-bb9d-723f58ae8068)

---
At present, it seems that the current limiting rules must be set in the document to perform current limiting. Can a current limiting threshold be set for the entire route?

![Image](https://github.com/user-attachments/assets/106c3e65-955f-46dd-bb9d-723f58ae8068)

**Comment by hanxiantao** [comment]
> Can consider supporting this, it is indeed a useful request

Got it. I will start renovating this this week.

**Comment by hanxiantao** [comment]
```yaml
rule_name: "global-route-limit"
show_limit_quota_header: true
rejected_code: 429
rejected_msg: "Global rate limit exceeded"
redis:
  service_name: "redis-cluster.example.com"
  service_port: 6379
  username: "admin"
  password: "******"
# 全局限流配置（与rule_items至少配置一个）
global_threshold:
  query_per_minute: 1000  # 整个路由每分钟最多1000次请求
# 条件限流规则（与global_threshold至少配置一个）
rule_items:
  - limit_by_header: "X-User-ID"
    limit_keys:
      - key: "user-001"
        query_per_minute: 100  # 用户001额外限制为100请求/分钟
```
我会新增 global_threshold 配置项，要求该配置与 rule_items 需至少完成其中一项配置。global_threshold 支持按秒、分钟、小时、天维度设置全局限流值。
