### ISSUE TITLE
linux 3.10内核安装 higress-gateway 报错

### ISSUE THREAD

**Issue by ShadowNight001** [alibaba/higress#226]
通过官网helm方式安装
安装时候 higress-gateway pod 报错
环境信息：
Linux version 3.10.0-1160.71.1.el7.x86_64
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:09:57Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
以下是报错信息：

Failed to create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "higress-gateway-59587585f7-blcpn": Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: open /proc/sys/net/ipv4/ip_unprivileged_port_start: no such file or directory: unknown

请问这个问题如何解决呢，

**Comment by CH3CHO** [comment]
请问是本地安装吗？本地的 K8s 集群是如何搭建的？是安装的本地测试版本还是生产版本呢？

**Comment by ShadowNight001** [comment]
@CH3CHO 本地环境  通过 yum 安装的 1.23.0版本的 k8s 集群

**Comment by johnlanni** [comment]
看上去像是K8s安装的不正确，本地环境建议用kind模式

**Comment by ShadowNight001** [comment]
> 

我发现了这个 [#97](https://github.com/alibaba/higress/issues/97)，好像说是内核版本引起的 但是没有找到解决方法

**Comment by johnlanni** [comment]
securityContext 改成 runAsRoot: true  试试

**Comment by johnlanni** [comment]
@iutx 可以帮忙在安装文档和README中介绍下低内核版本需要做的调整么

**Comment by ShadowNight001** [comment]
> securityContext 改成 runAsRoot: true 试试

还是不行 我将 securityContext  替换为  runAsRoot: true，依然报相同的错误

**Comment by iutx** [comment]
> @iutx 可以帮忙在安装文档和README中介绍下低内核版本需要做的调整么

好的。我看一下低内核下如何配置

**Comment by iutx** [comment]
@ShadowNight001 可以提供一下 helm 部署的命令以及 values 吗

**Comment by ShadowNight001** [comment]
> 
直接使用的 helm install higress -n higress-system  oci://higress-registry.cn-hangzhou.cr.aliyuncs.com/charts/higress

**Comment by ShadowNight001** [comment]
> @ShadowNight001 可以提供一下 helm 部署的命令以及 values 吗

helm install higress -n higress-system  oci://higress-registry.cn-hangzhou.cr.aliyuncs.com/charts/higress

**Comment by iutx** [comment]
@ShadowNight001 在 3.10 内核 >=1.22 版本的 k8s 下请尝试使用如下 values 安装

```yaml
gateway:
  securityContext:
    sysctls: ~
  containerSecurityContext:
    capabilities:
      drop:
      - ALL
      add:
      - NET_BIND_SERVICE
    runAsUser: 0
    runAsGroup: 1337
    runAsNonRoot: false
    allowPrivilegeEscalation: true
    readOnlyRootFilesystem: true
```

该配置会以特权运行，为了安全考虑，建议
1. 升级内核至 >=4.11 版本.
2. 或者在 3.10 版本内核中使用 < 1.22 版本的 Kubernetes.
