### ISSUE TITLE
Wrong behavior when decode tls using wildcard ingress

### ISSUE THREAD

**Issue by zzjin** [alibaba/higress#2270]
### Ⅰ. Issue Description
When setting one wildcard ingress with wildcard cert, and one ingress without TLS. Stream can send using `https` but not work using `wss`

### Ⅱ. Describe what happened

We want to use one ingress to offload TLS traffic, but when there are too many tls into ingress, higress become slow.

So access "http://cumeyivcmxky.192.168.10.227.nip.io" and "https://cumeyivcmxky.192.168.10.227.nip.io" works fine.

But cannot access "wss://cumeyivcmxky.192.168.10.227.nip.io"

### Ⅲ. Describe what you expected to happen

All works fine.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. one user svc and ingress
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: network-hfskybwbuxjp
  namespace: ns-admin
spec:
  rules:
    - host: cumeyivcmxky.192.168.10.227.nip.io
      http:
        paths:
          - backend:
              service:
                name: echo-server
                port:
                  number: 8080
            path: /
            pathType: Prefix

---
apiVersion: v1
kind: Service
metadata:
  name: echo-server
  namespace: ns-admin
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: echo-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  namespace: ns-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      automountServiceAccountToken: false
      containers:
        - image: jmalloc/echo-server
          imagePullPolicy: Always
          name: echo-server
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 200m
              memory: 128Mi
      restartPolicy: Always

```
2. one wildcard ingress to offload TLS traffic
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wildcard-ingress
  namespace: higress-system
spec:
  rules:
  - host: "*.192.168.10.227.nip.io"
    http:
      paths:
      - backend:
          service:
            name: higress-gateway
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - "*.192.168.10.227.nip.io"
    secretName: wildcard-cert
  ingressClassName: nginx
```
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: higress
    meta.helm.sh/release-namespace: higress-system
  labels:
    app: higress-gateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: higress-gateway
    app.kubernetes.io/version: 2.0.0
    helm.sh/chart: higress-core-2.0.0
    higress: higress-system-higress-gateway
  name: higress-gateway
  namespace: higress-system
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http2
      nodePort: 32526
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      nodePort: 30756
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: higress-gateway
    higress: higress-system-higress-gateway
  sessionAffinity: None
  type: NodePort

```

### Ⅴ. Anything else we need to know?
When access from wss, higress logs:
```json
{
  "authority": "cumeyivcmxky.192.168.10.227.nip.io",
  "bytes_received": "0",
  "bytes_sent": "95",
  "downstream_local_address": "192.168.10.227:443",
  "downstream_remote_address": "192.168.0.111:51902",
  "duration": "1001",
  "istio_policy_status": "-",
  "method": "GET",
  "path": "/",
  "protocol": "HTTP/1.1",
  "request_id": "2ab55f6d-32c5-4a7c-829e-d612a17a1458",
  "requested_server_name": "cumeyivcmxky.192.168.10.227.nip.io",
  "response_code": "503",
  "response_flags": "UC",
  "route_name": "wildcard-ingress",
  "start_time": "2025-05-19T09:28:49.291Z",
  "trace_id": "-",
  "upstream_cluster": "outbound|80||higress-gateway.higress-system.svc.cluster.local",
  "upstream_host": "192.168.10.227:80",
  "upstream_local_address": "192.168.10.227:35334",
  "upstream_service_time": "-",
  "upstream_transport_failure_reason": "-",
  "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36",
  "x_forwarded_for": "192.168.0.111",
  "response_code_details": "upstream_reset_before_response_started{connection_termination}",
}

```

when assess from ws, higress logs:
```json
{
  "authority": "cumeyivcmxky.192.168.10.227.nip.io",
  "bytes_received": "97",
  "bytes_sent": "113",
  "downstream_local_address": "192.168.10.227:80",
  "downstream_remote_address": "192.168.0.111:41396",
  "duration": "12342",
  "istio_policy_status": "-",
  "method": "GET",
  "path": "/",
  "protocol": "HTTP/1.1",
  "request_id": "1374f271-5fac-45d1-8085-6f5da04f06d1",
  "requested_server_name": "-",
  "response_code": "101",
  "response_flags": "UC",
  "route_name": "ns-admin/network-hfskybwbuxjp",
  "start_time": "2025-05-19T09:31:09.357Z",
  "trace_id": "-",
  "upstream_cluster": "outbound|8080||echo-server.ns-admin.svc.cluster.local",
  "upstream_host": "100.64.0.95:8080",
  "upstream_local_address": "100.64.0.237:36892",
  "upstream_service_time": "-",
  "upstream_transport_failure_reason": "-",
  "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36 Edg/138.0.0.0",
  "x_forwarded_for": "192.168.0.111",
  "response_code_details": "upstream_reset_after_response_started{connection_termination}",
}


```

### Ⅵ. Environment:

- Higress version:  latest
