### ISSUE TITLE
HEP: add support for hgctl cmd

### ISSUE THREAD

**Issue by Xunzhuo** [alibaba/higress#229]
## Why do you need it?

Add command line called `hgctl`, provides abilities for API Gateway operators to manage/debug/analyze higress control plane and data plane.

Some init commands for `hgctl`:
+ install
+ uninstall
+ manifests
+ upgrade
+ validate
+ config
+ analyze
+ version
+ status
+ help
+ .....

**Comment by Xunzhuo** [comment]
Thanks @xcbeyond, but there are some pre-tasks I am working on. I will separate this issue into sub-tasks to be assignable.

**Comment by xcbeyond** [comment]
> Thanks @xcbeyond, but there are some pre-tasks I am working on. I will separate this issue into sub-tasks to be assignable.

@Xunzhuo  ok, I'll pick up the assignment after we break it down

**Comment by CH3CHO** [comment]
After discussing with @johnlanni , we think it would be better to add a `hgctl ui` command to perform port-forward operation on 8080 port of Higress Console and open the console page directly, so user doesn't need to worry about Higress Console being blocked by some incorrect configurations on the Gateway itself, since the Ingress route of Higress Console is also served by the said gateway.

**Comment by Xunzhuo** [comment]
@CH3CHO LGFM, similar to `istioctl dashboard`

**Comment by CH3CHO** [comment]
> @CH3CHO LGFM, similar to `istioctl dashboard`

Then should I create a separate issue for this sub-command?

**Comment by 2456868764** [comment]
hgctl install demo 如下
1.  本地 kind 环境安装 
```
hgclt install --set profile=kind --set global.install=local --set global.enableIstioAPI=true --set gateway.replicas=2  --set console. o11y.enabled=true
```

2. 本地 docker 环境安装

```
hgclt install --set profile=kind --set global.install=docker   --set nacos.url=nacos://192.168.0.1:8848 --set console.admin.password.value=admin
```


关于 hgctl install 具体配置元数据 yaml 结构如下：


```
profile: kind
global:
  install: local # install mode k8s/local/docker
  ingressClass: higress
  watchNamespace:
  disableAlpnH2: true
  enableStatus: true
  enableIstioAPI: false
  namespace: higress-system

console:
  port: 8080
  replicas: 1
  service:
    type: ClusterIP
  domain: console.higress.io
  tlsSecretName:
  web:
    login:
      prompt:
  admin:
    password:
      value: admin
  o11y:
    enabled: false
  pvc:
    rwxSupported: true

gateway:
  replicas: 1
  httpPort: 80
  httpsPort: 443
  metricsPort: 15020

controller:
  replicas: 1

nacos:
  useBuiltin: false
  port: 8848
  url: nacos://192.168.0.1:8848 #  file://opt/higress/conf
  ns: higress-system
  username:
  password:
  dataEncKey:

# values passed through to helm
values:

charts:
  higress:
    chartUrl: https://higress.io/helm-charts
    chartName: higress
    chartVersion: 1.1.1
  istio:
    chartUrl: https://istio-release.storage.googleapis.com/charts
    chartName: base
    chartVersion: 1.18.2

```

**Comment by johnlanni** [comment]
@2456868764 
有两个问题：
1. 本地K8s环境，kind 是否用 local-k8s 更合理，本地docker环境，kind用 local-docker，未来我们还会提供纯 local 的方式，直接基于binary部署；另外是否这个kind可以无需指定，而是根据当前是否有 kubectl 命令，以及docker命令来自动选择。
2. nacos 是local-docker/local模式下的配置来源，配置url所属的第一配置层级不应该是nacos，应该是configure，是通过配置的url里的协议头部分决定了是走nacos：`nacos://`

**Comment by johnlanni** [comment]
请 @CH3CHO  一起看下这块

**Comment by 2456868764** [comment]
> @2456868764 有两个问题：
> 
> 1. 本地K8s环境，kind 是否用 local-k8s 更合理，本地docker环境，kind用 local-docker，未来我们还会提供纯 local 的方式，直接基于binary部署；另外是否这个kind可以无需指定，而是根据当前是否有 kubectl 命令，以及docker命令来自动选择。
> 2. nacos 是local-docker/local模式下的配置来源，配置url所属的第一配置层级不应该是nacos，应该是configure，是通过配置的url里的协议头部分决定了是走nacos：`nacos://`

1.  OK， 四种安装方式  k8s, local-k8s, local-docker, local  分别对应 K8s环境， 本地K8s环境， 本地docker环境， 和 供纯 local ，同时提供不同方式安装默认profile, 用户可以指定profile 就可以安装。 但是用户环境比较复杂，比如同时有 kubectl和docker等，安装方式 profile 还是让用户明确来指定
2.   关于 nacos 这块整体配置， 这块我理解是非K8环境安装后端存储配置内容。目前支持三种方式，用户指定nacos, buildin nacos, 和文件系统。 可以用URL部分的协议来区分, 可以优化如下配置

```
storage:
  url: nacos://192.168.0.1:8848 #  file://opt/higress/conf   或者  buildin://127.0.0.1:8848
  ns: higress-system
  username:
  password:
  dataEncKey:
```
