### ISSUE TITLE
外接监控面板时 ai_consumer的所有标签变成none

### ISSUE THREAD

**Issue by Kevin-qwx** [alibaba/higress#2314]
部署方式：
```bash
helm install higress -n higress-system higress.io/higress --create-namespace --render-subchart-notes --set global.enableRedis=true
```
监控面板是外接的gpu-operator  创建了一个PodMonitor资源  资源配置如下
```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: higress-gateway
  namespace: higress-system
spec:
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - port: istio-prom
      path: /stats/prometheus
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: "true"

        - sourceLabels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          targetLabel: __metrics_path__
          regex: (.+)

        - sourceLabels:
            - __address__
            - __meta_kubernetes_pod_annotation_prometheus_io_port
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          targetLabel: __address__

        - regex: __meta_kubernetes_pod_label_(.+)
          action: labelmap

        - sourceLabels: [__meta_kubernetes_namespace]
          action: replace
          targetLabel: kubernetes_namespace

        - sourceLabels: [__meta_kubernetes_pod_name]
          action: replace
          targetLabel: kubernetes_pod_name
  selector:
    matchLabels:
      app: higress-gateway
```

之后在grafana-dashborad 中Higress AI Gateway Dashboard面板Consumer Usage 发现所有Consumer 皆为none ，我检查了我的配置文件然后curl gateway IP:15020/stats/prometheus | grep ai_consumer  返回的指标数据全部都是none 无奈来请教下 官方是我的配置文件有问题吗？ 还是我对接的不对

![Image](https://github.com/user-attachments/assets/552574f5-930d-43ac-b8ae-1028cfaaf9c8)
