### ISSUE TITLE
请求响应转换，只有replace操作生效，其他add，remove等未生效

### ISSUE THREAD

**Issue by nuclearwu** [alibaba/higress#2328]
请求响应转换，只有replace操作生效，其他add，remove等未生效

**Comment by johnlanni** [comment]
transform 插件吗？

**Comment by johnlanni** [comment]
麻烦发一下能复现问题的完整配置

**Comment by johnlanni** [comment]
https://github.com/alibaba/higress/blob/main/test/e2e/conformance/tests/go-wasm-transformer.yaml


这个e2e集成测试里应该覆盖了这种情况的

**Comment by CH3CHO** [comment]
cc @johnlanni @Uncle-Justice

**Comment by johnlanni** [comment]
cc @WeixinX 

---
Cao Cao @WeiX

**Comment by WeixinX** [comment]
@nuclearwu hello，配置格式书写错误哈

首先是 key 和 value 是一个键值对，不需要都有 "-" 符号

其次 replace 操作语义是将 key 对应的 value 值替换为 newValue，所以为配置字段 "newValue" 而不是 "value"

最后 ”operation“ 字段应该为 "operate"

```yaml
reqRules:
- headers:
  - key: "content-type"
  - value: "application/json" # <-- 多余的 "-"，应为 newValue
  operate: "replace"
- headers:
  - key: name
  - value: johnjan # <-- 多余的 "-"
  operation: add  # <-- 应为 operate
respRules:
- body:
  - key: "data.foo"
    value: "bar"
  operation: "add" # <-- 应为 operate
```

因此正确的配置为：

```yaml
reqRules:
- operate: replace
  headers:
  - key: content-type
    newValue: application/json
- operate: add
  headers:
  - key: name
    value: johnjan
respRules:
- operate: add
  body:
  - key: data.foo
    value: bar


```

测试结果如下：

![Image](https://github.com/user-attachments/assets/baf6346f-0e28-4f0a-a761-ddef1476cb23)

[文档](https://higress.cn/docs/latest/plugins/transformation/transformer/?spm=36971b57.2ef5001f.0.0.2a932c1fWCMnmH#%E9%85%8D%E7%BD%AE%E7%A4%BA%E4%BE%8B)中有许多用例麻烦参考





---
@nuclearwu hello, configuration format is wrong

First of all, key and value are a key-value pair, and there is no need to have a "-" symbol.

Secondly, the replace operation semantics is to replace the value corresponding to the key with newValue, so the configuration field "newValue" instead of "value"

Finally, the "operation" field should be "operate"

```yaml
reqRules:
- headers:
  - key: "content-type"
  - value: "application/json" # <-- The extra "-" should be newValue
  operate: "replace"
- headers:
  - key: name
  - value: johnjan # <-- Redundant "-"
  operation: add # <-- should be operated
respRules:
- body:
  - key: "data.foo"
    value: "bar"
  operation: "add" # <-- Should be operated
```

Therefore the correct configuration is:

```yaml
reqRules:
- operate: replace
  headers:
  - key: content-type
    newValue: application/json
- operate: add
  headers:
  - key: name
    value: johnjan
respRules:
- operate: add
  body:
  - key: data.foo
    value: bar


```

The test results are as follows:

![Image](https://github.com/user-attachments/assets/baf6346f-0e28-4f0a-a761-ddef1476cb23)

There are many use cases in [Document](https://higress.cn/docs/latest/plugins/transformation/transformer/?spm=36971b57.2ef5001f.0.0.2a932c1fWCMnmH#%E9%85%8D%E7%BD%AE%E7%A4%BA%E4%BE%8B) There are many troublesome references
