### ISSUE TITLE
ai-statistics 采集指标异常 || ai-statistics Acquisition indicator abnormality

### ISSUE THREAD

**Issue by zjun-sudo** [alibaba/higress#2335]
## Why do you need it?

- 开启流式响应后，ai-statistics 采集不到 input_token、output_token等值

1. 未开启流式访问，ai-log值
![Image](https://github.com/user-attachments/assets/e6d2952a-ab2f-435f-ba03-e2f35c669ce7)

2. 开启流式访问，ai-log 值

![Image](https://github.com/user-attachments/assets/d04e235c-be36-49a9-8efd-4f0cf58fcd14)

## Other related information
1. 流式请求访问

![Image](https://github.com/user-attachments/assets/29afc24b-55c5-4ef2-bb92-86eb214b7185)
 2. 非流式请求访问

![Image](https://github.com/user-attachments/assets/6291ac53-884d-4e29-89a1-344ed737d600)
3. 插件配置
```yaml 
    attributes:
      - apply_to_log: true
        apply_to_span: true
        key: model
        value: model
        value_source: response_body
      - apply_to_log: true
        apply_to_span: true
        key: input_token
        value: usage.prompt_tokens
        value_source: response_body
      - apply_to_log: true
        apply_to_span: true
        key: output_token
        value: usage.completion_tokens
        value_source: response_body
      - apply_to_log: true
        key: question
        value: messages.@reverse.0.content
        value_source: request_body
      - apply_to_log: true
        key: answer
        rule: append
        value: choices.0.delta.content
        value_source: response_streaming_body
      - apply_to_log: true
        key: consumer
        value: x-mse-consumer
        value_source: request_header
```

---
## Why do you need it?

- After turning on streaming response, ai-statistics cannot collect input_token, output_token and other values

1. Streaming access is not enabled, ai-log value
![Image](https://github.com/user-attachments/assets/e6d2952a-ab2f-435f-ba03-e2f35c669ce7)

2. Turn on streaming access, ai-log value

![Image](https://github.com/user-attachments/assets/d04e235c-be36-49a9-8efd-4f0cf58fcd14)

## Other related information
1. Streaming request access

![Image](https://github.com/user-attachments/assets/29afc24b-55c5-4ef2-bb92-86eb214b7185)
 2. Non-streaming request access

![Image](https://github.com/user-attachments/assets/6291ac53-884d-4e29-89a1-344ed737d600)
3. Plug-in configuration
```yaml
    attributes:
      - apply_to_log: true
        apply_to_span: true
        key: model
        value: model
        value_source: response_body
      - apply_to_log: true
        apply_to_span: true
        key: input_token
        value: usage.prompt_tokens
        value_source: response_body
      - apply_to_log: true
        apply_to_span: true
        key: output_token
        value: usage.completion_tokens
        value_source: response_body
      - apply_to_log: true
        key: question
        value: messages.@reverse.0.content
        value_source: request_body
      - apply_to_log: true
        key: answer
        rule: append
        value: choices.0.delta.content
        value_source: response_streaming_body
      - apply_to_log: true
        key: consumer
        value: x-mse-consumer
        value_source: request_header
```
