### ISSUE TITLE
[ai-proxy] 希望能将 provider 的 capabilities 配置化 || [ai-proxy] Hope to configure the capabilities of the provider

### ISSUE THREAD

**Issue by daixijun** [alibaba/higress#2345]
## Why do you need it?
 Is your feature request related to a problem? Please describe in details

现在有不少的 provider 是提供了 openai 协议兼容的接口， 但如果需要使用的话得要在代码里面声明已支持的能力， 我希望是将这块可以配置化，这样就不需要在支持特定接口能力的时候还需要修改对应 provider 的代码。

https://github.com/alibaba/higress/blob/69b755a10d4ceacd271de95873d6bf5cf3429afe/plugins/wasm-go/extensions/ai-proxy/provider/provider.go#L301

希望的配置方式如下:

```yaml
    - id: xai
      type: openai
      openaiCustomUrl: api.x.ai/v1
      capabilities:
        openai/v1/chatcompletions: /v1/chat/completions
        openai/v1/imagegeneration: /v1/images/generations
```

## How could it be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

## Other related information

---
## Why do you need it?
 Is your feature request related to a problem? Please describe in details

Nowadays, many providers provide interfaces that are compatible with the openai protocol, but if you need to use it, you must declare the supported capabilities in the code. I hope this can be configured so that there is no need to modify the corresponding provider's code when supporting specific interface capabilities.

https://github.com/alibaba/higress/blob/69b755a10d4ceacd271de95873d6bf5cf3429afe/plugins/wasm-go/extensions/ai-proxy/provider/provider.go#L301

The desired configuration method is as follows:

```yaml
    - id: xai
      type: openai
      openaiCustomUrl: api.x.ai/v1
      capabilities:
        openai/v1/chatcompletions: /v1/chat/completeions
        openai/v1/imagegeneration: /v1/images/generations
```

## How could it be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.
