### ISSUE TITLE
higress 如何配置默认ssl 证书

### ISSUE THREAD

**Issue by vvlisn** [alibaba/higress#2377]
## 创建了Higress TLS 的全局配置 ConfigMap 对象 higress-https
```
apiVersion: v1
data:
  cert: |
    automaticHttps: false
    credentialConfig:
      - tlsSecret: yunxiao-tls
        domains:
          - xxxx.net
          - xxxx.net
    fallbackForInvalidSecret: true
    renewBeforeDays: 30
    version: "20241217091416"
kind: ConfigMap
metadata:
  name: higress-https
  namespace: higress-system

```
configmap 没有被服务挂载，如何确定配置生效了
