### ISSUE TITLE
配置全局的 TLS 后，ingress 对象还需要指定 tls 配置吗 || After configuring global TLS, do the ingress object still need to specify the tls configuration?

### ISSUE THREAD

**Issue by vvlisn** [alibaba/higress#2383]
## 配置全局的 TLS 后，ingress 对象还需要指定 tls 配置吗

---

**Comment by johnlanni** [comment]
请完善你的issue说明，具体是配了什么配置，预期是什么效果

---
Please improve your issue description, what configuration is installed and what expected effect

**Comment by vvlisn** [comment]
配置全局tls configmap 配置如下
``` yaml
apiVersion: v1
data:
  cert: |
    automaticHttps: false
    credentialConfig:
      - domains: ["*"]
        tlsSecret: yunxiao-tls
    fallbackForInvalidSecret: true
kind: ConfigMap
metadata:
  name: higress-https
  namespace: higress-system
```
开启了全局的tls 网关不应该默认监听 443 端口吗？创建ingress 对象还需要指定tls 配置项，才能正常使用https请求。如果ingress 不配置tls, 不能使用默认的tls

**Comment by vvlisn** [comment]
期望的状态，在 Ingress 资源中​​无需​​配置 spec.tls 字段：
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
spec:
  rules:
    - host: app.example.com
      http:
        paths:
          - path: /
            backend:
              service:
                name: app-service
                port: 80
```
​​效果​​：访问 https://app.example.com 时自动使用 default-cert 证书加密流量

---
The expected state does not require configuring the spec.tls field in the Ingress resource:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
spec:
  Rules:
    - host: app.example.com
      http:
        paths:
          - path: /
            backend:
              service:
                name: app-service
                port: 80
```
Effects: Automatically use the default-cert certificate to encrypt traffic when accessing https://app.example.com
