### ISSUE TITLE
nginx ingress 默认监听了 80 和 443 端口，ingress 全局配置 force-ssl-redirect，将http 重定向到 https。higress 是否有相关配置

### ISSUE THREAD

**Issue by vvlisn** [alibaba/higress#2386]
## nginx ingress 默认监听了 80 和 443 端口，ingress 全局配置 force-ssl-redirect，将http 重定向到 https。higress 是否有相关配置呢
使用higress 创建 ingress 配置
``` yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: higress-console
    meta.helm.sh/release-namespace: higress-system
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: higress-console
  namespace: higress-system
spec:
  ingressClassName: higress
  rules:
  - host: yunxiao.xxx.net
    http:
      paths:
      - backend:
          service:
            name: nginx
            port:
              number: 80
        path: /
        pathType: Prefix
```
```
curl -sSI -H "Host: yunxiao.xxx.net" http://10.254.5.141/healthz
HTTP/1.1 200 OK
cache-control: no-store
x-content-type-options: nosniff
x-frame-options: deny
x-xss-protection: 1; mode=block
date: Tue, 10 Jun 2025 03:22:33 GMT
req-cost-time: 1
req-arrive-time: 1749525736035
resp-start-time: 1749525736036
x-envoy-upstream-service-time: 1
server: istio-envoy
transfer-encoding: chunked
```
这里没有发生重定向，配置了 nginx.ingress.kubernetes.io/force-ssl-redirect: "true" 不是应该返回 308 吗
