### ISSUE TITLE
feat: plugin server 支持 k8s 一键部署并配置插件默认下载的 URL || feat: plugin server supports one-click deployment of k8s and configures the URL of the plug-in download by default

### ISSUE THREAD

**Issue by NorthernBob** [alibaba/higress#2390]
# feat: plugin server 支持 k8s 一键部署并配置插件默认下载的 URL
## 关联 issue: 
- #2232 
- #2280 
- #2312
## 关联 PR: 
- [plugin-server#2](https://github.com/higress-group/plugin-server/pull/2)
- [higress#2389](https://github.com/alibaba/higress/pull/2389)
- [higress-console#520](https://github.com/higress-group/higress-console/pull/520)
## 1 效果

1. 用户能够通过一行参数控制 plugin server 组件的安装以及 console 环境变量的配置，以默认使用 plugin server 来下载插件，如图：

![Image](https://github.com/user-attachments/assets/9f649d36-c334-4a75-913c-deb06e3eb772)

   该 feature pr 合并后，部署命令为：

   ```bash
   helm repo add higress.io https://higress.cn/helm-charts
   helm install higress -n higress-system higress.io/higress --create-namespace --set global.enablePluginServer=true --render-subchart-notes
   ```

2. 执行完以上命令后，查看部署的组件，可以看到 plugin server 已经被部署：

![Image](https://github.com/user-attachments/assets/badbb30b-8513-4bea-b96c-f393801fc3c3)

3. 进入 higress console 查看插件默认下载 URL，已默认从 plugin server 下载：

![Image](https://github.com/user-attachments/assets/4aa6fb61-f4f9-41eb-8d9e-678f67c9fe12)

### 2.1 plugin-server 仓库

PR: [plugin-server#2](https://github.com/higress-group/plugin-server/pull/2)

为了能够自动构建 plugin-server 的镜像并推送 higress 杭州公开仓库，在 plugin-server 的仓库中添加了 GitHub Action，参考了 higress 主仓库中 CI 的写法，具体代码如下：

```yml
# plugin-server/.github/workflows/build-plugin-server-image-and-push.yml
name: Build Plugin Server Image and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-plugin-server-image:
      runs-on: ubuntu-latest
      environment:
        name: image-registry-plugin-server
      env:
        PLUGIN_SERVER_IMAGE_REGISTRY: ${{ vars.IMAGE_REGISTRY || 'higress-registry.cn-hangzhou.cr.aliyuncs.com' }}
        PLUGIN_SERVER_IMAGE_NAME: ${{ vars.PLUGIN_SERVER_IMAGE_NAME || 'higress/plugin-server' }}
      steps:
        - name: "Checkout ${{ github.ref }}"
          uses: actions/checkout@v4
          with:
            fetch-depth: 1
  
        - name: Free Up GitHub Actions Ubuntu Runner Disk Space 🔧
          uses: jlumbroso/free-disk-space@main
          with:
            tool-cache: false
            android: true
            dotnet: true
            haskell: true
            large-packages: true
            swap-storage: true
  
        - name: Calculate Docker metadata
          id: docker-meta
          uses: docker/metadata-action@v5
          with:
            images: |
              ${{ env.PLUGIN_SERVER_IMAGE_REGISTRY }}/${{ env.PLUGIN_SERVER_IMAGE_NAME }}
            tags: |
              type=raw,value=1.0.0
  
        - name: Set up Docker Buildx (with docker-container driver)
          uses: docker/setup-buildx-action@v3
          with:
            driver: docker-container
            install: true
            use: true

        - name: Login to Docker Registry
          uses: docker/login-action@v3
          with:
            registry: ${{ env.PLUGIN_SERVER_IMAGE_REGISTRY }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
  
        - name: Build Docker Image and Push
          run: |
            docker buildx build \
                --platform linux/amd64,linux/arm64 \
                -t ${{ steps.docker-meta.outputs.tags }} \
                -f Dockerfile \
                --push \
                .
```

### 2.2 higress 主仓库

PR: [higress#2389](https://github.com/alibaba/higress/pull/2389)

#### 2.2.1 添加 helm chart template

将 plugin server 的 helm chart 编排进了 higress-core 的 chart 里，新增两个 template，具体如下：

```yaml
# higress/helm/core/templates/plugin-server-deployment.yaml
{{- if .Values.global.enablePluginServer }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pluginServer.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.pluginServer.replicas }}
  selector:
    matchLabels:
      {{- include "pluginServer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- with .Values.pluginServer.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "pluginServer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.pluginServer.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.pluginServer.hub | default .Values.global.hub }}/{{ .Values.pluginServer.image | default "plugin-server" }}:{{ .Values.pluginServer.tag | default "1.0.0" }}
          {{- if .Values.global.imagePullPolicy }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          {{- end }}
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: {{ .Values.pluginServer.resources.requests.cpu }}
              memory: {{ .Values.pluginServer.resources.requests.memory }}
            limits:
              cpu: {{ .Values.pluginServer.resources.limits.cpu }}
              memory: {{ .Values.pluginServer.resources.limits.memory }}
{{- end }}
```

```yaml
# higress/helm/core/templates/plugin-server-service.yaml
{{- if .Values.global.enablePluginServer }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pluginServer.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pluginServer.labels" . | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.pluginServer.service.port }}
      targetPort: 8080
  selector:
    {{- include "pluginServer.selectorLabels" . | nindent 4 }}
{{- end }}
```

#### 2.2.2 修改 values.yaml 和 _helpers.tpl

对 values.yaml 和 _helpers.tpl 两个文件做了对应修改，方便用户调节 plugin server 的配置，具体如下：

```yaml
# higress/helm/core/values.yaml
...
global:
  enablePluginServer: false
...
pluginServer:
  name: "higress-plugin-server"
  # -- Number of Higress Plugin Server pods, 2 recommended for high availability
  replicas: 2
  image: plugin-server

  hub: higress-registry.cn-hangzhou.cr.aliyuncs.com/higress
  tag: ""

  imagePullSecrets: []

  labels: {}
  # -- Labels to apply to the pod
  podLabels: {}

  #  Plugin-server Service configuration
  service:
    port: 80                    # Container target port (usually fixed)

  resources:
    requests:
      cpu: 200m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
```

```yaml
# higress/helm/core/templates/_helpers.tpl
{{- define "pluginServer.name" -}}
{{- .Values.pluginServer.name | default "higress-plugin-server" -}}
{{- end }}

{{- define "pluginServer.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{- define "pluginServer.labels" -}}
helm.sh/chart: {{ include "pluginServer.chart" . }}
{{ include "pluginServer.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
app.kubernetes.io/name: {{ include "pluginServer.name" . }}
{{- end }}

{{- define "pluginServer.selectorLabels" -}}
{{- if hasKey .Values.pluginServer.labels "app" }}
{{- with .Values.pluginServer.labels.app }}app: {{.|quote}}
{{- end}}
{{- else }}app: {{ include "pluginServer.name" . }}
{{- end }}
{{- if hasKey .Values.pluginServer.labels "higress" }}
{{- with .Values.pluginServer.labels.higress }}
higress: {{.|quote}}
{{- end}}
{{- else }}
higress: {{ include "pluginServer.name" . }}
{{- end }}
{{- end }}
```

### 2.3 higress-console 仓库

PR: [higress-console#520](https://github.com/higress-group/higress-console/pull/520)

修改该仓库的目的是，用户选择配置 plugin server(.Values.global.enablePluginServer = true) 时，会自动更改默认的插件下载 URL，考虑到兼容性，当用户配置启用 plugin server 时，如果还配置了插件下载 URL，应优先使用户的配置生效，故在配置环境变量时加了个判断，如果用户已有配置则优先生效，具体代码如下：

```yaml
# higress-console/helm/templates/deployment.yaml
...
spec:
  template:
    containers:
      env:
        {{- if and .Values.global.enablePluginServer (not (hasKey .Values.podEnvs "HIGRESS_ADMIN_WASM_PLUGIN_CUSTOM_IMAGE_URL_PATTERN"))}}
        - name: HIGRESS_ADMIN_WASM_PLUGIN_CUSTOM_IMAGE_URL_PATTERN
          value: "{{ .Values.pluginServer.UrlPattern }}"
        {{- end }}

```

```yaml
# higress-console/helm/values.yaml
...
pluginServer:
  UrlPattern: "http://higress-plugin-server.higress-system.svc/plugins/${name}/${version}/plugin.wasm"
```

---
# feat: plugin server supports k8s one-click deployment and configure the URL of the plugin download by default
## Related issue:
- #2232
- #2280
- #2312
## Related PR:
- [plugin-server#2](https://github.com/higress-group/plugin-server/pull/2)
- [higress#2389](https://github.com/alibaba/higress/pull/2389)
- [higress-console#520](https://github.com/higress-group/higress-console/pull/520)
## 1 Effect

1. Users can control the installation of plugin server components and the configuration of console environment variables through a line of parameters, and use plugin server by default to download plugins, as shown in the figure:

![Image](https://github.com/user-attachments/assets/9f649d36-c334-4a75-913c-deb06e3eb772)

   After the feature pr is merged, the deployment command is:

   ```bash
   helm repo add higress.io https://higress.cn/helm-charts
   helm install higress -n higress-system higress.io/higress --create-namespace --set global.enablePluginServer=true --render-subchart-notes
   ```

2. After executing the above commands, check the deployed components and you can see that the plugin server has been deployed:

![Image](https://github.com/user-attachments/assets/badbb30b-8513-4bea-b96c-f393801fc3c3)

3. Enter the higress console to view the default download URL of the plugin, which has been downloaded from the plugin server by default:

![Image](https://github.com/user-attachments/assets/4aa6fb61-f4f9-41eb-8d9e-678f67c9fe12)

### 2.1 plugin-server repository

PR: [plugin-server#2](https://github.com/higress-group/plugin-server/pull/2)

In order to automatically build a plugin-server image and push the higress public repository in Hangzhou, GitHub Action was added to the plugin-server repository, referring to the CI writing method in the higress main repository. The specific code is as follows:

```yml
# plugin-server/.github/workflows/build-plugin-server-image-and-push.yml
name: Build Plugin Server Image and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-plugin-server-image:
      runs-on: ubuntu-latest
      environment:
        name: image-registry-plugin-server
      env:
        PLUGIN_SERVER_IMAGE_REGISTRY: ${{ vars.IMAGE_REGISTRY || 'higress-registry.cn-hangzhou.cr.aliyuncs.com' }}
        PLUGIN_SERVER_IMAGE_NAME: ${{ vars.PLUGIN_SERVER_IMAGE_NAME || 'higress/plugin-server' }}
      Steps:
        - name: "Checkout ${{ github.ref }}"
          uses: actions/checkout@v4
          with:
            fetch-depth: 1
  
        - name: Free Up GitHub Actions Ubuntu Runner Disk Space 🔧
          uses: jlumbroso/free-disk-space@main
          with:
            tool-cache: false
            android: true
            dotnet: true
            haskell: true
            large-packages: true
            swap-storage: true
  
        - name: Calculate Docker metadata
          id: docker-meta
          uses: docker/metadata-action@v5
          with:
            images: |
              ${{ env.PLUGIN_SERVER_IMAGE_REGISTRY }}/${{ env.PLUGIN_SERVER_IMAGE_NAME }}
            tags: |
              type=raw,value=1.0.0
  
        - name: Set up Docker Buildx (with docker-container driver)
          uses: docker/setup-buildx-action@v3
          with:
            driver: docker-container
            install: true
            use: true

        - name: Login to Docker Registry
          uses: docker/login-action@v3
          with:
            registry: ${{ env.PLUGIN_SERVER_IMAGE_REGISTRY }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
  
        - name: Build Docker Image and Push
          run: |
            docker buildx build \
                --platform linux/amd64,linux/arm64\
                -t ${{ steps.docker-meta.outputs.tags }} \
                -f Dockerfile \
                --push \
                .
```

### 2.2 higress main warehouse

PR: [higress#2389](https://github.com/alibaba/higress/pull/2389)

#### 2.2.1 Add helm chart template

The helm chart of plugin server is arranged into the chart of hgress-core, and two new templates are added, as follows:

```yaml
# hgress/helm/core/templates/plugin-server-deployment.yaml
{{- if .Values.global.enablePluginServer }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pluginServer.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.pluginServer.replicas }}
  selector:
    matchLabels:
      {{- include "pluginServer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- with .Values.pluginServer.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "pluginServer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.pluginServer.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.pluginServer.hub | default .Values.global.hub }}/{{ .Values.pluginServer.image | default "plugin-server" }}:{{ .Values.pluginServer.tag | default "1.0.0" }}
          {{- if .Values.global.imagePullPolicy }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          {{- end }}
          Ports:
            - containerPort: 8080
          resources:
            Requests:
              cpu: {{ .Values.pluginServer.resources.requests.cpu }}
              memory: {{ .Values.pluginServer.resources.requests.memory }}
            limits:
              cpu: {{ .Values.pluginServer.resources.limits.cpu }}
              memory: {{ .Values.pluginServer.resources.limits.memory }}
{{- end }}
```

```yaml
# hgress/helm/core/templates/plugin-server-service.yaml
{{- if .Values.global.enablePluginServer }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pluginServer.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pluginServer.labels" . | nindent 4 }}
spec:
  Ports:
    - protocol: TCP
      port: {{ .Values.pluginServer.service.port }}
      targetPort: 8080
  selector:
    {{- include "pluginServer.selectorLabels" . | nindent 4 }}
{{- end }}
```

#### 2.2.2 Modify values.yaml and _helpers.tpl

The corresponding modifications have been made to the values.yaml and _helpers.tpl files to facilitate users to adjust the configuration of the plugin server. The details are as follows:

```yaml
# hgress/helm/core/values.yaml
...
global:
  enablePluginServer: false
...
pluginServer:
  name: "higress-plugin-server"
  # -- Number of Higress Plugin Server pods, 2 recommended for high availability
  replicas: 2
  image: plugin-server

  hub: hgress-registry.cn-hangzhou.cr.aliyuncs.com/higress
  tag: ""

  imagePullSecrets: []

  labels: {}
  # -- Labels to apply to the pod
  podLabels: {}

  # Plugin-server Service configuration
  service:
    port: 80 # Container target port (usually fixed)

  resources:
    Requests:
      cpu: 200m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
```

```yaml
# hgress/helm/core/templates/_helpers.tpl
{{- define "pluginServer.name" -}}
{{- .Values.pluginServer.name | default "higress-plugin-server" -}}
{{- end }}

{{- define "pluginServer.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{- define "pluginServer.labels" -}}
helm.sh/chart: {{ include "pluginServer.chart" . }}
{{ include "pluginServer.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
app.kubernetes.io/name: {{ include "pluginServer.name" . }}
{{- end }}

{{- define "pluginServer.selectorLabels" -}}
{{- if hasKey .Values.pluginServer.labels "app" }}
{{- with .Values.pluginServer.labels.app }}app: {{.|quote}}
{{- end}}
{{- else }}app: {{ include "pluginServer.name" . }}
{{- end }}
{{- if hasKey .Values.pluginServer.labels "higress" }}
{{- with .Values.pluginServer.labels.higress }}
higress: {{.|quote}}
{{- end}}
{{- else }}
higress: {{ include "pluginServer.name" . }}
{{- end }}
{{- end }}
```

### 2.3 hgress-console warehouse

PR: [higress-console#520](https://github.com/higress-group/higress-console/pull/520)

The purpose of modifying this repository is that when the user chooses to configure plugin server(.Values.global.enablePluginServer = true), the default plugin download URL will be automatically changed. Considering compatibility, when the user configures to enable plugin server, if the plugin download URL is also configured, the user's configuration should be given priority. Therefore, a judgment is added when configuring the environment variables. If the user already has configuration, it will be effective. The specific code is as follows:

```yaml
# higress-console/helm/templates/deployment.yaml
...
spec:
  template:
    containers:
      env:
        {{- if and .Values.global.enablePluginServer (not (hasKey .Values.podEnvs "HIGRESS_ADMIN_WASM_PLUGIN_CUSTOM_IMAGE_URL_PATTERN"))}}
        - name: HIGRESS_ADMIN_WASM_PLUGIN_CUSTOM_IMAGE_URL_PATTERN
          value: "{{ .Values.pluginServer.UrlPattern }}"
        {{- end }}

```

```yaml
# higress-console/helm/values.yaml
...
pluginServer:
  UrlPattern: "http://higress-plugin-server.higress-system.svc/plugins/${name}/${version}/plugin.wasm"
```
