### ISSUE TITLE
Discussion: extending cluster-key-rate-limit filter

### ISSUE THREAD

**Issue by tmsnan** [alibaba/higress#2455]
## Why do you need it?

Support some useful features

-  Expand the dynamic deduction limit value, which can be based on the request or response header value 

- Add additional matching conditions. Currently only single matching is supported.

- Add quota management. The plugin can dynamically update the limit size through the http interface, and manage the limit more flexibly, similar to the ai-quota plugin

## How could it be?
In order to achieve the above functions, some additional APIs need to be added

**Comment by tmsnan** [comment]
针对 1，自定义限流扣减规则，增加额外字段 `limit_type` `hit_added`
`limit_type` 可选 "request" "response", 默认为 request，针对请求/响应（响应码200）时扣减限流值
`hit_added` 自定义扣减规则，默认扣减 1，配置时，可以通过 header 指定扣减大小

例如
```
rule_name: default_rule
rule_items:
- limit_by_consumer: ''
  limit_keys:
  - key:  "consumerA"
    query_per_day: 7
    limit_type: "request"
    hit_added:
      base: 1
- limit_by_consumer: ''
  limit_keys:
  - key:  "consumerB"
    query_per_day: 11
    limit_type: "response"
    hit_added:
      base: 1
      from_header: "x-consumer-token"
```
以上配置规则为
消费者 A，根据请求数扣减限流值，每次请求扣减 1
消费者 B，根据响应 header 扣减限流值，每次响应码为200时，扣减限流大小为 base * {x-consumer-token}


---
For 1, customize the current limit deduction rule, add additional fields `limit_type` `hit_added`
`limit_type` optional "request" "response", default is request, deducting the current limit value for request/response (response code 200)
`hit_added` custom deduction rule, default deduction 1. When configuring, you can specify the deduction size through the header

For example
```
rule_name: default_rule
rule_items:
- limit_by_consumer: ''
  limit_keys:
  - key: "consumerA"
    query_per_day: 7
    limit_type: "request"
    hit_added:
      base: 1
- limit_by_consumer: ''
  limit_keys:
  - key: "consumerB"
    query_per_day: 11
    limit_type: "response"
    hit_added:
      base: 1
      from_header: "x-consumer-token"
```
The above configuration rules are
Consumer A, deduct the current limit value according to the number of requests, deduct 1 for each request
Consumer B, deduct the current limit value according to the response header. Each time the response code is 200, the deducted current limit size is base * {x-consumer-token}

**Comment by tmsnan** [comment]
针对 2，多 match 条件，当前只支持单一条件匹配，增加字段 `attach_match`
配置 `attach_match`，限流将额外匹配该条件，匹配成功后，将 `attach_match.name` 添加到 redis key 中
例如：
```
rule_name: default_rule
rule_items:
- limit_by_consumer: ''
  limit_keys:
  - key:  "consumerA"
    query_per_day: 7
  attach_match:
    name: mcptools
    headers:
    - key: mcp-method
      val: tools/call
```
以上配置为
consumerA 同时携带请求头 mcp-method: tools/call 时，将每天限流7次 

---
For 2, multiple match conditions, only single condition matching is supported at present, and the field `attach_match` is added.
Configure `attach_match`, and the current limit will additionally match the condition. After the match is successful, add `attach_match.name` to the redis key
For example:
```
rule_name: default_rule
rule_items:
- limit_by_consumer: ''
  limit_keys:
  - key: "consumerA"
    query_per_day: 7
  attach_match:
    name: mcptools
    headers:
    - key: mcp-method
      val: tools/call
```
The above configuration is
When consumerA carries the request header mcp-method: tools/call, the flow will be limited 7 times a day

**Comment by tmsnan** [comment]
针对 3，添加限流/配额管理，通过 http 接口动态调整限流额度，实现更灵活的配额/限流调整能力
添加字段 `quota_manager ` 字段
例如：
```
redis:
  service_name: redis.dns
  password: ***
quota_manager:
  admin_consumer: consumer1
  admin_path: /quota         //未设置时默认为 higressQuotaAdminInterface 
```
但配置该配额/管理接口时，可以通过 http 接口 对应 refresh/query/delta 更新/查询/扣减/增加 限流配额值，类似 ai-quota 实现


---
For 3, add current limit/quota management, dynamically adjust the current limit quota through the http interface to achieve more flexible quota/current limit adjustment capabilities.
Add field `quota_manager` field
For example:
```
redis:
  service_name: redis.dns
  password: ***
quota_manager:
  admin_consumer: consumer1
  admin_path: /quota //Default is higressQuotaAdminInterface when not set
```
However, when configuring this quota/management interface, you can update/query/delta corresponding to refresh/query/delta, query/deduct/increase the current limit quota value, similar to ai-quota implementation
