### ISSUE TITLE
[ai-statistics ai 统计]  代理 阿里百炼应用时，无法正常统计token

### ISSUE THREAD

**Issue by MHLiu1219** [alibaba/higress#2482]
代理 百炼应用 的时候，AI统计怎么配置，目前无法正常统计token的使用情况
我尝试改成这样，但是不生效

![Image](https://github.com/user-attachments/assets/0a2a5429-3fa3-4487-9a3d-98149d4d7ed2)

![Image](https://github.com/user-attachments/assets/81ff10ac-be80-41b2-9cf4-5a5b4dc09cde)

**Comment by johnlanni** [comment]
cc @rinfx

**Comment by rinfx** [comment]
改的不对，我看配置里面配的是answer和question的配置，可以参考：
```yaml
attributes:
  - key: model
    value_source: response_body
    value: usage.models.0.model_id
    apply_to_log: true
    apply_to_span: true
  - key: input_token
    value_source: response_body
    value: usage.models.0.input_tokens
    apply_to_log: true
    apply_to_span: true
  - key: output_token
    value_source: response_body
    value: usage.models.0.output_tokens
    apply_to_log: true
    apply_to_span: true
  - key: question
    value_source: request_body
    value: input.prompt
    apply_to_log: true
    apply_to_span: false
  - key: answer
    value_source: response_body
    value: output.text
    rule: append
    apply_to_log: true
    apply_to_span: false
```
