### ISSUE TITLE
[key_auth] 认证插件适配多种认证场景 || [key_auth] The authentication plug-in is suitable for multiple authentication scenarios

### ISSUE THREAD

**Issue by daixijun** [alibaba/higress#2518]
## Why do you need it?
 Is your feature request related to a problem? Please describe in details

我们现在AI网关上承载了多种协议的 AI Provider 认证方式如 Anthropic Claude / Google Gemini / OpenAI 等，但他们的认证方式有些区别，OpenAI 使用 `Authorization: Bearer APIKEY`, 而 Cluade 和 Gemini 分别使用 `X-API-Key: APIKEY` 和 `X-Goog-API-Key: APIKEY` 

目前的 key_auth 插件针对这类场景相同的 APIKEY 需要创建两个凭证才能满足需求，配置如下:

```yaml
consumers:
  # 适配 `Authorization: Bearer APIKEY`
  - credential: Bearer sk-XXX
    name: consumer-openai-bearer
    keys:
      - Authorization
  # 适配 `X-API-Key: APIKEY` 和 `X-Goog-Api-Key: APIKEY`
  - credential: sk-XXX
    name: consumer-claude-gemini-apikey
    keys:
    - X-API-Key
    - X-Goog-Api-Key
```

是否能添加个配置项，比如 `authorization_type`， 可以定义为 `Bearer` 或其他自定义的值，作用为当使用 Authorization 头进行验证时与 credential 内容进行拼接

期望的配置方式如下:

```yaml
authorization_type: Bearer
keys:
  - Authorization
  - X-API-Key
  - X-Goog-Api-Key
consumers:
  - credential: sk-XXX
    name: consumer
```

有其他自定义认证类型时配置如下:

```yaml
authorization_type: Bearer
keys:
  - Authorization
  - X-API-Key
  - X-Goog-Api-Key
consumers:
  - credential: sk-XXX
    name: consumer
  - credential: sk-YYY
    name: consumer2
    authorization_type: JWTAuth
```

## How could it be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

## Other related information

---
## Why do you need it?
 Is your feature request related to a problem? Please describe in details

We now carry multiple protocol authentication methods on the AI ​​gateway, such as Anthropic Claude / Google Gemini / OpenAI, etc., but their authentication methods are somewhat different. OpenAI uses `Authorization: Bearer APIKEY`, while Cluade and Gemini use `X-API-Key: APIKEY` and `X-Goog-API-Key: APIKEY` respectively.

The current key_auth plug-in requires two credentials to meet the requirements for the same APIKEY in this type of scenario. The configuration is as follows:

```yaml
Consumers:
  # Adaptation `Authorization: Bearer APIKEY`
  - credential: Bearer sk-XXX
    name: consumer-openai-bearer
    keys:
      - Authorization
  # Adapt `X-API-Key: APIKEY` and `X-Goog-Api-Key: APIKEY`
  - credential: sk-XXXX
    name: consumer-claude-gemini-apikey
    keys:
    - X-API-Key
    - X-Goog-Api-Key
```

Can you add a configuration item, such as `authorization_type`, which can be defined as `Bearer` or other custom value, which is used to splice with credential content when using the Authorization header for verification

The desired configuration method is as follows:

```yaml
authorization_type: Bearer
keys:
  - Authorization
  - X-API-Key
  - X-Goog-Api-Key
Consumers:
  - credential: sk-XXXX
    name: consumer
```

When there are other custom authentication types, the configuration is as follows:

```yaml
authorization_type: Bearer
keys:
  - Authorization
  - X-API-Key
  - X-Goog-Api-Key
Consumers:
  - credential: sk-XXXX
    name: consumer
  - credential: sk-YYY
    name: consumer2
    authorization_type: JWTAuth
```

## How could it be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by johnlanni** [comment]
我觉得更合理的方式是，一个consumer支持配置多个credential，这个其实已经支持了。文档没更新，看下这个单测：

https://github.com/alibaba/higress/blob/9a0cf9b7629bff8b896371cff5af02027d7eac63/plugins/wasm-cpp/extensions/key_auth/plugin_test.cc#L124

---
I think the more reasonable way is that a consumer supports configuring multiple credentials, which is actually already supported. The document has not been updated, please check this single test:

https://github.com/alibaba/higress/blob/9a0cf9b7629bff8b896371cff5af02027d7eac63/plugins/wasm-cpp/extensions/key_auth/plugin_test.cc#L124

**Comment by daixijun** [comment]
> 我觉得更合理的方式是，一个consumer支持配置多个credential，这个其实已经支持了。文档没更新，看下这个单测：
> 
> [higress/plugins/wasm-cpp/extensions/key_auth/plugin_test.cc](https://github.com/alibaba/higress/blob/9a0cf9b7629bff8b896371cff5af02027d7eac63/plugins/wasm-cpp/extensions/key_auth/plugin_test.cc#L124)
> 
> Line 124 in [9a0cf9b](/alibaba/higress/commit/9a0cf9b7629bff8b896371cff5af02027d7eac63)
> 
>        "credentials":["abc","def"], 
> I think the more reasonable way is that a consumer supports configuring multiple credentials, which is actually already supported. The document has not been updated, please check this single test:
> 
> [higress/plugins/wasm-cpp/extensions/key_auth/plugin_test.cc](https://github.com/alibaba/higress/blob/9a0cf9b7629bff8b896371cff5af02027d7eac63/plugins/wasm-cpp/extensions/key_auth/plugin_test.cc#L124)
> 
> Line 124 in [9a0cf9b](/alibaba/higress/commit/9a0cf9b7629bff8b896371cff5af02027d7eac63)
> 
>        "credentials":["abc","def"],

意思就是同一个 consumer 创建两个 credential, 一个带 Bearer 前缀，一个不带

这样 ？
```yaml
keys:
  - Authorization
  - X-API-Key
  - X-Goog-Api-Key
consumers:
  - credentials: 
      - sk-XXXX
      - Bearer sk-XXXX
    name: consumer
```
