### ISSUE TITLE
[key_auth] 使用 key_auth 插件对 ingress/domain 授权 consumer 遇到的问题

### ISSUE THREAD

**Issue by daixijun** [alibaba/higress#2519]
## Why do you need it?
 Is your feature request related to a problem? Please describe in details

我的场景下有多个 consumer ， 且有多条 Ingress 使用同一个域名
如下配置 ingress-01 与 ingress-02 均在 higress.example.com 域名下的子路径

我期望的逻辑是 consumer-01 可以访问 ingress-01 匹配的路由 ， consumer-02 可以访问 ingress-02 访问的路由， 而 consumer-03 可以访问 higress.example.com 域名下的所有路由，假设 higress.example.com 还有其他的如 ingress-03/ingress-04 未单独配置， 则应匹配最后一条 domain 规则

```yaml
matchRules:
  - config:
      allow:
       - consumer-01
    ingress:
      - ingress-01

  - config:
      allow:
        - consumer-02
    ingress:
      - ingress-02

  - config:
      allow:
       - consumer-03
    domain:
      - higress.example.com
```

但实际测试下来
consumer-01 访问 ingress-01  -> 通过
consumer-02 访问 ingress-02  -> 通过
consumer-03 访问 higress.example.com 所有 ingress 均失败。

## How could it be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.
