### ISSUE TITLE
Implement DeGraphQL wasm plugin

### ISSUE THREAD

**Issue by johnlanni** [alibaba/higress#268]
## Why do you need it?
We can use this plugin to transform a GraphQL upstream into a traditional endpoint by mapping URIs into GraphQL queries.

## How could it be?

```yaml
apiVersion: networking.higress.io/v1
kind: McpBridge
metadata:
  name: default
  namespace: higress-system
spec:
  registries:
  - domain: api.github.com
    name: github
    port: 443
    type: dns
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    higress.io/destination: github.dns
    higress.io/upstream-vhost: "api.github.com"
    higress.io/backend-protocol: HTTPS
  name: github-api
  namespace: higress-system
spec:
  ingressClassName: higress  
  rules:
  - http:
      paths:
      - backend:
          resource:
            apiGroup: networking.higress.io
            kind: McpBridge
            name: default
         path: /api
         pathType: prefix
---
apiVersion: extensions.higress.io/v1alpha1
kind: WasmPlugin
metadata:
  name: de-graphql
  namespace: higress-system
spec:
  matchRules:
  - ingress:
    - github-api
    config:
      gql: |
           query ($owner:String! $name:String!){
              repository(owner:$owner, name:$name) {
                name
                forkCount
                description
             }
           }
  url: oci://higress-registry.cn-hangzhou.cr.aliyuncs.com/plugins/de-graphql:1.0.0
```

Test it, and it will response:

```bash
curl "http://localhost/api/repo?owner=alibaba&name=higress" \
  --header "Authorization: Bearer some-token"
{
  "data": {
      "repository": {
          "description": "Next-generation Cloud Native Gateway",
          "forkCount": 149,
          "name": "higress"
      }
  }
}
```

## Other related information
[Kong DeGraphQL plugin](https://docs.konghq.com/hub/kong-inc/degraphql/)
