### ISSUE TITLE
Update the leveled-configuration model in the README files of Wasm plugins

### ISSUE THREAD

**Issue by CH3CHO** [alibaba/higress#326]
The old configuration model uses `_rules_` field to manage domain-level and route-level configurations. And global configurations are all added to the root of the spec, which brings some trouble to the governing process on the console side.

Old model:
```yaml
consumers: # Global configuration
- credential: 'admin:123456'
  name: consumer1
- credential: 'guest:abc'
  name: consumer2
_rules_:
  - _match_route_: # Route-level configuration
    - route-a
    - route-b
    allow:
    - consumer1
  - _match_domain_: # Domain-level configuration
    - "*.example.com"
    - test.com
    allow:
    - consumer2
```

The new model uses separate fields, `defaultConfig` and `matchRules` to store configs in different levels.

New model:
```yaml
defaultConfig: # Global configuration
  consumers: # Global configuration
  - credential: 'admin:123456'
    name: consumer1
  - credential: 'guest:abc'
    name: consumer2
matchRules:
- domain: # Domain-level configuration
  - "*.example.com"
  - test.com
  config:
    allow:
    - consumer1
- ingress: # Route-level configuration
  - route-a
  - route-b
  config:
    allow:
    - consumer2
```

So all the README files in https://github.com/alibaba/higress/tree/main/plugins need to be updated with the new model.
