### ISSUE TITLE
How to set the LoadBalancer of Service on AWS ELK

### ISSUE THREAD

**Issue by gumutianqi** [alibaba/higress#378]
## Why do you need it?
在 AWS ELK 上通过 Helm 部署 Higress，拉起的 LB 是 CLB ( classic )，这个是 AWS 已经弃用的选项，需要更换为 nlb。

## How could it be?
看上去应该需要再 Helm Values.yaml 里面指定一个 AWS 的 lb annotation 注解。

## Other related information
我们尝试自己修改 Helm Values.yaml  的内容，在 gateway service 节点上增加以下内容指定 lb type 为 nlb，但是没有生效

```yaml
service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
service.beta.kubernetes.io/aws-load-balancer-type: nlb

```
