### ISSUE TITLE
higress 支持不同content_type 压缩处理

### ISSUE THREAD

**Issue by 2456868764** [alibaba/higress#410]
## Why do you need it?

 对不同返回数据类型提供压缩能力，来提高网络传输效率， 比如 支持 content-type 为 text/html, application/json等类型数据压缩。

## How could it be?

提供 envoyFilter支持:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: higress-compressor
  namespace: higress-system
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.cors
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.compressor
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor
          compressor_library:
            name: text_optimized
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.compression.gzip.compressor.v3.Gzip
              compression_strategy: DEFAULT_STRATEGY
          request_direction_config:
            common_config:
              enabled:
                default_value: false
                runtime_key: request_compressor_enabled
          response_direction_config:
            common_config:
              min_content_length: 1024
            disable_on_etag_header: true

```

可以基于[higress config](https://higress.io/zh-cn/docs/user/configmap)机制来实现配置，参考tracing实现：https://github.com/alibaba/higress/pull/409

## Other related information
envoy :  https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/compressor_filter

**Comment by wojesen** [comment]
希望可以认领这个任务

**Comment by johnlanni** [comment]
@wojesen 请问这个任务有进展吗

**Comment by 2456868764** [comment]
我重新分配一下

**Comment by 2456868764** [comment]
```
apiVersion: v1
data:
  higress: |-
    gzip:
      enable: true
      min_content_length: 100
      content_type:
        - text/html
        - application/json
      disable_on_etag_header: true
      memory_level: 3
      window_bits: 10
      compression_level: BEST_COMPRESSION
      compression_strategy: DEFAULT_STRATEGY
...
...
kind: ConfigMap
metadata:
  name: higress-config
  namespace: higress-system

````
The demo gzip settings in higress-config is above, please check @johnlanni .
