### ISSUE TITLE
负载均衡采用一致性hash算法时，增加虚拟节点数设置

### ISSUE THREAD

**Issue by fengyeall111** [alibaba/higress#443]
## Why do you need it?
情景一：
当集群内的服务A有本地状态例如本地缓存时，集群内的其他服务服务或者集群外通过higress访问服务A时，需要使用一致性hash算法.
以便让访问A服务的所有流量能转发一致. 
情景二:
和增加虚拟节点数，当endpoint变更时，减少服务内部表示状态的数据的迁移
## How could it be?
一致性hash算法有三个要素，节点列表，节点权重、虚拟节点数.
### ingress 配置里
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    higress.io/upstream-hash-by: "$remote_addr"
    higress.io/upstream-hash-node: 160         //  虚拟节点数
    higress.io/upstream-hash-field:  ""            //  这里field表示的是权重，如何获取带权重的endpoint列表呢,也许可以指定在pod上
  name: demo
 ...
```
###  底层实现
- 实现节点带权重、能设置虚拟节点数的一致性hash
- 实现节点不带权重、能设置虚拟节点的一致性hash
