### ISSUE TITLE
如何配置HTTP2Rpc到dubbo服务

### ISSUE THREAD

**Issue by PerforMance308** [alibaba/higress#510]
# 背景信息
基于https://higress.io/zh-cn/docs/user/dubbo/ 文档尝试http2rpc，但是没有成功，寻求帮助排查

# Dubbo服务
使用这个例子：https://github.com/apache/dubbo-samples/tree/master/2-advanced/dubbo-samples-docker
删除注册中心相关配置: 
![image](https://github.com/alibaba/higress/assets/12728232/1b13d4fa-019c-460e-8882-8a34e46d56d0)

使改dubbo服务不依赖注册中心

并打包成镜像

# Higress版本
v1.1.0 并enable istio CRD

# 测试步骤
1. 部署dubbo服务
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dubbo-samples-apiserver-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dubbo-samples-apiserver-provider
  template:
    metadata:
      labels:
        app: dubbo-samples-apiserver-provider
    spec:
      containers:
        - name: server
          # image created from dubbo-samples-docker
          image: dubbo-docker-sample
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 20880
```

2. 创建service

```
apiVersion: v1
kind: Service
metadata:
  name: dubbo-samples-apiserver-provider
spec:
  selector:
    app: dubbo-samples-apiserver-provider
  ports:
    - name: "dubbo"
      protocol: TCP
      port: 20880
      targetPort: 20880
```
3. 创建路由
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway
  namespace: higress-system
spec:
  selector:
    higress: higress-system-higress-gateway # use istio default ingress gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: global
spec:
  gateways:
  - higress-system/gateway
  hosts:
  - '*'
  http:
  - match:
    - ignoreUriCase: false
      uri:
        # HTTP request prefix to match this route. E.g., 127.0.0.1/dubbo/hello?name="world"
        prefix: /dubbo
    name: test
    route:
    - destination:
        # uses this if resolving name through K8s SVC
        host:  dubbo-samples-apiserver-provider.default.svc.cluster.local
        # uses thsi if resolving name through Istio ServiceEntry
        # host: dubbo.static
        port:
          number: 20880
```

4. 创建http2rpc
```
apiVersion: networking.higress.io/v1
kind: Http2Rpc
metadata:
  name: httproute-http2rpc-demo
  namespace: higress-system
spec:
  dubbo:
    service: dubbo-samples-apiserver-provider.default.svc.cluster.local
    version: 1.0.0
    group: dev
    methods:
    - serviceMethod: sayName
      headersAttach: "*"
      httpMethods:
      - "GET"
      httpPath: "/dubbo/hello"
      params:
      - paramKey: p
        paramSource: QUERY
        paramType: "java.lang.String"
```

# 测试访问
![image](https://github.com/alibaba/higress/assets/12728232/ae5f5b17-ba81-4ea4-aa4b-065c5ecb1180)

**Comment by johnlanni** [comment]
这个 Http2Rpc CRD 目前只能搭配 ingress 使用，请参考：https://higress.io/zh-cn/docs/user/dubbo#%E9%80%9A%E8%BF%87ingress%E8%BD%AC%E5%8F%91%E8%AF%B7%E6%B1%82%E5%88%B0dubbo%E6%9C%8D%E5%8A%A1

**Comment by PerforMance308** [comment]
配置如下Ingress
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    higress.io/rpc-destination-name: dubbo-samples-apiserver-provider.default.svc.cluster.local
  name: dubbo-samples-apiserver-provider
spec:
  ingressClassName: higress
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/dubbo"
        backend:
          service:
            name: dubbo-samples-apiserver-provider
            port:
              number: 20880
```

得到同样错误：
![image](https://github.com/alibaba/higress/assets/12728232/f62c1b81-ca1f-429b-82a9-b6251f5ea838)


请问是我的ingress 配置不对吗
