### ISSUE TITLE
Implement a tool to translate springcloud gateway's config to ingress

### ISSUE THREAD

**Issue by johnlanni** [alibaba/higress#522]
Spring Cloud Gateway Configuration Doc:
https://cloud.spring.io/spring-cloud-gateway/reference/html/#shortcut-configuration

Ingress Doc:
https://kubernetes.io/docs/concepts/services-networking/ingress/

Higress Ingress Annotaiton Doc:
https://higress.io/zh-cn/docs/user/annotation
https://higress.io/zh-cn/docs/user/annotation-use-case

For example:

Spring Cloud Gateway:
```yaml
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: d8ac64f3-37f9-4857-a1a9-47a814ecf358
    gateway:
      routes:
      - id: simple_route
        uri: lb://backing-service:8088
        predicates:
        - Path=/consumingServiceEndpoint
```

Ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    higress.io/destination: backing-service.DEFAULT-GROUP.d8ac64f3-37f9-4857-a1a9-47a814ecf358.nacos:8088
  name: simple_route
spec:
  ingressClassName: higress
  rules:
    - http:
        paths:
        - backend:
            resource:
              apiGroup: networking.higress.io
              kind: McpBridge
              name: default
            path: /consumingServiceEndpoint
            pathType: Exact
```
