### ISSUE TITLE
hgctl install profile 增加 resources 配置

### ISSUE THREAD

**Issue by 2456868764** [alibaba/higress#571]
## Why do you need it?
profile console, controller, gateway 配置下增加 resources 配置，可以快速方便调整 higress console， controller， gateway 资源配置。

## How could it be?

 ```
profile: local-k8s
global:
  install: local-k8s # install mode k8s/local-k8s/local-docker/local
  ingressClass: higress
  enableIstioAPI: true
  enableGatewayAPI: true
  namespace: higress-system

console:
  replicas: 1
  o11yEnabled: true
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 2048Mi

gateway:
  replicas: 1
  resources:
    requests:
      cpu: 2000m
      memory: 2048Mi
    limits:
      cpu: 2000m
      memory: 2048Mi

controller:
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: 2048Mi
    limits:
      cpu: 1000m
      memory: 2048Mi

# values passed through to helm
values:

charts:
  higress:
    url: https://higress.io/helm-charts
    name: higress
    version: latest
  standalone:
    url: https://higress.io/standalone/get-higress.sh
    name: standalone
    version: latest

```

## Other related information
#229 
https://github.com/alibaba/higress/blob/main/pkg/cmd/hgctl/manifests/profiles/local-k8s.yaml
https://github.com/alibaba/higress/blob/main/pkg/cmd/hgctl/helm/profile.go
