### ISSUE TITLE
hgctl 支持本地Docker 环境安装

### ISSUE THREAD

**Issue by 2456868764** [alibaba/higress#572]
## Why do you need it?
hgctl 支持本地docker 环境下安装

## How could it be?
1. 本地docker 环境下安装 local-docker  profile 如下：
 ```
# profile 名称
profile: local-docker
# 全局配置
global:
  # 安装模式 k8s/local-k8s/local-docker/local
  install: local-docker

# console 配置
console:
  # 本地安装时 console 端口
  port: 8080

# gateway配置
gateway:
  # 本地安装 Gateway 端口配置
  httpPort: 80
  httpsPort: 443
  metricsPort: 15020

# 控制台配置
controller:

# 本地安装存储配置
storage:
  # 后端存储类型，支持 nacos, 文件
  url: nacos://192.168.0.1:8848 #  file://opt/higress/conf
  # 后端存储类型为 naocs， 保存的命名空间
  ns: higress-system
  # 访问后端存储 用户名和密码
  username:
  password:
  # 后端存储加解密 key
  dataEncKey:

# higress & istio helm chart 配置
charts:
  higress:
    url: https://higress.io/helm-charts
    name: higress
    version: latest
  istio:
    url: https://istio-release.storage.googleapis.com/charts
    name: base
    version: 1.18.2
 ```

2. 集成 higress-standalone 安装

https://github.com/higress-group/higress-standalone/blob/main/bin/configure.sh

## Other related information
#229
