### ISSUE TITLE
Implement api-spec plugin and support api level wasm configuration for all plugins

### ISSUE THREAD

**Issue by johnlanni** [alibaba/higress#601]
## Why do you need it?

The api we are talking about here is "business api".

There are several differences between `business api` and `route api`:

1. Intent
- `business api`: Use to specific business functions such as trading, pricing, etc.
- `route api`: Used to determine which service to proxy the request to if it meets certain conditions.

2. Config model standards
- `business api`: Swagger, OAS3, gRPC/Dubbo IDL etc.
- `route api`: Ingress API, Gateway API, etc.

3. Granularity
- `business api`: One business function is mapped to one api.
- `route api`: One service backend is mapped to some apis.

We want to implement `business api` level strategy, for example:

1.  Apply [transform plugin](https://github.com/alibaba/higress/tree/main/plugins/wasm-go/extensions/transformer) to the pricing api to implement mapping of price fields.
2. Apply [key-rate-limit plugin](https://github.com/alibaba/higress/tree/main/plugins/wasm-cpp/extensions/key_rate_limit) to the trading api to limit transactions per second per user.

## How could it be?

Implement a plugin which can binding business apis to a route (or service in the feature), plugin's configuration maybe like:

```yaml
apiVersion: extensions.higress.io/v1alpha1
kind: WasmPlugin
metadata:
  name: api-spec
  namespace: higress-system
spec:
  url: oci://higress-registry.cn-hangzhou.cr.aliyuncs.com/plugins/api-spec:1.0.0
  matchRules:
  - ingress:
    - default/foo
    config:
      api_spec:
        '/pet/{petId}':
            get:
              tags:
                - pet
              operationId: getPetById
              parameters:
                - name: petId
                  in: path
                  required: true
                  schema:
                    type: integer
                    format: int64
            post:
              tags:
                - pet
              operationId: updatePetWithForm
              parameters:
                - name: petId
                  in: path
                  required: true
                  schema:
                    type: integer
                    format: int64
                - name: name
                  in: query
                  schema:
                    type: string
                - name: status
                  in: query
                  schema:
                    type: string
```

We can enable additional plugins when matching an API's `tag` or `operationId`:

```yaml
apiVersion: extensions.higress.io/v1alpha1
kind: WasmPlugin
metadata:
  name: request-transform
  namespace: higress-system
spec:
  url: oci://higress-registry.cn-hangzhou.cr.aliyuncs.com/plugins/transformer:1.0.0
  matchRules:
  - api:
    - updatePetWithForm
    config:
      type: request
      rules:
      - operate: map
        querys:
        - key: petId
           value: petid
  - apiTag:
    - pet
    config:
      type: request
      rules:
      - operate: remove
        headers:
        - key: x-test-id
```

## Other related information

https://github.com/alibaba/higress/issues/535
