### ISSUE TITLE
Implement gatewayapi support in hgctl  installation profile

### ISSUE THREAD

**Issue by 2456868764** [alibaba/higress#608]
## Why do you need it?
Implement gatewayapi support in hgctl  installation profile

## How could it be?

add enableIstioAPI property under global section  and gatwayapi sub chart under charts sections  in  profile

```
profile: local-k8s
global:
  install: local-k8s # install mode k8s/local-k8s/local-docker/local
  ingressClass: higress
  watchNamespace:
  disableAlpnH2: true
  enableStatus: true
  enableIstioAPI: true
  enableIstioAPI: true  # support gatewayapi 
  namespace: higress-system
  istioNamespace: istio-system
  

console:
  replicas: 1
  serviceType: ClusterIP
  domain: console.higress.io
  tlsSecretName:
  webLoginPrompt:
  adminPasswordValue: admin
  adminPasswordLength: 8
  o11yEnabled: true
  pvcRwxSupported: true

gateway:
  replicas: 1

controller:
  replicas: 1

# values passed through to helm
values:

charts:
  higress:
    url: https://higress.io/helm-charts
    name: higress
    version: latest
  istio:
    url: https://istio-release.storage.googleapis.com/charts
    name: base
    version: 1.18.2
  standalone:
    url: https://higress.io/standalone/get-higress.sh
    name: standalone
    version: latest
 gatwayapi:
    url: https://github.com/kubernetes-sigs/gateway-api/releases/download/v0.7.1/standard-install.yaml;https://github.com/kubernetes-sigs/gateway-api/releases/download/v0.7.1/experimental-install.yaml
    name: gatewayapi
    version: latest

```
