### ISSUE TITLE
Feature Request: support more global configuration 

### ISSUE THREAD

**Issue by zzjin** [alibaba/higress#625]
## Why do you need it?
we need to use a large size of request header.

## How could it be?
Since envoy can set `max_request_headers_kb` to big ones, so like higress can also support or expose it would be better.

## Other related information
Tried https://discuss.istio.io/t/istio-ingress-increase-header-size/9003/8 , but not works.

**Comment by johnlanni** [comment]
Try this one:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name:  hcm-options
  namespace: higress-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        name: envoy.filters.network.http_connection_manager
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          max_request_headers_kb:  8196
```
Note that the maximum request header size is 8MB, which is limited by the Envoy implementation.

**Comment by johnlanni** [comment]
We should support more global configurations through [configmap](https://higress.io/zh-cn/docs/user/configmap), which is provided by this [code](https://github.com/alibaba/higress/blob/main/pkg/ingress/kube/configmap/config.go). Then users don't need use the istio's envoyfilter to implement it.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name:  global-options
  namespace: higress-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        name: envoy.filters.network.http_connection_manager
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          common_http_protocol_options:
            # connection idle
            idle_timeout: 180s
          # http2 optimize
          http2_protocol_options:
            initial_connection_window_size: 1048576
            initial_stream_window_size: 65535
            max_concurrent_streams: 100
          # request idle
          stream_idle_timeout: 180s
  - applyTo: LISTENER
    match:
      context: GATEWAY
    patch:
      operation: MERGE
      value:
        # max buffer size per connection
        per_connection_buffer_limit_bytes: 32768
```

If anyone wants to claim this issue, you can comment below.

**Comment by lcfang** [comment]
通过配置configmap来代替配置Envoyfilter，但实际上还是转换成Envoyfilter的吧？

**Comment by johnlanni** [comment]
@lcfang 是的，可以参考 tracing 功能的实现：https://github.com/alibaba/higress/blob/main/pkg/ingress/kube/configmap/tracing.go

**Comment by lcfang** [comment]
这个有人在做了吗？没有的话我领一下吧 @johnlanni

**Comment by lcfang** [comment]
这个感觉有很多envoyfilter的配置可以按照这种方式做啊，难道要一个配置一个controller来做吗？

**Comment by 2456868764** [comment]
@lcfang 你先看一下全局配置实现文档 https://higress.io/zh-cn/blog/configmap

**Comment by 2456868764** [comment]
@lcfang 现在有什么进展吗？ 如果有问题可以参考一下 PR： https://github.com/alibaba/higress/pull/660 和 issue： https://github.com/alibaba/higress/issues/410

**Comment by johnlanni** [comment]
@lcfang 麻烦加一下OPS SIG的钉钉群：45280001966
需要一起讨论下这块设计

**Comment by sjcsjc123** [comment]
我可以尝试一下。

**Comment by sjcsjc123** [comment]
higress配置文件设计如下：
```yaml
apiVersion: v1
data:
  higress: |-
    httpConnectManager:
      common:
        idleTimeout: 180s  (Duration) 0表示不超时
        maxConnectionDuration: 180s  (Duration)
        maxHeadersCount: 200  (uint32)
        maxRequestsPerConnection: 1000  (uint32)
      http2:  
        maxConcurrentStreams: 2147483647  (uint32) (1 - 2147483647(2^31-1))
        initialStreamWindowSize: 65536  (uint32) (65535 - 2147483647)
        initialConnectionWindowSize: 65536  (uint32)
      maxRequestHeadersKb: 60  (uint32)  最大: 8*1024=8192
      requestTimeout: 300s  (Duration) 0表示不超时
      streamIdleTimeout: 300s (Duration) 0表示不超时
      xRealIp: false  (bool)
      perConnectionBufferLimitBytes: 32768  (uint32)
...
...
kind: ConfigMap
metadata:
  name: higress-config
  namespace: higress-system
```
这个配置文件可以吗？切换为envoyFilter的配置文件的话大致如下：
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name:  global-options
  namespace: higress-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        name: envoy.filters.network.http_connection_manager
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          common_http_protocol_options:
            idleTimeout: 180s  (Duration) 0表示不超时
            maxConnectionDuration: 180s  (Duration)
            maxHeadersCount: 200  (uint32)
            maxRequestsPerConnection: 1000  (uint32)
          http2_protocol_options:
            maxConcurrentStreams: 2147483647  (uint32) (1 - 2147483647(2^31-1))
            initialStreamWindowSize: 65536  (uint32) (65535 - 2147483647)
            initialConnectionWindowSize: 65536  (uint32)
          # request idle
          maxRequestHeadersKb: 60  (uint32)  最大 8*1024=8192
          requestTimeout: 300s  (Duration) 0表示不超时
          streamIdleTimeout: 300s (Duration) 0表示不超时
  - applyTo: LISTENER
    match:
      context: GATEWAY
    patch:
      operation: MERGE
      value:
        # max buffer size per connection
        per_connection_buffer_limit_bytes: 32768
  - applyTo: ROUTE_CONFIGURATION
    match:
      context: GATEWAY
    patch:
      operation: MERGE
      value:
        request_headers_to_add:
        - append: false
          header:
            key: x-real-ip
            value: '%REQ(X-ENVOY-EXTERNAL-ADDRESS)%'
```
