### ISSUE TITLE
Support the use of nacos as storage when deploying with k8s

### ISSUE THREAD

**Issue by keepal7** [alibaba/higress#642]
## backgroud & feature-description
Many companies use multiple k8s clusters to form federated clusters. When it is not possible to deploy higress in each k8s cluster, a separate component is needed to store higress metadata. Nacos is a good choice.

**Comment by CH3CHO** [comment]
Task overview:
1. [ ] Deploy Higress API Server in the K8s cluster：https://github.com/higress-group/higress-standalone/tree/main/src/apiserver
2. [ ] Make Higress Controller pulling resources from Higress API Server instead of K8s API Server

**Comment by CH3CHO** [comment]
## Step 1: Generate Higress API Server configurations

Install the standalone version of Higress with builtin Nacos.

```shell
curl -fsSL https://higress.io/standalone/get-higress.sh | bash -s -- -a --use-builtin-nacos
```

Save all files in `./higress/compose/volumes/api` and `./higress/compose/volumes/kube` for future use.

Clean up: Execute `./higress/bin/reset.sh` and delete `./higress`.

## Step 2: Deploy Higress API Server in K8s

Create a Secret resource to store configurations to be used by Higress API Server.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: higress-apiserver
  namespace: higress-system
data:
  ca.crt: $(cat api/ca.crt)
  ca.key: $(cat api/ca.key)
  server.crt: $(cat api/server.crt)
  server.key: $(cat api/server.key)
  client.key: $(cat api/client.crt)
  nacos.key: $(cat api/nacos.key)
```

Create a Deployment resource for Higress API Server.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: higress-apiserver
    higress: higress-apiserver
  name: higress-apiserver
  namespace: higress-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: higress-apiserver
      higress: higress-apiserver
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: higress-apiserver
        higress: higress-apiserver
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - args:
        - --secure-port
        - "8443"
        - --client-ca-file
        - /etc/api/ca.crt
        - --tls-cert-file
        - /etc/api/server.crt
        - --tls-private-key-file
        - /etc/api/server.key
        - --storage
        - nacos
        - --nacos-server
        - http://NACOS_SERVER_IP:8848
        - --nacos-username
        - NACOS_USERNAME
        - --nacos-password
        - NACOS_PASSWORD
        - --nacos-ns-id
        - NACOS_NS_ID
        - --nacos-encryption-key-file
        - /etc/api/nacos.key
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        image: higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/api-server:0.0.10
        imagePullPolicy: IfNotPresent
        name: higress-apiserver
        ports:
        - containerPort: 8443
          hostPort: 8443
          name: https
          protocol: TCP
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /readyz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 1
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 3
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 1337
          runAsNonRoot: true
          runAsUser: 1337
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/api
          name: config
          readOnly: true
        - mountPath: /tmp/nacos
          name: nacos-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        secret:
          defaultMode: 420
          secretName: higress-apiserver
      - emptyDir: {}
        name: nacos-data
```

Create a Service resource for Higress API Server.

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: higress-apiserver
    higress: higress-apiserver
  name: higress-apiserver
  namespace: higress-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: higress-apiserver
    higress: higress-apiserver
  type: ClusterIP
```

### Step 3: Point Higress Controller to Higress API Server

Add `kubeconfig` file into the `higress-config` ConfigMap.

```yaml
apiVersion: v1
data:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters: ....
  mesh: |-
    accessLogEncoding: TEXT
    accessLogFile: /dev/stdout
    accessLogFormat: ...
  meshNetworks: 'networks: {}'
kind: ConfigMap
metadata:
  ...
```

Update the `higress-controller` deployment. Update `args` field of `higress-core` container.

```yaml
      - args:
        - serve
        - --kubeconfig=/etc/istio/config/kubeconfig
        - --gatewaySelectorKey=higress
        - --gatewaySelectorValue=higress-system-higress-gateway
        - --ingressClass=higress
```

If everythong goes well, you should be able to find a config item named `` in the corresponding namespace in Higress.

![image](https://github.com/alibaba/higress/assets/2909796/eb363bc1-7cad-4ea7-9377-850bd6db6f5e)

### All set. You can create Ingress resources in Nacos now.

Create a config with name prefix `ingresses.`, put Ingress YAML data into it, and save.

![image](https://github.com/alibaba/higress/assets/2909796/42bbe115-3c6a-4107-ab08-0a9efe155ce4)
