### ISSUE TITLE
支持关闭 x-envoy-original-path 请求头，避免对于path过长的情况，后端处理的header过大导致400

### ISSUE THREAD

**Issue by h31105** [alibaba/higress#643]
经过抓包对比分析后得出结论：
higress转发时会带一个x-envoy-original-path，导致整体header超过后端服务可接受的header大小阈值，这种情况下，请求报400错误。

根据测试验证，后端（springcloud java）通过调整 **max-http-header-size** 可以缓解此问题。

**Comment by johnlanni** [comment]
可以支持通过envoyfilter配置关闭此header设置，这个issue也作为#641的一部分

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  namespace: higress-system
  name: route
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: REPLACE
        value:
          name: envoy.filters.http.router
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
            suppress_envoy_headers: true
```

**Comment by sjcsjc123** [comment]
这个可以参考PR： https://github.com/alibaba/higress/pull/660 和 issue： https://github.com/alibaba/higress/issues/410 吗？可以的话，我可以尝试一下

**Comment by sjcsjc123** [comment]
higress配置文件设计如下：
```yaml
apiVersion: v1
data:
  higress: |-
    httpConfig:
      common:
        idleTimeout: 180s  (Duration) 0表示不超时
        maxConnectionDuration: 180s  (Duration)
        maxHeadersCount: 200  (uint32)
        maxRequestsPerConnection: 1000  (uint32)
      http2:  
        maxConcurrentStreams: 2147483647  (uint32) (1 - 2147483647(2^31-1))
        initialStreamWindowSize: 65536  (uint32) (65535 - 2147483647)
        initialConnectionWindowSize: 65536  (uint32)
      maxRequestHeadersKb: 60  (uint32)  最大: 8*1024=8192
      requestTimeout: 300s  (Duration) 0表示不超时
      streamIdleTimeout: 300s (Duration) 0表示不超时
      xRealIp: false  (bool)
      perConnectionBufferLimitBytes: 32768  (uint32)
      suppressEnvoyHeaders: false  (bool)
...
...
kind: ConfigMap
metadata:
  name: higress-config
  namespace: higress-system
```
这个配置文件可以吗？切换为envoyFilter的配置文件的话大致如下：
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name:  global-options
  namespace: higress-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: MERGE
      value:
        name: envoy.filters.network.http_connection_manager
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          common_http_protocol_options:
            idleTimeout: 180s  (Duration) 0表示不超时
            maxConnectionDuration: 180s  (Duration)
            maxHeadersCount: 200  (uint32)
            maxRequestsPerConnection: 1000  (uint32)
          http2_protocol_options:
            maxConcurrentStreams: 2147483647  (uint32) (1 - 2147483647(2^31-1))
            initialStreamWindowSize: 65536  (uint32) (65535 - 2147483647)
            initialConnectionWindowSize: 65536  (uint32)
          # request idle
          maxRequestHeadersKb: 60  (uint32)  最大 8*1024=8192
          requestTimeout: 300s  (Duration) 0表示不超时
          streamIdleTimeout: 300s (Duration) 0表示不超时
  - applyTo: LISTENER
    match:
      context: GATEWAY
    patch:
      operation: MERGE
      value:
        # max buffer size per connection
        per_connection_buffer_limit_bytes: 32768
  - applyTo: ROUTE_CONFIGURATION
    match:
      context: GATEWAY
    patch:
      operation: MERGE
      value:
        request_headers_to_add:
        - append: false
          header:
            key: x-real-ip
            value: '%REQ(X-ENVOY-EXTERNAL-ADDRESS)%'
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: REPLACE
      value:
        name: envoy.filters.http.router
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          suppress_envoy_headers: true
```
同时包含 #625 #631 #643

**Comment by 2456868764** [comment]
1. 在 httpConfig 增加一个属性 enable: false (默认）整体控制是否生效这个配置
2. 这个 xRealIp 配置项，xRealIP 这类类型配置是对应的 Envoy 里 response_headers_to_add， response_headers_to_remove， request_headers_to_add，request_headers_to_remove， 可以参考 https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route.proto， 是否需要要支持这四种 request/response header 操作？
3. 对这个  xRealIp，是否允许用户自定义 request header 名称，而不是默认的x-real-ip ？

其他参考文档： https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#config-access-log-format

@johnlanni 看一下

**Comment by sjcsjc123** [comment]
> 1. 在 httpConfig 增加一个属性 enable: false (默认）整体控制是否生效这个配置
> 2. 这个 xRealIp 配置项，xRealIP 这类类型配置是对应的 Envoy 里 response_headers_to_add， response_headers_to_remove， request_headers_to_add，request_headers_to_remove， 可以参考 [https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route.proto，](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route.proto%EF%BC%8C) 是否需要要支持这四种 request/response header 操作？
> 3. 对这个  xRealIp，是否允许用户自定义 request header 名称，而不是默认的x-real-ip ？
> 
> 其他参考文档： https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#config-access-log-format
> 
> @johnlanni 看一下

@johnlanni 有什么建议吗，没有的话我重新设计一下

**Comment by sjcsjc123** [comment]
higress配置文件修改之后如下：
```yaml
apiVersion: v1
data:
  higress: |-
    httpConfig:
      enable: false (bool)
      common:
        idleTimeout: 180s  (Duration) 0表示不超时
        maxConnectionDuration: 180s  (Duration)
        maxHeadersCount: 200  (uint32)
        maxRequestsPerConnection: 1000  (uint32)
      http2:  
        maxConcurrentStreams: 2147483647  (uint32) (1 - 2147483647(2^31-1))
        initialStreamWindowSize: 65536  (uint32) (65535 - 2147483647)
        initialConnectionWindowSize: 65536  (uint32)
      maxRequestHeadersKb: 60  (uint32)  最大: 8*1024=8192
      requestTimeout: 300s  (Duration) 0表示不超时
      streamIdleTimeout: 300s (Duration) 0表示不超时
      perConnectionBufferLimitBytes: 32768  (uint32)
      suppressEnvoyHeaders: false  (bool)
      requestHeadersToAdd:
        -header:
          key: x-real-ip
          value: '%REQ(X-ENVOY-EXTERNAL-ADDRESS)%'
          append: false
      requestHeadersToRemove:
        - x-envoy-external-address
      responseHeadersToAdd:
        - header:
          key: code
          value: '%RESPONSE_CODE%'
          append: false
      responseHeadersToRemove:
        - x-envoy-external-address
...
...
kind: ConfigMap
metadata:
  name: higress-config
  namespace: higress-system
```
切换为envoyFilter的配置文件的话大致如下：
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name:  global-options
  namespace: higress-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: MERGE
      value:
        name: envoy.filters.network.http_connection_manager
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          common_http_protocol_options:
            idleTimeout: 180s  (Duration) 0表示不超时
            maxConnectionDuration: 180s  (Duration)
            maxHeadersCount: 200  (uint32)
            maxRequestsPerConnection: 1000  (uint32)
          http2_protocol_options:
            maxConcurrentStreams: 2147483647  (uint32) (1 - 2147483647(2^31-1))
            initialStreamWindowSize: 65536  (uint32) (65535 - 2147483647)
            initialConnectionWindowSize: 65536  (uint32)
          # request idle
          maxRequestHeadersKb: 60  (uint32)  最大 8*1024=8192
          requestTimeout: 300s  (Duration) 0表示不超时
          streamIdleTimeout: 300s (Duration) 0表示不超时
  - applyTo: LISTENER
    match:
      context: GATEWAY
    patch:
      operation: MERGE
      value:
        # max buffer size per connection
        per_connection_buffer_limit_bytes: 32768
  - applyTo: ROUTE_CONFIGURATION
    match:
      context: GATEWAY
    patch:
      operation: MERGE
      value:
        request_headers_to_add:
        - append: false
          header:
            key: x-real-ip
            value: '%REQ(X-ENVOY-EXTERNAL-ADDRESS)%'
        request_headers_to_remove:
          - request_headers_to_remove
        response_headers_to_add:
        - append: false
          header:
            key: code
            value: '%RESPONSE_CODE%'
        response_headers_to_remove:
          - response_headers_to_remove
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: REPLACE
      value:
        name: envoy.filters.http.router
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          suppress_envoy_headers: true
```

@2456868764  @2456868764

**Comment by johnlanni** [comment]
@sjcsjc123 给出的envoyfilter有错误，第一个patch是network filter，不应该填subfilter
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name:  global-options
  namespace: higress-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
```

**Comment by johnlanni** [comment]
另外，我不建议把原生的envoy配置全部透出在higress配置里。higress应该针对网关场景做配置简化

**Comment by johnlanni** [comment]
```yaml
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        name: envoy.filters.network.http_connection_manager
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          common_http_protocol_options:
            idle_timeout: 180s
          http2_protocol_options:
            initial_connection_window_size: 1048576
            initial_stream_window_size: 65535
            max_concurrent_streams: 100
          stream_idle_timeout: 180s
  - applyTo: LISTENER
    match:
      context: GATEWAY
    patch:
      operation: MERGE
      value:
        per_connection_buffer_limit_bytes: 32768
```
对于上面这部分，我建议通过下面的配置进行抽象（同时给出的是默认值，即用户不配该字段时使用这个值）:

```yaml
downstream:
  # 控制 per_connection_buffer_limit_bytes
  connectionBufferLimits: 32768
  # 同时控制 idle_timeout 和 stream_idle_timeout
  idleTimeout: 180s
  # 控制 http2_protocol_options
  http2:
    initialConnectionWindowSize: 1048576
    initialStreamWindowSize: 65535
    maxConcurrentStreams: 100  
```

**Comment by johnlanni** [comment]
全局header这个配置先不暴露出来吧。因为可以通过transformer插件来做。一个功能到处都能配置，不是个好的设计。
对于 x-real-ip 这个功能，可以单独加个配置，key可以是"addXRealIPHeader":

```yaml
addXRealIpHeader: true
downstream:
  maxRequestHeadersKb: 60
...
```

**Comment by sjcsjc123** [comment]
higress配置文件修改之后如下：
```yaml
apiVersion: v1
data:
  higress: |-
    downstream:
      enable: false (bool) (表示是否开启）
      idleTimeout: 180s  (Duration) 0表示不超时  （表示idleTimeout和streamIdleTimeout）
      maxRequestHeadersKb: 60  (uint32)  最大: 8*1024=8192  （表示maxRequestHeadersKb）
      connectionBufferLimits: 32768  (uint32)
      http2:  
        maxConcurrentStreams: 100  (uint32) (1 - 2147483647(2^31-1))
        initialStreamWindowSize: 65535  (uint32) (65535 - 2147483647)
        initialConnectionWindowSize: 1048576  (uint32)
    suppressEnvoyHeaders: false  (bool)
    addXRealIpHeader: false  (bool)
...
...
kind: ConfigMap
metadata:
  name: higress-config
  namespace: higress-system
```
切换为envoyFilter的配置文件的话大致如下：
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name:  global-options
  namespace: higress-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        name: envoy.filters.network.http_connection_manager
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          common_http_protocol_options:
            idleTimeout: 180s  (Duration) 0表示不超时
          http2_protocol_options:
            maxConcurrentStreams: 100  (uint32) (1 - 2147483647(2^31-1))
            initialStreamWindowSize: 65535  (uint32) (65535 - 2147483647)
            initialConnectionWindowSize: 1048576  (uint32)
          # request idle
          maxRequestHeadersKb: 60  (uint32)  最大 8*1024=8192
          streamIdleTimeout: 180s (Duration) 0表示不超时
  - applyTo: LISTENER
    match:
      context: GATEWAY
    patch:
      operation: MERGE
      value:
        # max buffer size per connection
        per_connection_buffer_limit_bytes: 32768
  - applyTo: ROUTE_CONFIGURATION
    match:
      context: GATEWAY
    patch:
      operation: MERGE
      value:
        request_headers_to_add:
        - append: false
          header:
            key: x-real-ip
            value: '%REQ(X-ENVOY-EXTERNAL-ADDRESS)%'
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: REPLACE
      value:
        name: envoy.filters.http.router
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          suppress_envoy_headers: true
```

@johnlanni  @2456868764
