### ISSUE TITLE
Cannot serve by nginx proxy_pass

### ISSUE THREAD

**Issue by zzjin** [alibaba/higress#651]
- [x] I have searched the [issues](https://github.com/alibaba/higress/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
When upgraded from ingress-nginx controller to higress with `global.disableAlpnH2=true`, some functions do not work as usual.

### Ⅱ. Describe what happened

User server's nginx output error log and cannot access proxy stream:

```
*1 peer closed connection in SSL handshake (104: Connection reset by peer) while SSL handshaking to upstream, client: 10.0.2.53, server: localhost, request: "GET / HTTP/1.1", upstream: "[https://34.87.20.189:443/](https://34.87.20.189/)", host: "gboinqtqlini.cloud.sealos.top", referrer: "https://applaunchpad.cloud.sealos.top/"
*1 upstream server temporarily disabled while SSL handshaking to upstream, client: 10.0.2.53, server: localhost, request: "GET / HTTP/1.1", upstream: "[https://34.87.20.189:443/](https://34.87.20.189/)", host: "gboinqtqlini.cloud.sealos.top", referrer: "https://applaunchpad.cloud.sealos.top/"
```

### Ⅲ. Describe what you expected to happen
User can broswer content as usual.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. deploy higress
2. create one ingress cr with wildcard cert
    ```yaml
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/backend-protocol: HTTP
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/use-regex: "true"
      name: gglkrtup
      namespace: ns-abcdefg
    spec:
      tls:
        - hosts:
            - abcdefg.cloud.sealos.io
          secretName: wildcard-cloud-sealos-io-cert
      rules:
        - host: abcdefg.cloud.sealos.io
          http:
            paths:
              - path: /()(.*)
                pathType: Prefix
                backend:
                  service:
                    name: gglkrtup
                    port:
                      number: 3000

    ```
3. check user can direct access it via cr host url
4. deploy one other server with nginx installed
5. setup a new server block with: 
    ```
    location / {
        proxy_pass   https://HIGRESS_CR_HOST_HERE/;
    }
    ```

### Ⅵ. Environment:

- Higress version:  1.3.1
- OS : Kubernetes 1.25.6 on Ubuntu 22.04
