### ISSUE TITLE
在插件中无法请求外部服务

### ISSUE THREAD

**Issue by DuanJiaNing** [alibaba/higress#654]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via [ASRC](https://security.alibaba.com/)(Alibaba Security Response Center) where the issue will be triaged appropriately.**

- [x] I have searched the [issues](https://github.com/alibaba/higress/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

我们直接下载了 [http-call](https://github.com/alibaba/higress/blob/main/plugins/wasm-go/extensions/http-call/main.go)，并使用 这个 [Dockerfile](https://github.com/alibaba/higress/blob/main/plugins/wasm-go/Dockerfile) 进行构建，构建成功之后将其配置到 higress 插件中，不启用插件时，chrome 访问 /foo 地址能成功，启用后 chrome devtool 中该请求始终为 pending 状态，不清楚问题在哪。

这是插件配置

```yaml
bodyHeader: "body-from-https"
namespace: "service-base"
requestPath: "/foo"
serviceName: "global-srv"
servicePort: 8000
serviceSource: "k8s"
tokenHeader: "xxx"
```
![image](https://github.com/alibaba/higress/assets/20266921/85df91ae-be57-4d21-8657-5ba890418bfa)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅴ. Anything else we need to know?

我们的原始需求是在插件中访问公网的一个 http post 接口，最初参考 [chatgpt-proxy](https://github.com/alibaba/higress/tree/main/plugins/wasm-go/extensions/chatgpt-proxy) 的方式进行实现，但发现无法调通。

### Ⅵ. Environment:

- Higress version:  
- OS :
- Others:
