### ISSUE TITLE
如何不在 x-forwarded-for 中追加代理 IP

### ISSUE THREAD

**Issue by WangJieWJ** [alibaba/higress#771]
## Why do you need it?
 Is your feature request related to a problem? Please describe in details

现在是后端应用接收到的 XFF 会包含 10.177.X.X 这种K8S内部IP，想看一下怎么取消这个追加策略，直接使用前面透传过来的 XFF，然后找了下面一个配置项，但是不知道在 Higress 怎么配置这个
具体地址：https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#config-http-conn-man-headers-x-forwarded-for
![2222](https://github.com/alibaba/higress/assets/16323371/fcf4ba7f-473b-4880-a159-00ac25768744)

Higress 日志：
![3333](https://github.com/alibaba/higress/assets/16323371/ac073e2d-a165-46c1-bc72-17c56f6908a3)

## How could it be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by johnlanni** [comment]
1.  安装istio CRD，并开启istio API支持，参考文档：https://higress.io/zh-cn/docs/ops/deploy-by-helm#%E6%94%AF%E6%8C%81-istio-crd%E5%8F%AF%E9%80%89
2. kubectl apply 下面这份配置：
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name:  my-hcm-options
  namespace: higress-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        name: envoy.filters.network.http_connection_manager
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          skip_xff_append: true
```
