### ISSUE TITLE
waf 开启观察模式某些请求无法正确响应

### ISSUE THREAD

**Issue by h31105** [alibaba/higress#808]
如题，waf插件开启仅观察模式：
```
useCRS: true
secRules: 
- "SecRuleEngine DetectionOnly"
```

实际使用中，某些情况下会造成，后端响应异常，前端页面元素空白，接口响应报错
![image](https://github.com/alibaba/higress/assets/38588395/118e5062-57ad-49db-b8e6-d5d661c91695)

关掉waf插件后，恢复正常

**Comment by johnlanni** [comment]
@h31105 目前waf插件需要缓存请求body和响应body，网关对请求body的最大buffer限制默认值是 32k，可以通过[网关全局参数](https://higress.io/zh-cn/docs/user/configmap)中的downstream下的connectionBufferLimits来调整。
响应body，目前还没有开放配置，可以通过[开启istio api后](https://higress.io/zh-cn/docs/ops/deploy-by-helm#%E6%94%AF%E6%8C%81-istio-crd%E5%8F%AF%E9%80%89)，下发envoyfilter来配置：
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: upstream-idle-timeout
  namespace: higress-system
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      context: GATEWAY
    patch:
      operation: MERGE
      value:
        # 放开到10m
        per_connection_buffer_limit_bytes: 10485760
```
