### ISSUE TITLE
http头重复设置在Higress下会报415（Invalid mime type...），而在ingress controller下是正常的

### ISSUE THREAD

**Issue by millinchen** [alibaba/higress#818]
curl POST 'http://xxx/user/queryList'
-- header 'Content-Type: application/json'
-- header 'Content-Type: application/json; charset=UTF-8'
-- header ’Host:test.com.cn'
-- data-row '{
"usrId": "1000001"
}'

执行上面请求当http头被重复设置时（实际场景下由于请求链路长，可能会在某个链路环节重复设置了），在ingress controller下是正常的，迁移到Higress下会则报415（Invalid mime type...），请问Higress怎么能解决这个问题呢？

**Comment by johnlanni** [comment]
envoy会在协议解析阶段就进行内联header的合并，这是符合RFC标准的：https://datatracker.ietf.org/doc/html/rfc7230#section-3.2.2
另外，多个content-type头透传可能会导致产生安全性隐患。

如果要绕过此问题，可以[开启istio api](https://higress.io/zh-cn/docs/ops/deploy-by-helm#%E6%94%AF%E6%8C%81-istio-crd%E5%8F%AF%E9%80%89)支持，然后通过一个 lua envoyfilter来修改content-type，例如下面这个lua代码判断content-type中只要包含 application/json，就整体replace成一个：

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: updateheader
  namespace: higress-system
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        value: 
          name: envoy.lua
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
            inline_code: |-
              function envoy_on_request(request_handle)
                local type = request_handle:headers():get("Content-Type")
                if string.find(type, "application/json") then
                  request_handle:headers():replace("Content-Type","application/json; charset=UTF-8")
                end
              end
```
