### ISSUE TITLE
基于ip的限流插件

### ISSUE THREAD

**Issue by CPAltair** [alibaba/higress#851]
key-rate-limit插件目前只支持limit_by_header和limit_by_param 2种限流维度，希望插件能加上基于client ip的限流 或 新插件实现
需求：
1. 每个client请求达到阈值触发限流并可自定义的respon code和respon text
2. 基于client ip的策略可与 limit_by_header 或 limit_by_param同时启用不冲突
3. 基于client ip的策略支持 令牌、桶漏、滑动窗口等主流限流算法
4. 支持全局限流

**Comment by johnlanni** [comment]
计划后续基于插件中访问redis的能力来扩展实现这一能力

**Comment by johnlanni** [comment]
插件sdk已经支持redis api，欢迎认领

**Comment by wapmnw** [comment]
@johnlanni 
插件是还没更新么，在官方文档中还只有limit_by_header和limit_by_param
![image](https://github.com/alibaba/higress/assets/31203438/9f7e4cbc-786d-4053-a3bd-b210ef8d8723)

**Comment by hanxiantao** [comment]
> @johnlanni 插件是还没更新么，在官方文档中还只有limit_by_header和limit_by_param ![image](https://private-user-images.githubusercontent.com/31203438/331453882-9f7e4cbc-786d-4053-a3bd-b210ef8d8723.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MTk2NTEsIm5iZiI6MTcxNTkxOTM1MSwicGF0aCI6Ii8zMTIwMzQzOC8zMzE0NTM4ODItOWY3ZTRjYmMtNzg2ZC00MDUzLWEzYmQtYjIxMGVmOGQ4NzIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA0MTU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkYWY1MTVkZTc1NTY4ZmZkY2EzNzQ2NzA4NDc0NGI1YmU0ZjU1MWNhNzY2ZWNmOTBkMGM3YjIzN2NlNDM4ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GhC2urXzuVU6ctqkCHekuO8_1H_cGe6EVcaaIw36is4)

集群限流的插件需要使用redis的能力，但envoy中使用redis的能力还未开源，开源后我这边会继续跟进这个功能，目前已经开发了一部分，但无法调试和使用
![image](https://github.com/alibaba/higress/assets/45159482/eae4ad13-3f66-4587-b9e4-6fdea318b0d3)

**Comment by wapmnw** [comment]
> > @johnlanni 插件是还没更新么，在官方文档中还只有limit_by_header和limit_by_param ![image](https://private-user-images.githubusercontent.com/31203438/331453882-9f7e4cbc-786d-4053-a3bd-b210ef8d8723.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MTk2NTEsIm5iZiI6MTcxNTkxOTM1MSwicGF0aCI6Ii8zMTIwMzQzOC8zMzE0NTM4ODItOWY3ZTRjYmMtNzg2ZC00MDUzLWEzYmQtYjIxMGVmOGQ4NzIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA0MTU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkYWY1MTVkZTc1NTY4ZmZkY2EzNzQ2NzA4NDc0NGI1YmU0ZjU1MWNhNzY2ZWNmOTBkMGM3YjIzN2NlNDM4ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GhC2urXzuVU6ctqkCHekuO8_1H_cGe6EVcaaIw36is4)
> 
> @wapmnw 集群限流的插件需要使用redis的能力，但envoy中使用redis的能力还未开源，开源后我这边会继续跟进这个功能，目前已经开发了一部分，但无法调试和使用

好的明白了，谢谢

**Comment by johnlanni** [comment]
@hanxiantao 最新发布的1.4.0-rc.1已经支持插件里访问redis了，可以试试

**Comment by hanxiantao** [comment]
> @hanxiantao 最新发布的1.4.0-rc.1已经支持插件里访问redis了，可以试试

好的

**Comment by hanxiantao** [comment]
@johnlanni 咨询个问题
我这边开发的时候，redisClient init一直报错：
[Envoy (Epoch 0)] [2024-05-25 07:16:09.594][30][error][wasm] wasm log: [key-cluster-rate-limit] cluster.ClusterName():outbound|6379||redis.static
[Envoy (Epoch 0)] [2024-05-25 07:16:09.594][30][error][wasm] wasm log: [key-cluster-rate-limit] cluster.HostName():redis
[Envoy (Epoch 0)] [2024-05-25 07:16:09.594][30][error][wasm] wasm log: [key-cluster-rate-limit] username ,password ,timeout 10000
[Envoy (Epoch 0)] [2024-05-25 07:16:09.594][30][critical][wasm] wasm log: failed to init redis: error status returned by host: bad argument
[Envoy (Epoch 0)] [2024-05-25 07:16:09.594][30][warning][wasm] wasm log: [key-cluster-rate-limit] parse rule config failed: parse config failed, no valid rules; global config parse error:redisClient init error: error status returned by host: bad argument
[Envoy (Epoch 0)] [2024-05-25 07:16:09.594][30][error][wasm] Wasm VM failed Failed to configure base Wasm plugin

redis init代码如下：
```
func initRedisClient(json gjson.Result, config *KeyClusterRateLimitConfig, log wrapper.Log) error {
	serviceSource := json.Get("service_source").String()
	serviceName := json.Get("service_name").String()
	serviceHost := json.Get("service_host").String()
	servicePort := json.Get("service_port").Int()
	if serviceName == "" || servicePort == 0 {
		return errors.New("invalid service config")
	}
	switch serviceSource {
	case "ip":
		config.client = wrapper.NewRedisClusterClient(&wrapper.StaticIpCluster{
			ServiceName: serviceName,
			Host:        serviceHost,
			Port:        servicePort,
		})
	case "dns":
		domain := json.Get("service_domain").String()
		if domain == "" {
			return errors.New("missing service_domain in config")
		}
		config.client = wrapper.NewRedisClusterClient(&wrapper.DnsCluster{
			ServiceName: serviceName,
			Port:        servicePort,
			Domain:      domain,
		})
	default:
		return errors.New("unknown service source: " + serviceSource)
	}
	username := json.Get("username").String()
	password := json.Get("password").String()
	timeout := json.Get("timeout").Int()
	err := config.client.Init(username, password, timeout)
	if err != nil {
		return errors.New(fmt.Sprintf("redisClient init error: %v", err))
	}
	return nil
}
```
使用的gateway镜像：higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/gateway:1.4.0-rc.1
服务来源、服务列表如下：
<img width="1428" alt="image" src="https://github.com/alibaba/higress/assets/45159482/3c242b9b-9813-42da-b10b-eb080c46b544">

<img width="1425" alt="image" src="https://github.com/alibaba/higress/assets/45159482/be485eb9-5245-4fef-9c92-39a59bf3379e">
wasmplugin.yaml：

```
apiVersion: extensions.higress.io/v1alpha1
kind: WasmPlugin
metadata:
  name: test
  namespace: higress-system
spec:
  defaultConfig:
    ip_source_type: header
    rule_name: test
    service_name: redis
    service_host: redis
    service_port: 6379
    service_source: ip
    timeout: 10000
    limit_keys:
      - key: 1.1.1.1
        query_per_second: 10
  url: oci://registry.cn-hangzhou.aliyuncs.com/wasm-plugin/wasm-plugin:0.0.19
  imagePullSecret: aliyun
```

**Comment by pepesi** [comment]
集群中的redis地址要怎么写才对呢？
我在default namespace下部署了一个redis，service就叫redis，没有密码，默认端口

我的wasm中配置这样的
```
spec:
  matchRules:
  - config:
      redis:
        service_name: redis.default
      rule_items:
      - limit_by_per_header: X-USER
        limit_keys:
        - key: regexp:.*
          token_per_second: 10
      rule_name: default_rule
    configDisable: false
    ingress:
    - baichuan
  phase: UNSPECIFIED_PHASE
  priority: 600
  ```
  但是日志老报错，我不确定这个格式要怎么写了
  ```
  [Envoy (Epoch 0)] [2024-06-26 03:07:42.131][32][critical][wasm] wasm log: failed to init redis: error status returned by host: bad argument
[Envoy (Epoch 0)] [2024-06-26 03:07:42.131][32][warning][wasm] wasm log: [ai-token-ratelimit] parse rule config failed: error status returned by host: bad argument
  ```
  我尝试过 `redis://redis.static` `redis` 都没效果
  我看到wasm-go中用的是 ClusterName() 方法，这在evoy内部有啥自己转换机制吗?
  https://github.com/alibaba/higress/blob/0ce52de59b2416193fdb62854210142aceef98f5/plugins/wasm-go/pkg/wrapper/redis_wrapper.go#L114
