### ISSUE TITLE
higress的wasm plugin如何应用在gateway api上

### ISSUE THREAD

**Issue by alexzzh** [alibaba/higress#857]
### Ⅰ. Issue Description
  - 项目中需要使用gateway api，但需要结合ext_authn\ratelimit\jwt等一起使用，所以需要higress 的wasm plugin能结合gateway api一起生效，按照 [这个文档](https://higress.io/zh-cn/docs/plugins/intro/#%E9%80%9A%E8%BF%87-higress-wasmplugin-crd-%E8%BF%9B%E8%A1%8C%E9%85%8D%E7%BD%AE ) 测试下来，全局范围可以生效，但不清楚如何将plugin规则应用于局部范围，例如只针对某个httproute生效。

### Ⅱ. Describe what happened

   - 部署gateway api测试环境
```
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: higress-gateway
spec:
  controllerName: "higress.io/gateway-controller"
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: higress-gateway
  namespace: higress-system
spec:
  gatewayClassName: higress-gateway
  listeners:
  - name: http1
    port: 11111
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  - name: http2
    port: 22222
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  - name: foobar-https
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      certificateRefs:
      - kind: Secret
        name: wildcard-foobar-com
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: myroute
  namespace: default
spec:
  parentRefs:
  - name: higress-gateway
    namespace: higress-system
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /nnn
    filters:
    - type: RequestHeaderModifier
      requestHeaderModifier:
        add:
        - name: my-added-header
          value: added-value-higress
    backendRefs:
    - name: foo-service
      port: 5678
  - matches:
    - path:
        type: PathPrefix
        value: /by-nacos
    backendRefs:
    - name: service-provider.DEFAULT-GROUP.public.nacos
      group: networking.higress.io
```

  - 按[这个文档](https://higress.io/zh-cn/docs/plugins/intro/#%E9%80%9A%E8%BF%87-higress-wasmplugin-crd-%E8%BF%9B%E8%A1%8C%E9%85%8D%E7%BD%AE ) 部署wasm plugin，并将其绑定在myroute上， 没有达到预期效果，没生效。
```
apiVersion: extensions.higress.io/v1alpha1
kind: WasmPlugin
metadata:
  name: request-block
  namespace: higress-system
spec:
  defaultConfig:
    block_urls:
    - swagger.html
    - foo=bar
    case_sensitive: false
  matchRules:
   # 路由级生效配置
  - ingress:
    - default/myroute
    config:
      block_headers:
      - example-key
      - example-value
  url: oci://higress-registry.cn-hangzhou.cr.aliyuncs.com/plugins/request-block:1.0.0
```

### Ⅲ. Describe what you expected to happen
  - 希望higress 的 wasm plugin 除了可以全局生效，也可以在局部范围生效，针对域名、针对路由规则等
