### ISSUE TITLE
e2e: add testcases for destination annotations

### ISSUE THREAD

**Issue by johnlanni** [alibaba/higress#860]
## Why do you need it?

annotations: 
+ `higress.io/destination`

## How could it be?

single destiantion:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    higress.io/destination:  " bar-service.default.svc.cluster.local:5678"
  name: echo
  namespace: default
spec:
  ingressClassName: higress
  rules:
  - http:
      paths:
      - backend:
          resource:
            apiGroup: networking.higress.io
            kind: McpBridge
            name: default
        path: /echo
        pathType: Prefix
```

multiple destiantions:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    higress.io/destination: |
      33% service-provider.DEFAULT-GROUP.public.nacos
      33% service-provider-gray.DEFAULT-GROUP.public.nacos
      34% bar-service.default.svc.cluster.local:5678
  name: echo
  namespace: default
spec:
  ingressClassName: higress
  rules:
  - http:
      paths:
      - backend:
          resource:
            apiGroup: networking.higress.io
            kind: McpBridge
            name: default
        path: /echo
        pathType: Prefix
```

## Other related information
+ https://github.com/alibaba/higress/tree/main/test
+ https://github.com/alibaba/higress/issues/190
