### ISSUE TITLE
use envoyfilter to add cluster cause higress-controller dump, some envoyfilter config invalid  may not cause this BIG problem

### ISSUE THREAD

**Issue by alexzzh** [alibaba/higress#871]
### Ⅰ. Issue Description
  - when test ext_authz by envoyfilter,  unluckly,  we met  higress-controller dump when use invalid envoyfilter config,  that's all right?  maybe，is ISTIO bug or not a bug.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)
  - apply  envoyfilter content below, you can see higress-controller dump,  change "static" to "STATIC", everything is ok.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: apply-ext-authz
  namespace: higress-system
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      listener:
        name: 0.0.0.0_4006
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: INSERT_BEFORE
      value: 
        name: envoy.filters.http.ext_authz
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
          http_service:
            server_uri:
              uri: ext-authz
              cluster: ext-authz
              timeout:  2s
            authorization_request:
              allowed_headers:
                patterns:
                - exact: App-Name
                  ignore_case: true
                - exact: Aes-ID
                  ignore_case: true
                - exact: Ant-ID
                  ignore_case: true
                - exact: App-ID
                  ignore_case: true
                - exact: Session-ID
                  ignore_case: true
                - exact: Verify-ID
                  ignore_case: true
          failure_mode_allow: true
          with_request_body:
            max_request_bytes: 4294967295
            allow_partial_message: true
  - applyTo: HTTP_ROUTE
    match:
      context: GATEWAY
      listener:
        name: 0.0.0.0_4006
    patch:
      operation: MERGE
      value:
        match:
          prefix: /aaaaa
        typed_per_filter_config:
          envoy.filters.http.ext_authz:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute
            disabled: true
  - applyTo: CLUSTER
    match:
      context: GATEWAY
    patch:
      operation: ADD
      value:
        name: ext-authz
        connect_timeout: 5s
        type: static 
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: ext-authz
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 10.0.229.82
                    port_value: 80
                    ipv4_compat: true
```
  - higress-controller log
  
```
2024-03-14T07:51:51.411579Z	info	ads	full push happen, reason:[config]
2024-03-14T07:51:51.512912Z	info	ads	Push debounce stable[8] 1 for config EnvoyFilter/higress-system/apply-ext-authz: 100.377561ms since last change, 100.377489ms since last push, full=true
2024-03-14T07:51:51.526603Z	error	model	failed to build envoy filter value: Envoy filter: unknown value "\"static\"" for enum envoy.config.cluster.v3.Cluster.DiscoveryType
2024-03-14T07:51:51.527269Z	info	ads	XDS: Pushing:2024-03-14T07:51:51Z/8 Services:11 ConnectedEndpoints:1  Version:2024-03-14T07:51:51Z/8
panic: interface conversion: protoreflect.ProtoMessage is nil, not *envoy_config_cluster_v3.Cluster

goroutine 28439 [running]:
istio.io/istio/pilot/pkg/networking/core/v1alpha3/envoyfilter.InsertedClusters(0x3, 0x1?)
	istio.io/istio/pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go:154 +0x195
istio.io/istio/pilot/pkg/networking/core/v1alpha3.clusterPatcher.insertedClusters(...)
	istio.io/istio/pilot/pkg/networking/core/v1alpha3/cluster.go:323
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).buildClusters(0xc000effb00, 0xc000ef9600, 0xc000ed2e10, {0xc0015123c0, 0x1, 0xb})
	istio.io/istio/pilot/pkg/networking/core/v1alpha3/cluster.go:166 +0x9f6
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).BuildClusters(0x28d9e00?, 0xc000ef9600, 0xc000ed2e10)
	istio.io/istio/pilot/pkg/networking/core/v1alpha3/cluster.go:92 +0x37e
istio.io/istio/pilot/pkg/xds.CdsGenerator.Generate({0x0?}, 0xc000ef9600?, 0x0?, 0xc0016f73a0?, 0xc000ed2e10?)
	istio.io/istio/pilot/pkg/xds/cds.go:76 +0xb5
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).pushXds(0xc0005bf080, 0xc000f8c900, 0xc0015acb40, 0xc0014022c0, 0xc000ed2e10)
	istio.io/istio/pilot/pkg/xds/xdsgen.go:192 +0x279
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).pushConnection(0xc0005bf080, 0xc000f8c900, 0xc001a5d090)
	istio.io/istio/pilot/pkg/xds/ads.go:758 +0x129f
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).Stream(0xc0005bf080, {0x33c6618, 0xc001986f50})
	istio.io/istio/pilot/pkg/xds/ads.go:353 +0xa75
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).StreamAggregatedResources(0xc0013cab70?, {0x33c6618?, 0xc001986f50?})
	istio.io/istio/pilot/pkg/xds/ads.go:249 +0x25
github.com/envoyproxy/go-control-plane/envoy/service/discovery/v3._AggregatedDiscoveryService_StreamAggregatedResources_Handler({0x2e67c00?, 0xc0005bf080}, {0x33c2aa8?, 0xc0010e2300})
	github.com/envoyproxy/go-control-plane@v0.9.10-0.20210907150352-cf90f659a021/envoy/service/discovery/v3/ads.pb.go:298 +0x9f
google.golang.org/grpc.(*Server).processStreamingRPC(0xc000c99a40, {0x33c77b8, 0xc000e04f00}, 0xc000e06a20, 0xc0011a9200, 0x4f9c540, 0x0)
	google.golang.org/grpc@v1.42.0/server.go:1540 +0xf3c
google.golang.org/grpc.(*Server).handleStream(0xc000c99a40, {0x33c77b8, 0xc000e04f00}, 0xc000e06a20, 0x0)
	google.golang.org/grpc@v1.42.0/server.go:1620 +0x9ea
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.42.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.42.0/server.go:919 +0x28a
```
