### ISSUE TITLE
使用higress网关访问后端协议为grpc，无法访问。

### ISSUE THREAD

**Issue by ldl-home** [alibaba/higress#906]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via [ASRC](https://security.alibaba.com/)(Alibaba Security Response Center) where the issue will be triaged appropriately.**

- [ ] I have searched the [issues](https://github.com/alibaba/higress/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
基于k8s环境使用如下配置创建了一个higress访问的域名，后端服务提供grpc
```
---
apiVersion: v1
kind: Service
metadata:
  namespace: higress-system
  name: go-ping-s
spec:
  selector:
    app: go-ping-s
  ports:
    - name: grpc
      port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: higress-system
  annotations:
    higress.io/backend-protocol: "GRPC"
  name: go-ping-s
spec:
  ingressClassName: higress
  rules:
    - host: grpc.test.com
      http:
        paths:
          - backend:
              service:
                name: go-ping-s
                port: 
                  number: 80
            path: /
            pathType: Exact
```
### Ⅱ. Describe what happened

通过 postman的grpc协议调用grpc.test.com其中的一个ping方法。无法到后端服务

日志如下
{"authority":"grpc.test.com:80","bytes_received":"0","bytes_sent":"0","downstream_local_address":"192.168.201.50:80","downstream_remote_address":"192.168.201.103:56441","duration":"0","istio_policy_status":"-","method":"POST","path":"/ping.Ping/Ping","protocol":"HTTP/2","request_id":"dd357754-f453-40aa-be3a-eb5171ee649f","requested_server_name":"-","response_code":"501","response_flags":"NR","route_name":"-","start_time":"2024-04-08T05:47:46.917Z","trace_id":"-","upstream_cluster":"-","upstream_host":"-","upstream_local_address":"-","upstream_service_time":"-","upstream_transport_failure_reason":"-","user_agent":"grpc-node-js/1.8.10","x_forwarded_for":"192.168.201.103"}

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- Higress version:  
- OS :
- Others:
