### ISSUE TITLE
higress从1.3.0升级1.3.5版本后，virtualservice配置路由404

### ISSUE THREAD

**Issue by listapp99** [alibaba/higress#916]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via [ASRC](https://security.alibaba.com/)(Alibaba Security Response Center) where the issue will be triaged appropriately.**

- [ ] I have searched the [issues](https://github.com/alibaba/higress/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
higress从1.3.0升级1.3.5版本后，virtualservice配置路由404

### Ⅱ. Describe what happened
测试环境：有一套higress网关，一套istio网关，分别在不同的命名空间
curl -v demo.abc.def.com概率性返回404
higress-controller日志
2024-04-21T17:52:11.289873Z     warn    constructed http route config for route higress-rds-80.demo.abc on port 80 with no vhosts; Setting up a default 404 vhost
2024-04-21T17:52:23.706454Z     warn    constructed http route config for route higress-rds-80.demo.abc.def.com on port 80 with no vhosts; Setting up a default 404 vhost

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: demo-vs
  namespace: default
spec:
  gateways:
  - default/gw2
  - default/gw1
  hosts:
  - demo.abc
  - demo.abc.def.com
  http:
  - match:
    - authority:
        prefix: demo.abc
      gateways:
      - default/gw1
    retries: {}
    route:
    - destination:
        host: demo-ping.default.svc.cluster.local
        port:
          number: 8888
  - match:
    - authority:
        prefix: demo.abc.def.com
      gateways:
      - default/gw2
    retries: {}
    route:
    - destination:
        host: demo-ping.default.svc.cluster.local
        port:
          number: 8888
```
          
其中demo-ping.default.svc.cluster.local是后端service
          
istio的gateway
```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: gw1
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 8081
      protocol: HTTP
```
      
higress的gateway
```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: gw2
  namespace: default
spec:
  selector:
    app: higress-gateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP      
```

### Ⅲ. Describe what you expected to happen
配置能找到路由

### Ⅵ. Environment:

- Higress version:  1.3.5
- OS : linux，k8s
- Others:
