### ISSUE TITLE
Http2Rpc配置两个Http2Rpc，路由转发失败

### ISSUE THREAD

**Issue by java4candy** [alibaba/higress#926]
### Ⅰ. Issue Description

Http2Rpc配置两个Http2Rpc，路由转发失败

### Ⅱ. Describe what happened

通过Higress，实现HTTP转同一个Dubbo下的两个Service时，配置了两个Ingress后，对应配置任意一个Http2Rpc，都可以正常访问。
同时配置两个Http2Rpc，两个API接口都返回失败：
NOT_FOUND: Could not resolve /account/name to a method
NOT_FOUND: Could not resolve /echo/echo to a method

### Ingress && Http2Rpc yaml

- demo source
[dubbo-spring-boot-provider.zip](https://github.com/alibaba/higress/files/15111506/dubbo-spring-boot-provider.zip)

- API
```
curl --location --request GET 'http://x.x.x.x:xxx/echo/echo?p=123'
curl --location --request GET 'http://x.x.x.x:xxx/account/name?p=123'
```
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    higress.io/destination: providers:com.alibaba.edas.boot.EchoService:1.0.0:DUBBO.zookeeper
    higress.io/ignore-path-case: 'false'
    higress.io/rpc-destination-name: echo
  labels:
    higress.io/resource-definer: higress
  name: echo-higress
  namespace: higress-system
spec:
  ingressClassName: higress
  rules:
    - http:
        paths:
          - backend:
              resource:
                apiGroup: networking.higress.io
                kind: McpBridge
                name: default
            path: /echo
            pathType: Prefix
status:
  loadBalancer: {}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    higress.io/destination: providers:com.alibaba.edas.boot.AccountService:1.0.0:DUBBO.zookeeper
    higress.io/ignore-path-case: 'false'
    higress.io/rpc-destination-name: account
  labels:
    higress.io/resource-definer: higress
  name: account-higress
  namespace: higress-system
spec:
  ingressClassName: higress
  rules:
    - http:
        paths:
          - backend:
              resource:
                apiGroup: networking.higress.io
                kind: McpBridge
                name: default
            path: /account
            pathType: Prefix
status:
  loadBalancer: {}



apiVersion: networking.higress.io/v1
kind: Http2Rpc
metadata:
  name: echo
  namespace: higress-system
spec:
  dubbo:
    group: DUBBO
    methods:
      - httpMethods:
          - GET
        httpPath: /echo/echo
        params:
          - paramKey: p
            paramSource: QUERY
            paramType: java.lang.String
        serviceMethod: echo
    service: com.alibaba.edas.boot.EchoService
    version: 1.0.0


apiVersion: networking.higress.io/v1
kind: Http2Rpc
metadata:
  name: account
  namespace: higress-system
spec:
  dubbo:
    group: DUBBO
    methods:
      - httpMethods:
          - GET
        httpPath: /account/name
        params:
          - paramKey: p
            paramSource: QUERY
            paramType: java.lang.String
        serviceMethod: name
    service: com.alibaba.edas.boot.AccountService
    version: 1.0.0
```

### Environment:

- Higress version:  1.3.3/1.3.6
- OS : K8S v1.26.7
