### ISSUE TITLE
希望higress-https中的全局https证书配置可以用于ingress中secret不存在时的兜底

### ISSUE THREAD

**Issue by zzjin** [alibaba/higress#978]
- [x] I have searched the [issues](https://github.com/alibaba/higress/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

When update to 1.4.0-rc1, and setting #854 (without auto cert, just self-signed cert), users cannot access https ingress.

### Ⅱ. Describe what happened

Users can only access one https route.

### Ⅲ. Describe what you expected to happen

All ingress route over https can access normally.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

Apply higress version 1.4.0-rc1, apply CRs below:

```yaml
apiVersion: v1
data:
  cert: |
    automaticHttps: true
    renewBeforeDays: 1
    credentialConfig:
    - domains:  
        - "*.34.84.109.10.nip.io"
        - "34.84.109.10.nip.io"
      tlsSecret: wildcard-cert
kind: ConfigMap
metadata:
  name: higress-https
  namespace: higress-system
```
```yaml
apiVersion: v1
data:
  ca.crt: aaa(replace with any valid cert)
  tls.crt: bbb
  tls.key: ccc
kind: Secret
metadata:
  annotations:
    cert-manager.io/alt-names: 34.84.109.10.nip.io,*.34.84.109.10.nip.io
    cert-manager.io/certificate-name: sealos-cloud
    cert-manager.io/common-name: 34.84.109.10.nip.io
    cert-manager.io/ip-sans: ""
    cert-manager.io/issuer-group: ""
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/issuer-name: selfsigned-issuer
    cert-manager.io/uri-sans: ""
  name: wildcard-cert
  namespace: higress-system
type: kubernetes.io/tls

```
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: sealos-desktop
  namespace: sealos
spec:
  rules:
    - host: 34.84.109.10.nip.io
      http:
        paths:
          - backend:
              service:
                name: desktop-frontend
                port:
                  number: 3000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - 34.84.109.10.nip.io
      secretName: wildcard-cert
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: applaunchpad-frontend
  namespace: applaunchpad-frontend
spec:
  rules:
    - host: applaunchpad.34.84.109.10.nip.io
      http:
        paths:
          - backend:
              service:
                name: applaunchpad-frontend
                port:
                  number: 3000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - applaunchpad.34.84.109.10.nip.io
      secretName: wildcard-cert
```

There are 3 ns and one secret higress-system/wildcard-cert exists, no other secrets exists.

### Ⅵ. Environment:

- Higress version:  1.4.0-rc1
- OS : kubernetes 1.25.6
- Others:
